foundryvtt/dnd5e

system.json
- Adds `id`, `authors`, & `compatibility`
- Removes `author`
- Updates verified core version to 10
Resolves #1611
=> [#1611] Update manifest to include v10 fields

module/applications/actor/base-sheet.mjs
=> [#1660] correctly await `item.getChatData` when expanding sheet item

dnd5e.css, dnd5e.mjs, less/items.less, module/advancement/advancement-manager.mjs, module/documents/chat-message.mjs
- Fix deprecation warning accessing world migration flag
- Fix deprecation warning in class advancement
- Fix deprecation warning in `applyChatCardDamage`
- Fix alignment issue in advancement configuration mode link
=> Various deprecation warning fixes

module/dice/dice.mjs
=> [#1698] Fix rollDeathSave not respecting roll mode when roll is fast forwarded

.github/workflows/release.yml, templates/items/equipment.hbs
- Don't rename javascript map file in build script
- Fix the partial link to mountain equipment
=> Fix javascript map & mountable equipment sheet

package-lock.json, package.json, utils/packs.mjs
- Adds log messages to make it clear what packs the system is extracting, compiling, or cleaning
=> Improve gulp logging

module/config.mjs
=> [#1581] Add d4 hit die denomination

module/canvas/token.mjs
=> [#1880] Fix token HP bar height

module/advancement/advancement-selection.mjs, module/config.mjs, module/documents/item.mjs
=> [#1807] Move advancement type setup to CONFIG

dnd5e.mjs, lang/en.json, module/applications/actor/base-sheet.mjs, module/data/_module.mjs, module/data/abstract.mjs, module/data/item/_module.mjs, module/data/item/loot.mjs, module/data/item/templates/item-description.mjs, module/data/item/templates/physical-item.mjs, module/documents/item.mjs, module/migration.mjs
Adds the data model for Loot items, which includes the Item Description template and the Physical Item template.
=> [#1835] Add `loot` data model

module/data/item/_module.mjs, module/data/item/templates/mountable.mjs, module/data/item/weapon.mjs, template.json
Adds `WeaponData` & `MountableTemplate`
=> [#1835] Create system data model for weapons

.gitignore
Since I've seen multiple ongoing PRs add this, I figured it would be better to make a single, targeted PR that could be merged in relatively quickly.
=> Add VSCode IDE directory to .gitignore

module/advancement/advancement.mjs, module/data/fields.mjs, module/data/item/_module.mjs, module/data/item/class.mjs, module/documents/item.mjs, module/migration.mjs
Classes with the full advancement integration (something to review while the consumable debate continues).
=> [#1835] Create system data model for classes

module/data/abstract.mjs, module/data/item/_module.mjs, module/data/item/consumable.mjs, module/data/item/templates/activated-effect.mjs
This one makes use of the more complex schema merging behavior to add the `autoDestroy` field to the `uses` object from `ActivatedEffectTemplate`.
=> [#1835] Create system data model for consumables

templates/apps/skill-config.hbs
Changes originally made by @arbron, extracted from https://github.com/foundryvtt/dnd5e/pull/1854
=> Add ability score selection to the skills configuration.

module/applications/actor/base-sheet.mjs, module/applications/actor/character-sheet.mjs, module/applications/actor/group-sheet.mjs, module/applications/actor/npc-sheet.mjs, module/applications/actor/vehicle-sheet.mjs, module/documents/actor/actor.mjs, module/documents/item.mjs, templates/actors/character-sheet.hbs, templates/actors/npc-sheet.hbs, templates/actors/parts/actor-features.hbs, templates/actors/parts/actor-inventory.hbs, templates/actors/parts/actor-spellbook.hbs, templates/actors/parts/actor-traits.hbs, templates/actors/vehicle-sheet.hbs
Apologies for how clumsy some of this is. The guiding principles here were:
- It is ok to pass the real actor or item instance into the template data as it's only for reading.
- Avoid mutating a property of the real actor or item instance as part of template data or roll data preparation.
=> Rework sheet and roll data preparation to avoid mutating actor and item state

module/applications/actor/armor-config.mjs, module/applications/actor/base-sheet.mjs, module/applications/item/ability-use-dialog.mjs, module/applications/item/item-sheet.mjs, module/dice/damage-roll.mjs, module/documents/item.mjs, templates/apps/actor-armor.hbs, templates/items/spell.hbs
- Closes #1817 
- Closes #1639 
- Closes #1891 
- Closes #1958 
- Closes #1238 
- Closes #1239
=> Assorted bug fixes

module/data/actor/character.mjs, module/data/actor/npc.mjs, module/data/actor/templates/common.mjs, module/data/actor/vehicle.mjs, module/migration.mjs, system.json, template.json
- Closes #2040 
- Closes #2043
=> 2.1.2 Validation Adjustments

module/applications/actor/base-sheet.mjs, module/data/actor/group.mjs, module/data/actor/templates/attributes.mjs, templates/apps/movement-config.hbs
- Create spell scrolls from spells dropped onto vehicle sheets #2055 
- Fix units not being available for actor movement #2057 
- Allow decimals in movement values (to support metric values) #2058
- Fix items created directly on sheets not getting proper properties #2066
=> [#2055, #2057, #2058, #2066] Fix various issues with sheets

package-lock.json, package.json
Fixing some stuff that broke when I upgraded my Node version :).
=> [#2091] Update dependency versions to support Node 19

dnd5e.css, lang/en.json, less/actors.less, module/applications/actor/_module.mjs, module/applications/actor/ability-config.mjs, module/applications/actor/armor-config.mjs, module/applications/actor/base-config.mjs, module/applications/actor/base-sheet.mjs, module/applications/actor/hit-dice-config.mjs, module/applications/actor/hit-points-config.mjs, module/applications/actor/initiative-config.mjs, module/applications/actor/movement-config.mjs, module/applications/actor/senses-config.mjs, module/applications/actor/sheet-flags.mjs, module/applications/actor/skill-config.mjs, module/applications/actor/trait-selector.mjs, templates/actors/parts/actor-spellbook.hbs
=> [#2041] Disable fields that are overridden by an Active Effect and display a tooltip explaining why they cannot be edited

.eslintrc.json, module/applications/actor/base-sheet.mjs, module/applications/item/item-sheet.mjs, module/data/actor/character.mjs, module/data/actor/npc.mjs, module/data/item/templates/activated-effect.mjs, module/documents/item.mjs, module/migration.mjs
Just a few code style cleanup issues.
=> Fix various linting issues

module/applications/journal/class-sheet.mjs
=> [#2124] Fix bug with dropping classes & subclasses onto class journal pages

module/applications/actor/base-sheet.mjs, module/applications/journal/class-sheet.mjs
Brings back two bug fixes that were implemented on the `2.2.x` branch so users don't have to wait for that to enjoy these bug fixes.
Resolves #2114 
Resolves #2124
=> [#2114, #2124] Fix delete bug & subclass bug on class journals

.gitignore, dnd5e.mjs, module/applications/item/item-sheet.mjs, module/config.mjs, module/data/abstract.mjs, module/documents/actor/actor.mjs, module/documents/token.mjs, module/migration.mjs, system.json, templates/apps/initiative-config.hbs, templates/apps/proficiency-config.hbs, templates/apps/skill-config.hbs
- Added LevelDB files to .gitignore.
- Ensure actor preparation does not throw an error for actors with module-provided sub-types.
- Use new explicit trackableAttributes configuration to include derived attributes.
=> v11 compatibility updates.

dnd5e.css, dnd5e.mjs, less/journal.less
Closes #2176.
Minimum width:
Minimum height:
=> [#2176] Add min height and width to SRD Rules compendium

module/documents/actor/actor.mjs
Closes https://github.com/foundryvtt/dnd5e/issues/2202
=> Use item's rollData on item recharge

module/documents/item.mjs
=> Gets rid of deprecation warning on attacks

module/documents/actor/actor.mjs
Fixes https://github.com/foundryvtt/dnd5e/issues/2195
=> Keep class active effects on polymorph

module/applications/advancement/hit-points-flow.mjs
Fixes https://github.com/foundryvtt/dnd5e/issues/2221
=> Add missing import in hit-points-flow

lang/en.json, module/applications/item/item-sheet.mjs, module/data/item/consumable.mjs, templates/items/consumable.hbs
Enables setting of physical properties on ammunition (e.g. "Adamantine", "Magical", or "Silvered").
=> [#2036] Add physical properties to ammunition

wiki/Home.md, wiki/Modifying-Your-Game-with-Scripts.md
Adds a basic guide for World Scripts, and provides dnd5e specific examples (will need some help for more examples, @krbz999 )
Closes #2365
=> Wiki scripts

lang/en.json, module/applications/item/item-sheet.mjs, module/config.mjs, module/data/actor/templates/creature.mjs, module/data/item/equipment.mjs, module/data/item/spell.mjs, module/data/item/templates/equippable-item.mjs, module/data/item/tool.mjs, module/data/item/weapon.mjs, module/documents/actor/actor.mjs, module/documents/item.mjs, module/migration.mjs, template.json, templates/items/equipment.hbs, templates/items/tool.hbs, templates/items/weapon.hbs
- Closes #1082 
- Closes #2327 
- Closes #2305
=> [#1082] Add proficiency automation for weapons, armour, and tools.

lang/en.json, module/config.mjs
=> Add arcane shot class feature type

dnd5e.css, less/actors.less
=> Update attuned/not attuned icon colors

system.json
Resolves #2310 
Implements Compendium Folders for new worlds with the following structure
```
**DnD5e SRD Content** #cd2c1e
rules
tables
heroes
**Character Features** #b72c1f
classes
subclasses
classfeatures
backgrounds
races
**Items & Spells** #941919 
items
spells
tradegoods
**Monsters** #7d160c
monsters
monsterfeatures
```
=> pack folders

wiki/Advancement-Type-Hit-Points.md, wiki/Advancement-Type-Item-Choice.md, wiki/Advancement-Type-Item-Grant.md, wiki/Advancement-Type-Scale-Value.md, wiki/Advancement-User-Guide.md, wiki/Advancement.md, wiki/Custom-Class-Advancement.md, wiki/Dynamic-Module-Art.md, wiki/FAQ.md, wiki/Hooks.md, wiki/Roll-Formulas.md
Files were deleted when 2.3.0 was pushed to `publish-wiki`
fixes #2437
=> Restore wiki files

lang/en.json
=> [#2419] Remove the dot from 'Remarkable Athlete.'.

module/applications/item/item-sheet.mjs
=> [#2405] Add `scrollY` properties to match class tabs

module/data/abstract.mjs, module/data/actor/character.mjs, module/data/actor/npc.mjs, module/data/actor/templates/common.mjs, module/data/actor/templates/creature.mjs, module/data/actor/vehicle.mjs, module/data/item/class.mjs, module/data/item/equipment.mjs, module/data/item/feat.mjs, module/data/item/spell.mjs, module/data/item/templates/action.mjs, module/data/item/templates/activated-effect.mjs, module/data/item/templates/equippable-item.mjs, module/data/item/templates/item-description.mjs, module/data/item/templates/mountable.mjs, module/data/item/templates/physical-item.mjs, module/data/item/tool.mjs, module/data/item/weapon.mjs, module/data/shared/currency.mjs
These changes make it possible to use `cleanData`, `validateJoint`, and `shimData` in a template.
=> Improve `SystemDataModel`

module/applications/actor/base-sheet.mjs
Closes #968 
Modified _getSenses(systemData)
Removes senses.special
Adds a senses.customN for each special senses separated by a semi-colon (N being the index starting from 1)
=> [#968] Update base-sheet.mjs

module/documents/advancement/ability-score-improvement.mjs
=> [#2470] Fix issue with ASI being applied incorrectly when effect targets ability

module/documents/active-effect.mjs
=> [#2444] Modify effect defaults on creation

module/documents/active-effect.mjs
Open delete dialogue to confirm deletion of active effects on the effects page.
=> Require confirmation to delete effects.

module/documents/active-effect.mjs
=> Revert "Require confirmation to delete effects."

module/documents/actor/actor.mjs
=> [#2451] Fix bug with custom skills & abilities causing transformation to fail

module/data/item/consumable.mjs, module/data/item/loot.mjs, module/data/item/templates/physical-item.mjs
This shows up as a 'tag' in chat messages and in the actor sheet when expanded.
=> [#2501] Show price on loot and consumable items

module/applications/actor/base-sheet.mjs, module/applications/actor/sheet-mixin.mjs
Also moved the contextmenu into the 'isEditable' section since it's relevant only to editing, currently.
=> [#2350] Require being a non-compendium actor to make any rolls on the sheet

.github/workflows/release.yml, system.json
~~**Note:** This works fine at the moment with language files and templates, but CSS changes aren't properly picked up. This appears to be an issue with the way our gulp script is compiling the CSS files. The changes to the build scripts in #2458 resolve this problem.~~
=> [#2440] Add hotReload flags for development, strip in release script

module/documents/item.mjs
=> Move `needsConfiguration` to below pre hook

dnd5e.css, less/apps.less, less/items.less
Adding some padding so you won't need to be so precise to edit one part of the description.
=> Make the item description edit buttons slightly easier to hit

wiki/Modifying-Your-Game-with-Scripts.md
Adds world script examples from #2372 
Also did a little bit of formatting cleanup
Updated some wordings
=> Wiki - More World Scripts

module/config.mjs, module/enrichers.mjs
=> Fix enrichers using full key rather then short key when calling roll method

wiki/Enrichers.md, wiki/Modifying-Your-Game-with-Scripts.md, wiki/Roll-Formulas.md
Updated the Languages World Script examples to close #2598, thanks to etiquettestartshere
Added a list of ToolIds to the Enrichers page, because some of them are not intuitive
=> Wiki - WS Language update and Enricher ToolIds

module/documents/chat-message.mjs
=> Apply critical/fumble class only to the correct elements

module/applications/actor/vehicle-sheet.mjs, module/applications/item/ability-use-dialog.mjs, module/applications/item/item-sheet.mjs, module/config.mjs, module/data/item/consumable.mjs, module/data/item/equipment.mjs, module/data/item/feat.mjs, module/data/item/fields/item-type-field.mjs, module/data/item/loot.mjs, module/data/item/templates/item-type.mjs, module/data/item/tool.mjs, module/data/item/weapon.mjs, module/documents/actor/actor.mjs, module/documents/actor/trait.mjs, module/documents/item.mjs, module/migration.mjs, template.json, templates/items/consumable.hbs, templates/items/equipment.hbs, templates/items/tool.hbs, templates/items/weapon.hbs, utils/packs.mjs
Draft of #2168 fix, with the changes requested by @Fyorl [here](https://github.com/foundryvtt/dnd5e/pull/2242#issuecomment-1771601242).
=> [#2168] Standardize item system type format

module/documents/actor/actor.mjs
=> [#2687] Optional chain RT

module/applications/actor/group-sheet.mjs
=> [#2694] Prevent race being dropped on Group sheet

module/applications/actor/_module.mjs, module/applications/actor/base-sheet.mjs, module/applications/actor/group-sheet.mjs, module/applications/actor/sheet-mixin.mjs
=> [#2697] Expose actor sheet mixin

module/canvas/ability-template.mjs, module/documents/item.mjs
=> Add placeTemplate hooks

module/config.mjs, module/documents/actor/actor.mjs
=> [#1415] Prelocalize creature types

packs/src/heroes/riswynn-dwarf-rogue.json
=> Add humanoid to Creature Type value

module/data/item/equipment.mjs
=> [#2716] Show AC only on armor/shield/vehicle

module/documents/chat-message.mjs
=> Prevent chat card rendering from failing if sender has been removed from message

less/v1/apps.less
=> [#2842] use flex-basis auto for checkboxes in flex labels

module/documents/actor/actor.mjs
Adds a hook to see what calculations have been made in the applyDamage function.
=> Add a `dnd5e.calculateDamage` hook

templates/actors/tabs/character-details.hbs
=> [#2903] Show skill tooltip on the skill row, rather on the skill label

module/documents/item.mjs
=> [#2770] Toggle effect on actor if it already exists

module/documents/item.mjs
=> [#2838] Don't collapse chat card if the user clicked a link or button in the collapsible region

less/v2/chat.less, module/documents/chat-message.mjs
Closes #2911
Observer view on the left, speaker view on the right
=> [#2911] Privatize item roll cards

module/applications/item/container-sheet.mjs
=> [#2895] convert spell to scroll when dropping in container

lang/en.json, module/documents/actor/actor.mjs, module/tooltips.mjs
=> [#2883] Support passive ability checks and passive skill checks with arbitrary base skills

module/canvas/shaders/token-ring-shader.mjs
Must not be merged and released before Prototype 2 has been released.
=> Update `TokenRingSamplerShader` for V12

module/canvas/shaders/token-ring-shader.mjs, module/canvas/token-ring.mjs, module/canvas/token.mjs
- Urgent: fixed a *bug* in v12 token ring batched shader to avoid crashing into a v11 environment.
- Added compatibility with v12 filter effects (and thus, invisibility that needed a special treatment)
=> Added compatibility with v12 condition filters.

module/documents/active-effect.mjs, module/documents/actor/actor.mjs
=> [#2843, #2972] Fix issues with AC bonuses & attribution

module/documents/actor/actor.mjs
=> [#2927] Fix token ring effects not appearing on linked tokens

dnd5e.mjs, less/v2/apps.less
=> [#2939, #2940] Fix sidebar branding appearing twice, not showing update badge

module/data/item/consumable.mjs, module/data/item/equipment.mjs, module/data/item/feat.mjs, module/data/item/weapon.mjs
=> [#2931] Fallback to default item type label

less/v2/apps.less, less/v2/character.less, module/applications/actor/group-sheet.mjs, module/canvas/token.mjs, module/documents/actor/actor.mjs, module/documents/token.mjs, templates/actors/character-sheet-2.hbs
=> [#2845] Display temp max on character sheet HP bar

module/applications/actor/trait-selector.mjs
* Disable choices that have been removed by an override.
* Disable `custom` if overridden.
* Disable `bypasses` if overridden.
=> Fix: `ActiveEffect` changes are persisted when submitting the `TraitSelector` sheet

module/applications/actor/spell-slots-config.mjs
=> Show pact slots in `ActorSpellSlotsConfig` if actor has at least one spell with "pact" preparation mode

less/elements.less, less/v2/apps.less, less/v2/character.less, less/v2/inventory.less, less/variables.less, ui/ability-score-tab-hc.svg
=> [#2863] Increase contrast on sheet UI when prefers-contrast: more is enabled

module/documents/mixins/document.mjs
=> Don't forward database operations to the type data model in V12

.github/workflows/release.yml
Closes #2841 
Closes #3110 
Closes #3111 
Closes #3113
=> [#2841, #3110, #3111, #3113] Update build script to fix issues & remove deprecations

module/applications/actor/character-sheet-2.mjs
Easy to guess how these were missed. :)
=> Add .label in two missing places

module/applications/item/ability-use-dialog.mjs
=> [#3200] Fix available uses displaying as `null` in ability use dialog

less/v1/items.less, less/v2/chat.less, module/applications/components/damage-application.mjs, module/documents/chat-message.mjs, module/documents/item.mjs, templates/chat/item-card.hbs, templates/chat/roll-breakdown.hbs
This will break any existing chat cards, but I think that's acceptable for a .1 release. I think the clean up of tech debt around having to set `height`s manually in javascript is worth it.
=> [#3099] Move to pure CSS solution for collapsibles.

packs/_source/monsters/dragon/adult-white-dragon.json
=> Fix Adult white dragon wing attack

dnd5e.mjs, module/documents/active-effect.mjs, module/documents/token.mjs, templates/shared/active-effects.hbs
https://github.com/foundryvtt/foundry-vtt/pull/1913
=> Adjust `ActiveEffect.fromStatusEffect` for V12

module/data/actor/templates/attributes.mjs, templates/apps/concentration-config.hbs, templates/apps/initiative-config.hbs
Just like initiative, it needs to be possible to set the ability to a blank option to default to the default.
=> Add blank option in Concentration config

wiki/Active-Effect-Guide.md, wiki/Roll-Formulas.md
=> Update roll data and active effect wikis for 3.x

module/applications/item/ability-use-dialog.mjs
=> [#3301] Remove everything related to conc if the item does not require conc at all

module/data/item/fields/summons-field.mjs, module/data/token/token-system-flags.mjs
Moved the stored origin flag from the token to the actor, which gets around the bug that seems to exist in core with updating `ActorDelta`.
=> [#3308] Fix item changes not being retained on summons

module/applications/advancement/item-choice-flow.mjs, module/documents/advancement/item-grant.mjs
=> [#3323, #3324] Fix advancement issues with missing linked items

module/data/item/templates/equippable-item.mjs
=> [#3297] Prevent magical bonuses from applying if the item is not magical

module/utils.mjs
An oversight (who ever uses kh/kl, amirite?)
=> Add kh and kl as valid dice modifiers in Dice Scale Values

packs/_source/classfeatures/warlock/eldritch-invocations/ascendant-step.json, packs/_source/classfeatures/warlock/eldritch-invocations/bewitching-whispers.json, packs/_source/classfeatures/warlock/eldritch-invocations/chains-of-carceri.json, packs/_source/classfeatures/warlock/eldritch-invocations/dreadful-word.json, packs/_source/classfeatures/warlock/eldritch-invocations/lifedrinker.json, packs/_source/classfeatures/warlock/eldritch-invocations/master-of-myriad-forms.json, packs/_source/classfeatures/warlock/eldritch-invocations/minions-of-chaos.json, packs/_source/classfeatures/warlock/eldritch-invocations/mire-the-mind.json, packs/_source/classfeatures/warlock/eldritch-invocations/one-with-shadows.json, packs/_source/classfeatures/warlock/eldritch-invocations/otherworldly-leap.json, packs/_source/classfeatures/warlock/eldritch-invocations/sculptor-of-flesh.json, packs/_source/classfeatures/warlock/eldritch-invocations/sign-of-ill-omen.json, packs/_source/classfeatures/warlock/eldritch-invocations/thirsting-blade.json, packs/_source/classfeatures/warlock/eldritch-invocations/visions-of-distant-realms.json, packs/_source/classfeatures/warlock/eldritch-invocations/whispers-of-the-grave.json, packs/_source/classfeatures/warlock/eldritch-invocations/witch-sight.json
Adds the required levels to all of the Eldritch Invocations in the SRD.
=> [#1833] Add level prerequisites to eldritch invocations

module/applications/actor/base-sheet.mjs
=> [#3463] Default to config if skill's ability doesn't exist in src data

lang/en.json, less/v2/inventory.less, module/applications/actor/character-sheet-2.mjs, module/documents/active-effect.mjs, module/documents/item.mjs, module/tooltips.mjs, templates/effects/parts/effect-tooltip.hbs, templates/shared/active-effects2.hbs
=> [#3492] Add tooltips to active effects

module/documents/chat-message.mjs
Related to #2892.
https://github.com/foundryvtt/dnd5e/assets/50169243/d41d7206-0900-4bc5-849b-591e3321b7ba
=> [#2892] Allow for selecting token via any chat message

module/documents/active-effect.mjs
=> Store the level a spell was cast at when concentrating

module/applications/item/ability-use-dialog.mjs, module/data/item/fields/summons-field.mjs
=> [#3524] Add summon level to all summoned creatures

module/documents/item.mjs
Closes #3517.
Something similar I feel should be done for enchantments as well.
=> [#3517] Add spell level to granted and dependent effects

module/utils.mjs
While using the system in V12 (12.231) I encountered a bug where advancement features being pulled from a compendium pack would throw an error and fail to render. You can easily reproduce this by creating a character and attempting to add a class from the compendium pack.
The error was being thrown by the attempted call to `TextEditor._createLegacyContentLink`. I'm not sure why that was deemed necessary.
There is some friction here because now in V12 content link generation is most directly an async operation, but this PR proposes a way to approach the issue using a synchronous workaround that is confirmed to work in V12 and should (but I did not test) work in V11.
=> Propose resolution to synchronous UUID link generation bug

lang/en.json, less/v1/items.less, module/applications/item/item-sheet.mjs, module/data/item/fields/enchantment-field.mjs, module/documents/active-effect.mjs, templates/items/parts/item-action.hbs
Improves the appearance of the list of enchanted items on the item sheet and adds controls for viewing the item and removing the enchantment if it is an item the player owns.
=> [#3305] Improve enchantment list on item sheet, add controls

module/applications/actor/sheet-mixin.mjs, templates/actors/parts/actor-features.hbs
Added min, max, inputmode, and pattern attributes that were used on other item-details on the v1 sheets to the input for actor features. It appears that the inputmode="numeric" is used to bind the _onChangeInputDelta event.
Closes #3401
=> [#3401] Modified actor-features.hbs input node for item-detail

module/canvas/token-placement.mjs
Added clear call for current placement preview if placement was false.
Closes #3659
=> [#3659] Added clear call for preview

packs/_source/items/weapon/blowgun-1.json, packs/_source/items/weapon/blowgun-2.json, packs/_source/items/weapon/blowgun-3.json, packs/_source/items/weapon/blowgun.json, packs/_source/items/weapon/club-1.json, packs/_source/items/weapon/club-2.json, packs/_source/items/weapon/club-3.json, packs/_source/items/weapon/club.json, packs/_source/items/weapon/flail-1.json, packs/_source/items/weapon/flail-2.json, packs/_source/items/weapon/flail-3.json, packs/_source/items/weapon/flail.json, packs/_source/items/weapon/mace-1.json, packs/_source/items/weapon/mace-2.json, packs/_source/items/weapon/mace-3.json, packs/_source/items/weapon/mace.json, packs/_source/items/weapon/pike-1.json, packs/_source/items/weapon/pike-2.json, packs/_source/items/weapon/pike-3.json, packs/_source/items/weapon/pike.json, packs/_source/items/weapon/trident-1.json, packs/_source/items/weapon/trident-2.json, packs/_source/items/weapon/trident-3.json, packs/_source/items/weapon/trident.json
As English is not my mother tongue, I've just taken over the description from @CodeMoWerser .
Close : https://github.com/foundryvtt/dnd5e/issues/3669
=> Update various weapon descriptions and images for accuracy.

wiki/FAQ.md
=> Update FAQ with new spell scroll instructions & 2024 rulebook plans

module/applications/award.mjs
=> [#3719] Make award enricher handle XP 'correctly'

module/applications/advancement/item-choice-flow.mjs
Fixes maximum selection calculation in the `_onDrop` method and removing dropped item if the replacement is deselected so it doesn't give you an extra item.
Closes #3696
=> [#3696] Fix Item Choice replacement with dropped items

wiki/Enrichers.md
=> Item enricher wiki format fix

json/fa-token-mapping.json
=> Update Swarm of Poisonous Snakes image path

lang/en.json, module/data/item/spell.mjs, module/documents/actor/actor.mjs, module/documents/item.mjs, templates/items/spell.hbs
=> [#1351] Allow spells to be linked to a specific class

module/dice/d20-roll.mjs, module/dice/damage-roll.mjs, module/dice/dice.mjs, module/documents/item.mjs
=> [#3761] Pass allowInteractive: false to blind rolls

lang/en.json, module/data/advancement/spell-config.mjs, module/data/item/templates/activated-effect.mjs, module/dice/simplify-roll-formula.mjs, module/documents/actor/actor.mjs, module/migration.mjs, module/utils.mjs
=> [#3742] Replace safeEval with evaluateSync in V12

module/documents/actor/actor.mjs
Closes https://github.com/foundryvtt/dnd5e/issues/3743.
=> Fix polymorphing with Token Ring in V12

module/canvas/token.mjs
targetToken passes the token placeable, so we need to access the token.document to see if the dynamic token ring is enabled
=> fix dynamic token flashing on targeting

module/config.mjs, module/documents/chat-message.mjs
=> [#3652] Add config option to prevent damage aggregation in chat messages

module/enrichers.mjs
Adds a new `[[/concentration]]` enricher that taps into an updated `enrichSave` method to be able to handle concentration checks.
=> [#3039] Add enricher for concentration checks

packs/_source/spells/3rd-level/conjure-animals.json, packs/_source/spells/4th-level/conjure-minor-elementals.json, packs/_source/spells/4th-level/conjure-woodland-beings.json, packs/_source/spells/5th-level/conjure-elemental.json, packs/_source/spells/6th-level/conjure-fey.json, packs/_source/spells/7th-level/conjure-celestial.json
=> [#3830] Update SRD spells with CR-based summoning

lang/en.json, module/data/_module.mjs, module/data/activity/_module.mjs, module/data/activity/base-activity.mjs
Adds a data model representing a base activity with all of the information that will be shared between all activities.
=> [#461, #1964] Build base data model for activities

module/documents/actor/hit-dice.mjs
=> Add getters for smallest and largest available hit dice

module/documents/chat-message.mjs
A CONFIG option `DND5E.aggregateDamageDisplay ` was added in #3769 that supposedly prevents damage of the same type from being aggregated in the damage tooltip. While this CONFIG option does stop aggregation in the roll array, that roll array was simply aggregated a second time by the tooltip generation regardless of whether or not the CONFIG option was set to true/false. This meant that the CONFIG option didn't actually end up doing anything.
This fix changes around the breakdown of damage rolls that is used by the tooltip generation so that it accurately reflects the damage roll array. Instead of aggregating into a new object, it simply cherry picks the data it needs from the damage roll array into a new array that is then sent to the tooltip generation. This way, if the rolls in the …
=> [#3652] Fix aggregate damage CONFIG option

lang/en.json, less/dnd5e.less, less/v2/dark/items.less, less/v2/items.less, module/applications/item/item-sheet.mjs, module/applications/item/sheet-v2-mixin.mjs, module/data/item/equipment.mjs, module/data/item/spell.mjs, module/data/item/weapon.mjs, module/utils.mjs, templates/items/item-sheet-2.hbs, templates/items/parts/item-description2.hbs
=> Item sheets V2 Description tab

less/v2/items.less, module/applications/item/container-sheet-2.mjs, module/applications/item/item-sheet-2.mjs, module/applications/item/sheet-v2-mixin.mjs, templates/items/item-sheet-2.hbs
=> Item Sheet V2: Container Contents tab

module/applications/actor/character-sheet-2.mjs, module/applications/components/item-list-controls.mjs, module/applications/item/item-sheet-2.mjs, module/applications/item/sheet-v2-mixin.mjs, module/applications/mixins/sheet-v2-mixin.mjs, templates/items/item-sheet-2.hbs
=> Item Sheet V2: Effects tab

lang/en.json, less/v2/dark/items.less, less/v2/forms.less, less/v2/items.less, less/v2/sheets.less, module/applications/item/item-sheet-2.mjs, module/applications/item/sheet-v2-mixin.mjs, module/documents/item.mjs, module/utils.mjs, templates/items/item-sheet-2.hbs, templates/items/parts/item-activities.hbs
There's room for some supplementary information on these activity rows, so the design may change a bit, but for now I haven't thought much about what would go there.
=> Item Sheet V2: Activities tab

lang/en.json, module/data/advancement/spell-config.mjs, module/data/item/_module.mjs, module/data/item/class.mjs, module/data/item/fields/spellcasting-field.mjs, module/data/item/spell.mjs, module/data/item/subclass.mjs, packs/_source/classes/cleric.json, packs/_source/classes/druid.json, packs/_source/classes/paladin.json, packs/_source/classes/wizard.json, templates/advancement/parts/advancement-spell-config.hbs, templates/items/details/details-spell.hbs, templates/items/details/details-spellcasting.hbs
Updated version of the PR by @absymylyar (https://github.com/foundryvtt/dnd5e/pull/3416), switching to formulas for the calculation plus a few other tweaks.
Closes #1021
Closes #2978
=> [#1021, #2978] Automatically calculated spell preparation limits

dnd5e.mjs, less/v2/chat.less, module/documents/chat-message.mjs
Closes #3443 
Happy to make any requested changes.
=> [#3443] Holding shift as GM shows original delete icon for chat messages

lang/en.json, less/v2/forms.less, module/applications/journal/class-page-sheet.mjs, module/data/item/class.mjs, templates/items/class.hbs, templates/items/details/details-class.hbs, templates/journal/page-class-view.hbs
Adds primary ability to classes and displays in on the class journal page.
Closes #2212
Closes #3998
=> [#2212, #3998] Add primary ability to classes

lang/en.json, module/documents/actor/actor.mjs
=> [#4026, #4027] Cap concentration DC at 30, rename exotic languages

lang/en.json, less/dnd5e.less, less/v2/activities.less, less/v2/dark/activities.less, less/v2/forms.less, module/applications/activity/activity-sheet.mjs, module/applications/fields.mjs, module/utils.mjs, templates/activity/attack-identity.hbs, templates/activity/identity.hbs, templates/activity/parts/damage-damage.hbs, templates/activity/parts/damage-part.hbs, templates/activity/parts/enchant-enchantments.hbs, templates/activity/parts/enchant-restrictions.hbs, templates/activity/parts/heal-healing.hbs, templates/activity/parts/save-damage.hbs, templates/activity/parts/summon-changes.hbs, templates/activity/parts/summon-profiles.hbs, templates/activity/summon-identity.hbs, templates/activity/utility-effect.hbs, templates/activity/utility-identity.hbs, templates/items/details/details-consumable.hbs, templates/items/details/details-weapon.hbs, templates/shared/fields/field-damage.hbs
=> Activity Sheets: Remainder

module/config.mjs, templates/actors/character-sheet-2.hbs, templates/items/details/details-weapon.hbs
- Add range/reach inputs to other weapon types.
- Accommodate reach in favourites.
=> Reach tweaks

less/v2/character.less, module/applications/actor/character-sheet-2.mjs, module/data/item/class.mjs, module/data/item/spell.mjs, module/data/item/subclass.mjs, module/documents/actor/actor.mjs, templates/actors/tabs/creature-spells.hbs, templates/items/details/details-spellcasting.hbs
=> [#2978] Add spell preparation count to character sheet.

lang/en.json, module/documents/macro.mjs, module/enrichers.mjs
Allows the item enricher to include an activity ID or name that will be triggered if found on the item:
```
[[/item Bite activity=Paralyze]]
[[/item amUUCouL69OK1GZU activity=G8ng63Tjqy5W52OP]]
```
=> [#1964] Extend [[/item]] enricher to trigger activities

packs/_source/items/weapon/sickle-1.json, packs/_source/items/weapon/sickle-2.json, packs/_source/items/weapon/sickle-3.json, packs/_source/items/weapon/trident-1.json, packs/_source/items/weapon/trident-2.json, packs/_source/items/weapon/trident-3.json, packs/_source/items/weapon/trident-of-fish-command.json, packs/_source/items/weapon/vicious-sickle.json, packs/_source/items/weapon/vicious-trident.json, packs/_source/items/weapon/vicious-war-pick.json, packs/_source/items/weapon/war-pick-1.json, packs/_source/items/weapon/war-pick-2.json, packs/_source/items/weapon/war-pick-3.json
=> [#4108] New icons for magic sickles, tridents, & war picks

packs/_source/items/weapon/javelin-1.json, packs/_source/items/weapon/javelin-2.json, packs/_source/items/weapon/javelin-of-lightning.json, packs/_source/items/weapon/javelin.json, packs/_source/items/weapon/lance-1.json, packs/_source/items/weapon/lance-2.json, packs/_source/items/weapon/lance-3.json, packs/_source/items/weapon/pike-1.json, packs/_source/items/weapon/pike-2.json, packs/_source/items/weapon/pike-3.json, packs/_source/items/weapon/spear-1.json, packs/_source/items/weapon/spear-2.json, packs/_source/items/weapon/spear-3.json, packs/_source/items/weapon/vicious-javelin.json, packs/_source/items/weapon/vicious-lance.json, packs/_source/items/weapon/vicious-pike.json, packs/_source/items/weapon/vicious-spear.json
=> [#4110] New icons for magic lances, spears, javelins, pikes.

packs/_source/items/weapon/dwarven-thrower.json, packs/_source/items/weapon/hammer-of-thunderbolts.json, packs/_source/items/weapon/light-hammer-1.json, packs/_source/items/weapon/light-hammer-2.json, packs/_source/items/weapon/light-hammer-3.json, packs/_source/items/weapon/maul-1.json, packs/_source/items/weapon/maul-3.json, packs/_source/items/weapon/maul.json, packs/_source/items/weapon/vicious-light-hammer.json, packs/_source/items/weapon/vicious-maul.json, packs/_source/items/weapon/vicious-warhammer.json, packs/_source/items/weapon/warhammer-1.json, packs/_source/items/weapon/warhammer-2.json, packs/_source/items/weapon/warhammer-3.json
=> [#4112] New icons for magic hammers

packs/_source/items/weapon/club-1.json, packs/_source/items/weapon/club-2.json, packs/_source/items/weapon/club-3.json, packs/_source/items/weapon/club.json, packs/_source/items/weapon/glaive-1.json, packs/_source/items/weapon/glaive-2.json, packs/_source/items/weapon/glaive-3.json, packs/_source/items/weapon/greatclub-1.json, packs/_source/items/weapon/greatclub-2.json, packs/_source/items/weapon/greatclub-3.json, packs/_source/items/weapon/halberd-1.json, packs/_source/items/weapon/halberd-2.json, packs/_source/items/weapon/halberd-3.json, packs/_source/items/weapon/vicious-club.json, packs/_source/items/weapon/vicious-glaive.json, packs/_source/items/weapon/vicious-greatclub.json, packs/_source/items/weapon/vicious-halberd.json
=> [#4115] New icons for magic clubs, glaives, halberds.

module/applications/item/item-sheet.mjs, module/documents/active-effect.mjs, module/documents/item.mjs
=> [#4107] Fix applying rider effects on enchantment. Fix flagging rider effects.

packs/_source/items/ammunition/arrow-1.json, packs/_source/items/ammunition/arrow-2.json, packs/_source/items/ammunition/arrow-3.json, packs/_source/items/ammunition/arrow-of-slaying.json, packs/_source/items/ammunition/arrow.json, packs/_source/items/ammunition/blowgun-needle.json, packs/_source/items/ammunition/bolt-of-slaying.json, packs/_source/items/ammunition/crossbow-bolt-1.json, packs/_source/items/ammunition/crossbow-bolt-2.json, packs/_source/items/ammunition/crossbow-bolt-3.json, packs/_source/items/ammunition/crossbow-bolt.json, packs/_source/items/ammunition/sling-bullet-1.json, packs/_source/items/ammunition/sling-bullet-2.json, packs/_source/items/ammunition/sling-bullet-3.json, packs/_source/items/ammunition/sling-bullet-of-slaying.json, packs/_source/items/ammunition/sling-bullet.json, packs/_source/items/container/crossbow-bolt-case/_container.json, packs/_source/items/container/efficient-quiver/_container.json, packs/_source/items/container/quiver/_container.json
=> [#4129] New icons for magic ammo.

packs/_source/items/weapon/hand-crossbow-1.json, packs/_source/items/weapon/hand-crossbow-2.json, packs/_source/items/weapon/hand-crossbow-3.json, packs/_source/items/weapon/hand-crossbow.json, packs/_source/items/weapon/heavy-crossbow-1.json, packs/_source/items/weapon/heavy-crossbow-2.json, packs/_source/items/weapon/heavy-crossbow-3.json, packs/_source/items/weapon/light-crossbow-1.json, packs/_source/items/weapon/light-crossbow-2.json, packs/_source/items/weapon/light-crossbow-3.json, packs/_source/items/weapon/vicious-hand-crossbow.json, packs/_source/items/weapon/vicious-heavy-crossbow.json, packs/_source/items/weapon/vicious-light-crossbow.json
=> [#4131] New icons for magic crossbows

packs/_source/items/wand/wand-of-binding.json, packs/_source/items/wand/wand-of-enemy-detection.json, packs/_source/items/wand/wand-of-fear.json, packs/_source/items/wand/wand-of-fireballs.json, packs/_source/items/wand/wand-of-lightning-bolts.json, packs/_source/items/wand/wand-of-magic-detection.json, packs/_source/items/wand/wand-of-magic-missiles.json, packs/_source/items/wand/wand-of-paralysis.json, packs/_source/items/wand/wand-of-polymorph.json, packs/_source/items/wand/wand-of-secrets.json, packs/_source/items/wand/wand-of-the-war-mage-1.json, packs/_source/items/wand/wand-of-the-war-mage-2.json, packs/_source/items/wand/wand-of-the-war-mage-3.json, packs/_source/items/wand/wand-of-web.json, packs/_source/items/wand/wand-of-wonder.json, packs/_source/items/weapon/wand.json, packs/_source/items/weapon/yew-wand.json
=> New icons for wands

lang/en.json, less/v2/apps.less, less/v2/compendium-browser.less, less/v2/dark/apps.less, module/applications/_module.mjs, module/applications/compendium-browser-source-config.mjs, module/applications/compendium-browser.mjs, module/settings.mjs, templates/compendium/browser-header.hbs, templates/compendium/sources-packs.hbs, templates/compendium/sources-sidebar.hbs
=> Add application for configuring compendium browser source exclusions.

packs/_source/items/weapon/dancing-longsword.json, packs/_source/items/weapon/defender-longsword.json, packs/_source/items/weapon/dragon-slayer-longsword.json, packs/_source/items/weapon/flame-tongue-longsword.json, packs/_source/items/weapon/frost-brand-longsword.json, packs/_source/items/weapon/holy-avenger-longsword.json, packs/_source/items/weapon/longsword-1.json, packs/_source/items/weapon/longsword-2.json, packs/_source/items/weapon/longsword-3.json, packs/_source/items/weapon/longsword-of-life-stealing.json, packs/_source/items/weapon/longsword-of-sharpness.json, packs/_source/items/weapon/longsword-of-wounding.json, packs/_source/items/weapon/luck-blade-longsword.json, packs/_source/items/weapon/nine-lives-stealer-longsword.json, packs/_source/items/weapon/sun-blade.json, packs/_source/items/weapon/vicious-longsword.json
=> New icons for magic longswords

packs/_source/items/weapon/dancing-scimitar.json, packs/_source/items/weapon/defender-scimitar.json, packs/_source/items/weapon/dragon-slayer-scimitar.json, packs/_source/items/weapon/flame-tongue-scimitar.json, packs/_source/items/weapon/frost-brand-scimitar.json, packs/_source/items/weapon/giant-slayer-scimitar.json, packs/_source/items/weapon/holy-avenger-scimitar.json, packs/_source/items/weapon/luck-blade-scimitar.json, packs/_source/items/weapon/nine-lives-stealer-scimitar.json, packs/_source/items/weapon/scimitar-1.json, packs/_source/items/weapon/scimitar-2.json, packs/_source/items/weapon/scimitar-3.json, packs/_source/items/weapon/scimitar-of-life-stealing.json, packs/_source/items/weapon/scimitar-of-sharpness.json, packs/_source/items/weapon/scimitar-of-speed.json, packs/_source/items/weapon/scimitar-of-wounding.json, packs/_source/items/weapon/vicious-scimitar.json, packs/_source/items/weapon/vorpal-scimitar.json
=> New icons for magic scimitars

packs/_source/items/equipment/cape-of-the-mountebank.json, packs/_source/items/equipment/cloak-of-arachnida.json, packs/_source/items/equipment/cloak-of-displacement.json, packs/_source/items/equipment/cloak-of-elvenkind.json, packs/_source/items/equipment/cloak-of-the-bat.json, packs/_source/items/equipment/cloak-of-the-manta-ray.json, packs/_source/items/equipment/costume-clothes.json, packs/_source/items/equipment/fine-clothes.json, packs/_source/items/equipment/mantle-of-spell-resistance.json, packs/_source/items/equipment/robe-of-eyes.json, packs/_source/items/equipment/robe-of-scintillating-colors.json, packs/_source/items/equipment/robe-of-stars.json, packs/_source/items/equipment/robe-of-the-archmagi.json, packs/_source/items/equipment/robe-of-useful-items.json, packs/_source/items/equipment/robes.json, packs/_source/items/equipment/travelers-clothes.json, packs/_source/items/equipment/wings-of-flying.json
=> New icons for capes, cloaks, clothes, & robes

module/applications/journal/class-page-sheet.mjs
- Filter out any non-feature items when building tables and feature lists to avoid pollution from spells
- Prevent features that couldn't be found from displaying in tables
- Don't display subclass rows if scale value is the same as the previous row and everything else is equal
Closes #2125
=> [#2125] Only display features in table, simplify subclass tables

module/documents/actor/actor.mjs
It seems like it could be useful to have access to statuses in rolls.
=> Add `statuses` to `Actor#getRollData`

module/documents/actor/actor.mjs
=> append item rollData when recovering during rest

packs/_source/tables/grey-bag-of-tricks.json
=> Fix grey-bag-of-tricks.json icon

packs/_source/items/container/alms-box/_container.json, packs/_source/items/equipment-packs/burglars-pack/_container.json, packs/_source/items/equipment-packs/burglars-pack/ball-bearings.json, packs/_source/items/equipment-packs/diplomats-pack/_container.json, packs/_source/items/equipment-packs/diplomats-pack/fine-clothes.json, packs/_source/items/equipment-packs/diplomats-pack/ink-bottle.json, packs/_source/items/equipment-packs/diplomats-pack/map-case/_container.json, packs/_source/items/equipment-packs/diplomats-pack/scroll-case/_container.json, packs/_source/items/equipment-packs/dungeoneers-pack/_container.json, packs/_source/items/equipment-packs/entertainers-pack/costume-clothes.json, packs/_source/items/equipment-packs/priests-pack/_container.json, packs/_source/items/equipment-packs/priests-pack/alms-box/_container.json, packs/_source/items/equipment-packs/priests-pack/blanket.json, packs/_source/items/equipment-packs/scholars-pack/_container.json, packs/_source/items/equipment-packs/scholars-pack/book-of-lore.json, packs/_source/items/equipment-packs/scholars-pack/ink-bottle.json
=> Update icons of Equipment Packs

packs/_source/items/equipment/bracers-of-archery.json, packs/_source/items/equipment/bracers-of-defense.json, packs/_source/items/equipment/eyes-of-charming.json, packs/_source/items/equipment/eyes-of-minute-seeing.json, packs/_source/items/equipment/eyes-of-the-eagle.json, packs/_source/items/equipment/gauntlets-of-ogre-power.json, packs/_source/items/equipment/gloves-of-missile-snaring.json, packs/_source/items/equipment/gloves-of-swimming-and-climbing.json, packs/_source/items/equipment/goggles-of-night.json
=> New icons for hand and eyewear

less/v2/apps.less, less/v2/items.less
=> [#4235] Fix issue with header clipping

packs/_source/items/weapon/flame-tongue-greatsword.json, packs/_source/items/weapon/flame-tongue-longsword.json, packs/_source/items/weapon/flame-tongue-rapier.json, packs/_source/items/weapon/flame-tongue-scimitar.json, packs/_source/items/weapon/flame-tongue-shortsword.json
=> [#2902] Flame Tongue swords

packs/_source/items/trinket/hempen-rope-50-ft.json, packs/_source/items/trinket/silk-rope-50-ft.json
=> [#4342, #4343] Update hempen and silk ropes

packs/_source/races/orc/orc-features/savage-attacks.json
=> Savage Attacks AE

module/enrichers.mjs
=> [#4490] Toggle status effect on actors

module/documents/item.mjs
=> [#4287] Spell Scroll Icon

module/applications/activity/activity-usage-dialog.mjs
=> [#4292] Set default spell slot if the default option is disabled

less/v2/apps.less, less/v2/dark/apps.less, module/applications/actor/config/damages-config.mjs, templates/apps/parts/traits-list.hbs
=> Add icons to DamagesConfig.

dnd5e.mjs
In recompense, I have removed a different check.
=> Register `TokenConfig` subclass in V12 only

module/data/advancement/spell-config.mjs
When a new activity is added to support free casts through item grants, this now adds them using a Forward activity rather than fully duplicating the original activity.
=> [#4031] Adjust Grant/Choose Items advancement to use Forward

lang/en.json, module/applications/_module.mjs, module/applications/activity/order-usage-dialog.mjs, module/applications/actor/character-sheet-2.mjs, module/applications/bastion.mjs, module/settings.mjs, templates/apps/bastion-config.hbs
=> Bastion configuration settings

dnd5e.mjs, lang/en.json, less/v2/activities.less, less/v2/apps.less, module/applications/activity/order-usage-dialog.mjs, module/applications/bastion.mjs, module/documents/_module.mjs, module/documents/activity/order.mjs, module/documents/actor/bastion.mjs, module/documents/chat-message.mjs, module/settings.mjs, templates/apps/bastion-config.hbs, templates/chat/bastion-turn-summary.hbs, templates/chat/order-activity-card.hbs
=> Bastion turn automation

packs/_source/monsters/dragon/adult-green-dragon.json
=> [#4634] Fix Wing Attack damage of Adult Green Dragon

module/documents/actor/actor.mjs
- Actually merge the Objects
Closes #4716
=> #rollSkillTool() doesn't merge the message Object properly

lang/en.json, module/applications/actor/config/hit-dice-config.mjs, module/data/activity/fields/consumption-targets-field.mjs, module/data/actor/character.mjs, module/data/actor/templates/creature.mjs, module/data/item/class.mjs, module/documents/actor/actor.mjs, module/documents/actor/hit-dice.mjs, module/documents/advancement/hit-points.mjs, templates/items/class.hbs, templates/items/details/details-class.hbs, templates/journal/parts/journal-modern-traits.hbs
Due to the order of things being prepared, this means the HitDice class has to resort to getters. Not an issue, in fact a small performance improvement to only calculate the max or value once when needed.
Closes #2197.
=> Move hit dice data, add "additional" property

lang/en.json, module/documents/activity/attack.mjs, module/enrichers.mjs
Adds a new attack enricher that can be used to roll an attack using a fixed formula:
```
[[/attack +5]]
[[/attack formula=5]]
```
=> [#3355] Add attack enricher

wiki/Active-Effect-Guide.md
Some minor fixes. Closes #4811.
=> Minor wiki updates

module/applications/activity/activity-choice-dialog.mjs, module/applications/compendium-browser.mjs
=> Fixed missing this annotations in appv2 actions

.github/workflows/release.yml, foundryvtt.json
- Allows for the same build script to be used for both systems and modules, premium or not
- Automatically determines the contents of the ZIP archive using the package manifest and the optional `includes` option in the configuration file
=> Update build script with more automation & flexibility

module/enrichers.mjs
Allows for providing an activity ID to specify a specific activity or leaving them blank to automatically find the first check or save activity on the item.
```
[[/check]]
[[/check activity=RLQlsLo5InKHZadn]]
[[/save]]
[[/save activity=RLQlsLo5InKHZadn]]
```
Closes #4862
=> [#4862] Add activity-linked check & save enrichers

wiki/Enrichers.md
- Adds examples to the enricher types
- Adds table of options for each enricher
- Adds potential issues that might cause an enricher to not enrich
- Splits Save Enrichers into their own section
=> Add examples & option tables for system enrichers

wiki/Enrichers.md
- Add the attack enricher
- Multiple proficiencies in check enricher
- Multiple damage types & formulas in damage enricher
- Mulitple abilities in save enricher
- Activity-linked check, damage, and save enrichers
- Activity lookup
=> Update enricher documentation to match changes in 4.2

module/applications/actor/_module.mjs
=> [#5053] Adds DeathConfig to module\applications\actor\_module.mjs

wiki/Roll-Formulas.md
Adding on to  #5104 
Don't think I missed any of the changes, only added `attributes.spell.attack`.
=> Update Roll Formulas for 4.3

module/data/activity/attack-data.mjs, module/data/activity/base-activity.mjs, module/data/item/weapon.mjs
=> [#5194] Fix melee and natural weapons missing reach tags.

module/parse-uuid.mjs
=> [#5215] Fix failed data preparation when sourceId compendium is no longer available.

module/data/activity/heal-data.mjs
Reinstate scaling for HealActivity.
Closes #5272
=> HealActivity scaling fix

module/canvas/token.mjs
Scale HP bar according to `canvas.dimensions.uiScale`.
https://github.com/foundryvtt/foundry-vtt/pull/3371
=> Update `Token#_drawHPBar` for V13

module/applications/components/effects.mjs, module/applications/components/inventory.mjs, module/applications/components/item-list-controls.mjs
Fixes `EffectsElement`, `InventoryElement`, and `ItemListControlsElement` to work in old and new applications.
Closes #5348
=> [#5348] Fix custom elements in `ApplicationV2`

dnd5e.mjs, module/applications/item/item-compendium.mjs, module/documents/active-effect.mjs, module/documents/actor/actor.mjs, module/documents/item.mjs
Closes #5335
Also covers the primary party not being marked as such in the actor directory.
=> Fix onTokenHUDRender and onRenderActorDirectory for V13

lang/en.json
=> [#5087] Fix i18n for Turn End & Turn Start abbreviations

dnd5e.mjs, module/documents/actor/actor.mjs, module/migration.mjs, module/module-art.mjs, system.json
=> Revert "[#5332] Migrate to core's `CompendiumArt` system"

module/documents/actor/actor.mjs
=> Pass number of concentration effects to statuses.concentrating

module/applications/actor/vehicle-sheet.mjs, module/applications/components/inventory.mjs, templates/actors/parts/actor-features.hbs, templates/actors/parts/actor-spellbook.hbs, templates/shared/inventory.hbs
- Add back fallback for fetching V1 applications
- Add back old expanding code when V1 sheet is detected
- Add special handling for toggling crewed state on vehicles
Closes #5500
=> [#5500] Fix inventory element for legacy sheets

less/v1/journal.less
=> [#5527] Move width/height styling for ToC app

module/applications/actor/sheet-v2-mixin.mjs, module/data/actor/templates/creature.mjs
Let me know if you can think of any issues this might cause.
=> Fix bonus field labels in special traits tab in v13.

module/migration.mjs
Recent changes to migration that make use of `recrusive: false` to migrate item and active effect types have resulted in items being deleted from actors. This modifies `migrateActorData` to ensure that the full data for all items is present on the actors if any item has the `persistSourceMigration` flag set to prevent this.
=> Fix errors with certain migrations removing items from actors

module/applications/actor/api/base-actor-sheet.mjs, module/documents/actor/actor.mjs
=> [#5577] Fixed actor sheet tool rolls

module/applications/components/inventory.mjs
=> [#5601] Change item to entry in _onRollRecharge

module/data/advancement/spell-config.mjs
- Closes #4727 
- Closes #5692
=> [#4727] [#5692] Set spell source class appropriately during Advancement.

wiki/Modifying-Your-Game-with-Scripts.md
=> [#2834] Add guidance for modify SVGs to work with system

wiki/Modifying-Your-Game-with-Scripts.md
Correcting "activityActivationType" to "activityActivationTypes" within the wikipage.
=> Update Modifying-Your-Game-with-Scripts wikiPage to correct incorrect Variable

module/data/settings/transformation-setting.mjs
=> [#5888] Fix Transformation Setting otherSettings name prefix

module/data/activity/attack-data.mjs, module/data/item/weapon.mjs
=> [#2735] Have natural weapons use the highest of str or dex by default.

module/documents/actor/actor.mjs
=> [#5429] Use transformation source to-hit bonus when transformed.

module/documents/actor/actor.mjs
=> [#5419] When keep HP or spells transformation options are set, retain these values when reverting form.

module/canvas/token.mjs
Somehow this bit of logic got dropped in the original PR.
=> Stop movement prior to a blocking token, rather than fully preventing the movement

module/applications/advancement/item-choice-flow.mjs
=> Item Choice Flow: Any Available Level option is not working correctly

module/applications/advancement/item-choice-flow.mjs, module/data/item/feat.mjs
- Closes #6004 
- Closes #6006 
- Closes #6007
=> [#6004] [#6006] [#6007] Improve prerequisite management in ItemChoiceFlow.

module/documents/actor/actor.mjs
=> [#6080] Allow `exhaustionDelta` in short rest

system.json
=> Add missing file path fields to manifest
