foundryvtt/dnd5e

README.md
Seemed to have been left over from the move from git lab. I've just copy and pasted the URL from https://foundryvtt.com/packages/dnd5e (which worked better than either the thing I replaced or the one listed in the application)
Closes #1615
=> [#1615] Update readme install location

.github/workflows/release.yml
This action setup has full parity with the previous gitlab ci configuration:
- Verifies that the `system.json` `version` and `download` fields are correct for the tag that triggers the build.
- Installs `npm` deps, using node 16
- Runs `npm run build` to build everything at once
- Zips up the same file list as is present in `gitlab-ci.yml`
- Attaches that zip file and the `system.json` file to a release which is generated for this tag
Simplifications from the Gitlab CI:
- We no longer need a hacky `/latest` workaround using a "generic package", as github provides a permalink to `foundryvtt/dnd5e/releases/latest` out of the box.
I tested this in my own fork:
- Failure because of `download` url: https://github.com/ElfFriend-DnD/dnd5e/actions/runs/2522296308
- Failure because of `version` …
=> ci: add Github Actions to replace Gitlab-CI

dnd5e.mjs, main.mjs, module/applications/actor/base-sheet.mjs, module/applications/item-sheet.mjs, module/applications/select-items-prompt.mjs, module/config.mjs, module/documents/actor/actor.mjs
- Update compatibility warnings that include version 1.7–1.9 to reflect new version numbers of 2.0–2.2
- Add `DnD5e` before compatibility warning version numbers to indicate that they are DnD issues
- Replace some more `console.log` entries with core helper
=> Fix version numbers in compatibility warnings to match new versions

module/documents/actor/actor.mjs, templates/apps/ability-config.html
- Fix issue with custom abilities still appearing on character sheet after they are disabled
- Fix issue with ability data not being persisted to the database when added, resulting in properties like `"bonuses"` not existing for custom abilities unless the user explicitly sets them in the configuration window
- Fix issue with ability proficiency value being set to a string rather than a number via the configuration interface
=> Fix various issues with custom abilities caused by V10 transition

module/advancement/advancement.mjs, module/advancement/types/item-grant.mjs, module/documents/item.mjs, module/utils.mjs
- Fix issue with item grant choices not appearing in advancement list or advancement config due to `TextEditor._createContentLink` returning node rather than raw HTML
- Fix issue with advancement values not being unset when leveling down due to `mergeObject` no long performing deletions by default
- Fix issue with granted item ID not being stored in advancement data
=> Fix several bugs in item grant advancement

dnd5e.mjs, module/applications/actor/base-sheet.mjs, module/applications/item/item-sheet.mjs, module/documents/_module.mjs, module/documents/macro.mjs, module/migration.mjs
- Adjust macro export to match filename (`dnd5e.documents.macro` rather than `dnd5e.documents.macros`)
- Add compatibility exports for `game.dnd5e.rollItemMacro` & `game.dnd5e.macros`
- Add migration to convert existing macros from using the old paths to the new paths
- Fix issue with migrations being unable to be created by dropping on macro bar
- Fix issue with token image migrations pointing to old `img` rather than `texture.src`
- Fix a few instances where `logComptabilityWarning` were provided with `from` rather than `since`
=> Fix v10 macro & token migration issues

dnd5e.css, less/apps.less, module/applications/actor/base-sheet.mjs, module/applications/actor/character-sheet.mjs, module/applications/actor/npc-sheet.mjs, module/applications/actor/vehicle-sheet.mjs, module/applications/item/item-sheet.mjs, templates/items/parts/item-activation.html
- Refactor the `getData` methods for all of the sheets to use a merge-strategy rather than individually setting each property on context
- Fix bug with `multiclassLabel` in character sheet context caused by the new subclass type
- Remove more unwanted `h3` underlines that was missed in the last PR
=> Refactor actor & item sheet getData methods

dnd5e.css, less/items.less, module/applications/proficiency-selector.mjs, utils/javascript.mjs
- Fix a bug preventing `ProficiencySelector` from showing selected items
- Fix `data` warning in `ProficiencySelector`
- Fix issue with compiled source map pointing to wrong filename
- Add small black outline to improve contrast for warning icon in advancement list
Resolves #1667
=> [#1667] Fix bug in `ProficiencySelector` and accessibility update

module/documents/item.mjs
Add hooks to the specific item rolling methods not covered by #1662.
- `dnd5e.preRollAttack`, `dnd5e.rollAttack`
- `dnd5e.preRollDamage`, `dnd5e.rollDamage`
- `dnd5e.preRollFormula`, `dnd5e.rollFormula`
- `dnd5e.preRollRecharge`, `dnd5e.rollRecharge`: Modifies how roll recharge is performed so that the formula and target value are customizable
- `dnd5e.preRollToolCheck`, `dnd5e.rollToolCheck`
=> [#1002] Add hooks to `Item5e` rolling methods

module/applications/actor/base-sheet.mjs, module/canvas/ability-template.mjs, module/documents/item.mjs, module/documents/macro.mjs, templates/apps/ability-use.hbs
Adds a number of hooks to the item usage process to allow modules to better customize that workflow without having to override or wrap system methods:
- `dnd5e.preUseItem`: Called before the item is configured, allows changing configuration data, controlling whether the dialog should be displayed, and upcasting spells even if the dialog isn't shown
- `dnd5e.preItemUsageConsumption`: Called before usage updates are calculated
- `dnd5e.itemUsageConsumption`: Called after resource consumption is calculated to allow any modifications before those changes are applied to the actor or other items
- `dnd5e.preDisplayCard`: Called before the chat card is created with the chat data that will be used to display the card to allow for any changes before the creation occurs
- `dnd5e.displayCard`: …
=> [#1002, #1543, #1677] Add hooks to `Item5e#roll` & `Item5e#displayCard` to allow modules to enhance that workflow

module/documents/item.mjs
If the user has specified these directly, then we should not clobber the existing values when creating the item. This matches the check already found in e.g. `_onCreateOwnedTool`
Closes #1607.
=> [#1607] avoid setting NPC weapon proficiency/equipped if already set

dnd5e.mjs
Closes #1470
This allows world distributors to set a manifest flag to let the dnd5e system know that this world has already been migrated to a certain version. Normally, the `settings.db` serves this purpose, but sharing that is often undesirable (e.g. in a git repo) since it may contain sensitive info such as API keys for certain modules.
For example, you may find this in a world's manifest file to indicate that the world has been migrated to v1.6.3 of dnd5e:
```json
"flags": {
"dnd5e": {
"version": "1.6.3"
}
}
```
=> [#1470] Allow migration version to be set via world manifest flag

module/dice/damage-roll.mjs
Attempting to fix the issue with rolling critical damage when a parenthetical or math expression is used:
1. `(@details.level)d6` ==> `5d6`
2. `floor(@details.level / 2)d6` ==> `2d6`
It also evaluates properly if a deterministic formula is used for the dice type:
4. `1d(4+floor((@classes.monk.levels+1)/6)*2)` ==> `1d6`
5. `1d(@prof)rr=1` ==> `1d3rr=1`
It does not attempt to simplify things if dice are used on either side of the expression:
6. `(1d4)d6` ==> Nope
7. `1d(2 * 1d10)` ==> Nope
=> [#1140] Fix rolling criticals when number of dice is a formula

templates/items/tool.hbs
[possible solution to #1532]
This PR adds the tool's type [from among Artisan's, Musical Instrument, or Gaming Set] to the tool sheet's header.
=> [#1532] Displaying toolType in tool sheet header

dnd5e.mjs, module/documents/macro.mjs, templates/apps/ability-config.hbs, templates/apps/actor-armor.hbs, templates/apps/actor-flags.hbs, templates/apps/actor-type.hbs, templates/apps/hit-dice-config.hbs, templates/apps/movement-config.hbs, templates/apps/senses-config.hbs, templates/apps/skill-config.hbs, templates/apps/trait-selector.hbs
- Remove `name` attribute from various submit buttons resulting in unwanted form data (see https://github.com/foundryvtt/foundryvtt/issues/7938, but it seems good to clean up on our side also)
- Fix async bug with creating macros for items and active effects using drag-and-drop
=> Resolve bugs introduced by 10.279

module/migration.mjs
- Renames `_migrateItemIcon` -> `_migrateDocumentIcon` (it was already being used for many different documents)
- Added the ability to provide a `field` as part of its `migrationData`. This allows us to re-use the same function for ActiveEffect document `icon`, while preserving the default of `img` for the other document types.
- Added `_migrateDocumentIcon` to `migrateEffectData`
I will create a followup PR which migrates the effect icons in our compendia as they are currently broken links.
=> Update migration scripts to migrate effect icons

module/applications/item/item-sheet.mjs
Resolves #1741
The output of `_getItemConsumptionTargets` is an object with keys that look like paths to user data:
```js
{
'resources.primary.value': 'resources.primary.value'
// etc
}
```
When `mergeObject` encounters such a thing, it expands the path into an object.
```js
{
resources: { primary: { value: 'resources.primary.value' } }
}
```
Instead of using `mergeObject` to apply abilityConsumptionTargets, mutate `context` directly, as we did pre-v10-refactor.
=> [#1741] Fix ability consumption display in item sheets

module/documents/item.mjs, templates/items/equipment.hbs
Resolves #1743 
The `stealth` field of an equipment item document should be a boolean, but the input has a `value="1"` attribute, causing it to be saved incorrectly when the item is edited.
This in turn causes a problem when attempting to get `_equipmentChatData`, since `value` isn't necessary to check the boolean toggle.
=> [#1743] Fix stealth input having a value

lang/en.json, module/config.mjs
The newly-released Spelljammer: Adventures in Space contains a new "tool" vehicle proficiency type, for space vehicles.
E.x.: "Wildspacer" background:
> **Tool Proficiencies:** Navigator’s tools, vehicles (space)
=> Add support for "Space Vehicle" tool proficiencies

packs/src/monsters/celestial/couatl.json, packs/src/monsters/fey/dryad.json, packs/src/monsters/humanoid/acolyte.json, packs/src/monsters/humanoid/archmage.json, packs/src/monsters/humanoid/druid.json, packs/src/monsters/humanoid/mage.json, packs/src/monsters/monstrosity/gynosphinx.json, packs/src/monsters/undead/lich.json
Runs the migration from #1739 and only keeps the `icon` changes. These icons currently are broken references as the images were removed in 2.0.0-alpha3
=> Migrate old effect icons in compendium data

dnd5e.css, less/actors.less, module/applications/actor/base-sheet.mjs, module/applications/actor/skill-config.mjs, module/config.mjs, module/documents/actor/actor.mjs, template.json, templates/actors/character-sheet.hbs, templates/actors/npc-sheet.hbs, templates/apps/skill-config.hbs
Similar to the changes made in !443, this adds the ability for modules to easily introduce new skills simply by modifying `CONFIG.DND5E.skills`. This involves three major changes:
1. `DND5E.skills` has been modified to contain the default ability associated with this skill:
```javascript
DND5E.skills = {
acr: { label: "DND5E.SkillAcr", ability: "dex" },
ani: { label: "DND5E.SkillAni", ability: "wis" },
arc: { label: "DND5E.SkillArc", ability: "int" },
ath: { label: "DND5E.SkillAth", ability: "str" },
…
};
```
A `patchConfig` method has been added that allows any sheets or modules that are expecting the old format to continue functioning without the dreaded `"[object Object]"` showing up everywhere.
2. Introduction of `Actor5e#_prepareBaseSkills` to ensure the proper skills are contained …
=> [#1314, #1395] Allow skills to be customized by modules

module/documents/item.mjs
`ammo.data` -> `ammo.system` to remove a compatibility warning that occurs while rolling attacks for weapons with ammo
=> Remove ammo.data reference

module/documents/actor/actor.mjs, module/documents/item.mjs
- Ensure `dnd5e.useItem` hook is called even if the template creation is canceled (resolves #1748)
- Pass created measured template into hook (resolves #1749)
- Clean up various issues with hook documentation
=> [#1748, #1749] Adjust `dnd5e.useItem` hook & clean up hook documentation

lang/en.json, module/documents/actor/actor.mjs, module/documents/chat-message.mjs
Also adds an `applyTempHp` function to `Actor5e`. I could have just done that inside the chat function, but I figured it could be useful for macros and module developers to have the function.
=> [#1610] Apply temp HP from context menu on dice rolls

CONTRIBUTING.md, package.json
Looks like the gulp target changed, but the package.json and contribution guidelines weren't updated.
=> Fix CSS build target

module/dice/d20-roll.mjs
The `D20Roll` class will no longer throw an error if it isn't provided a valid D20 formula. Instead it will now just check validity at certain points before performing D20-specific customization.
=> [#1779] Fix issue with d20 rolls failing when they include min() or max()

module/applications/item/item-sheet.mjs, module/documents/item.mjs
Ensures you cannot use the new Duplicate Advancement method to create invalid configurations, such as two Hit Points Advancements on a single class.
=> [#1777] Check to ensure advancement can be created on item before duplication

lang/en.json, module/advancement/advancement-config.mjs, module/advancement/advancement.mjs, module/advancement/types/item-grant.mjs, module/utils.mjs, templates/advancement/item-grant-config.hbs, templates/advancement/parts/advancement-spell-config.hbs
- Add ability to override spellcasting ability, preparation mode, and max uses for spells added using item grant advancement (resolves #1626)
- Prevent `class`, `subclass`, or `background` items from being added using item grant to avoid issues caused by the use of the advancement system in a way that isn't yet supported (existing advancements that do this won't break, but new ones can't be created through the interface) (resolves #1689)
- Localize delete title that was missed (resolves #1620)
- Move drag & drop code into `AdvancementConfig` to prepare for sharing with `ItemChoiceAdvancement`
=> [#1620, #1626, #1689] Add spell config & type restriction to ItemGrant advancement

module/documents/actor/actor.mjs
This fixes the issue with rolling hit dice with a negative con modifier potentially subtracting hit points.
It also reworks `rollHitDie` to use the base `Roll` rather than `DamageRoll`, which avoids some formatting weirdness from the formula simplification present in `DamageRoll` that is not necessary for this purpose. This is a breaking change because it removes the ability to show a roll configuration dialog for hit die rolls (disabled by default, but possible before by passing `{dialog: true}` to the `rollHitDie` method). It also alters the config data passes to the `dnd5e.preRollHitDie` hook, potentially causing issues with people who have implemented that new hook already.
That said, I think it is better for hit die to be rolled as vanilla `Roll` rather than `DamageRoll`.
=> [#1769] Fix hit dice subtracting health with negative con mod, rework rollHitDie to use base Roll rather than DamageRoll

module/applications/actor/skill-config.mjs, module/applications/item/item-sheet.mjs, module/documents/item.mjs
- Fix bug with Global Skill Check Bonus not appearing in Skill Config dialog (resolves #1776)
- Fix bug with `prepareFinalAttributes` not being called on upcast spells (resolves #1810)
- Fix bug when invalid identifier is set on class or subclass sheet (resolves #1811)
=> [#1776, #1810, #1811] Fix various bugs

module/applications/item/item-sheet.mjs
This change introduces drag and drop handlers for the Item Sheet to allow Effects to be dragged and dropped between items.
This also allows effects to be drag and dropped from an item onto an actor to emulate applying the effect.
- Having configured a "Poisoned Dagger" with a "Poisioned" Effect, I would like to be able to quickly copy that effect to a "Poisioned Longsword".
- Said items would not need to transfer their effect to their parent actor in order for the GM to use them on enemies.
- An item which replicates the effects of a spell that has active effects configured can quickly clone the effect of that spell.
Copies what core does for dropping active effects on Actor Sheets, with one change:
- Sets the `origin` of the created effect to be the `uuid` of the new parent item.
I've …
=> Allow drag and drop of effects on items

module/applications/actor/base-sheet.mjs, module/documents/item.mjs
The `event` from `ActorSheet5e#_onItemUse` can contain useful information for modules listening to the `Item5e#use` hooks. This PR changes the `ItemUseOptions` to provide that `event` as well as the existing options, and ensures that this event is passed through to the use method from actor sheet usage.
A module such as [Faster Rolling By Default](https://github.com/ElfFriend-DnD/foundryvtt-faster-rolling-by-default-5e) can make use of the PointerEvent which triggered the item usage. Instead of swallowing it during `_onItemUse`, we can simply put it on `options` even though we do not use it ourself.
Additionally, other modules which offer ways to `use` items can adopt this pattern to improve intercompatibility.
=> Provide an event option to `item#use` from character sheet usage

module/dice/dice.mjs, module/documents/item.mjs
1. Centralize `fastForward` and `critical` detection within the `dice.mjs` helper functions, rather than also have some event key detection within `rollDamage` and similar methods.
- `_determineCriticalMode` and `_determineAdvantageMode` should be the only methods concerned with determining these roll modifiers to make it easier to refactor those methods later (e.g. in #1591)
2. Respect when `damageRoll` or `d20Roll` is invoked with `fastForward` explicitly set to `false`, showing the roll config dialog as normal.
3. Maintain the current API call signatures and behaviors, except in the case where `fastForward` is explicitly set to false.
> It is not possible to explicitly override a roll config to be `fastForward: false` if the config also has an `event` which would normally fast-forward …
=> Centralize fastForward detection for roll configs, allow explicit false

lang/en.json, module/advancement/types/scale-value.mjs, templates/advancement/scale-value-config.hbs
Added a simple icon to copy the whole scalar variable.
~~There is currently no indication that the info is copied to the clipboard, this could be fixed using a notification. Should this also be added?~~
closes #1506
=> [#1506] Add a copy button next to Scalar variable name 

module/applications/actor/base-sheet.mjs
Changes deletion to be a delete dialog instead.
- While testing with classes and subclasses, there is no double-up on confirmation dialogs unless you choose to not remove the items granted.
Closes #1629.
=> [#1629] Adds confirmation prompt to item deletion.

module/documents/actor/actor.mjs, module/documents/item.mjs
Merges default and provided `parts` array in the following methods:
- `Actor#rollAbilityTest`, `rollAbilitySave`, `rollDeathSave`, `rollSkill`.
- `Item#rollAttack`, `rollDamage`, `rollToolCheck`.
Closes #1839.
=> [#1839] Provided `parts` array overriding default `parts` in various rolls.

lang/en.json, module/config.mjs, module/documents/actor/actor.mjs, module/documents/item.mjs, module/utils.mjs, templates/items/parts/item-spellcasting.hbs
- Refactors `_prepareSpellcasting` method to make the spellcasting preparation process clearer and remove special cases
- Adds `_computeLeveledProgression` & `_computePactProgression` methods for build progression object from classes
- Adds `dnd5e.computeLeveledProgression` & `dnd5e.computePactProgression` hooks to allow for overriding the default behavior
- Adds `_prepareLeveledSlots` & `_preparePactSlots` and related hooks to allow for customizing slot creation behavior
This also introduces a `CONFIG.DND5E.spellcastingTypes` object that will eventually replace `spellProgression`. It defines two top-level types (`leveled` and `pact`) with the option for new additions by modules. Individual progressions (`full`, `half`, `third`, `artificer`) are defined underneath that top-level type. The …
=> [#1550, #1575] Refactor spellcasting preparation & add support for custom progressions

module/documents/item.mjs
Added ammunition's critical threshold to an item's `getCriticalThreshold`. Resolves #1901.
=> [#1901] Take ammo's critical threshold into account when calculating attack's threshold

module/documents/actor/actor.mjs
Fixed it so new characters have vision by default. Fixes #1882
=> [#1882] Fix new Character's token prototypes not having vision enabled by default

module/applications/item/item-sheet.mjs
This is an attempt to resolve #1853. By taking the largest of the *current* height and the default height, the rather annoying resizing of item sheets is somewhat relieved.
The automatic resizing was mainly an issue for the Description tab. There was no noticeable issue with the Effects tab unless an item had 10 or more effects. Also, this PR does not affect the Details tab at all.
=> [#1853] Relieve automatic resizing of Item Sheets when dragged

module/canvas/ability-template.mjs
This pull request modifies the `_onMovePlacement` and `_onConfirmPlacement` methods in the `AbilityTemplate` class to cause ability templates to only undergo pixel-level snapping (effectively no snapping) when placing ability templates onto a gridless scene. Snapping behavior on gridded scenes is unaffected.
Closes #1919
=> [#1919] Disable grid snapping when placing ability templates onto gridless scenes

module/documents/item.mjs
This pull request adds try-catch handling to the placeTemplate case of the `_onChatCardAction` method of the `Item5e` class. The absence of handling the rejection case of the promise from the `drawPreview` method of the created `AbilityTemplate` resulted in an uncaught error. The code within the placeTemplate case has also been refactored so as to resemble the code responsible for the creation of the initial `AbilityTemplate`.
Closes #1926
=> [#1926] Add try-catch handling to placeTemplate case of Item5e._onChatCardAction

module/documents/item.mjs
This is a one-liner to add a spell's level, as well as its item id, as `flags.dnd5e.use.spellLevel: <Number>`, and hopefully resolve #881.
I have put this in a separate PR to get some feedback on what the best flag would be; attack rolls use `flags.dnd5e.roll.type: "attack"` and damage rolls use `flags.dnd5e.roll.type: "damage"`, and this is not entirely in line with that, but using `flags.dnd5e.roll.type: "use"` didn't seem correct either.
=> [#881] Add spell level and item id to message flags when a spell is cast

module/documents/active-effect.mjs
This is an attempt to resolve #1293, changing the logic of determineSuppression given that uuids for linked and unlinked actors are different.
Updated: Using `fromUuidSync` and getting the item (the origin) immediately, and checking the equality of the effect's and item's (if any) parents, it should be a lot simpler.
=> [#1293] Suppress unavailable effects on synthetic actors

lang/en.json, module/data/_module.mjs, module/data/actor/group.mjs, module/data/item/_module.mjs, module/data/item/container.mjs, module/data/item/templates/action.mjs, module/data/item/templates/activated-effect.mjs, module/data/item/templates/item-description.mjs, module/data/item/templates/mountable.mjs, module/data/item/templates/physical-item.mjs, module/data/shared/_module.mjs, module/data/shared/currency.mjs
I named it `ContainerData` in expectation of an eventual renaming of the `backpack` item type to `container` (#1622). If that seems too confusing, I can rename it to `BackpackData` and we can change it later.
Also, I moved the currency data to its own template so it can eventually contain currency conversion methods so they are available on containers in addition to actors. More work can be done on that once #1829 is integrated.
=> [#1835] Create system data model for containers (aka backpacks)

module/documents/active-effect.mjs
A new PR to revert a change made in #1913, going back to not using `fromUuidSync` since it was found to be able to cause an error despite the try/catch.
=> Determine ActiveEffect suppression on all actor types

module/data/item/class.mjs
The advancement system sets classes to level 0 when first created and adjust them down to 0 during the deletion process, but the data model requiring `levels` to be positive causes this to thrown an error.
=> [#1983] Allow class to be level 0 to prevent advancement issue

module/config.mjs, module/documents/actor/actor.mjs
I'm the maintainer of World Currency 5e, a module that allows for currency customization. This pull request changes the currency conversion schema so that all currencies are defined in terms of GP (according to rules as written).
There are a few problems with the current schema:
- Module creators often hard code their own conversion logic because it's convoluted to use the system conversion numbers to convert a currency to/from GP.
- Completely omitting a currency like Electrum can't be achieved while keeping copper and silver.
- We can't have more than one currency that's worth more than GP.
- Defining new currencies in terms of each other isn't intuitive for most GMs.
I believe that the current schema was designed to make the "Currency Converter" logic straightforward. I have updated …
=> Use RAW GP as standard for currency conversions

templates/items/parts/item-activation.hbs
The grouping of item target type got removed when the "None" options was modified, this adds it back.
=> Add grouping back to item target type

module/documents/item.mjs
When an item (a spell) is cast at a level higher than its base, the attack roll does not take its current level into account. That's fine, unless you give the spell an AttackBonus of `@item.level`, in which the base level is always used. This PR changes it so the spellLevel from the chat message is used, identical to the way `rollDamage` is performed.
`Item5e#rollAttack` accepts `spellLevel` as an option now, same as `Item5e#rollDamage`.
I have tested it on attack rolls with
- leveled spells at a base level,
- leveled spells cast at a higher level,
- cantrips,
- weapons
=> Add spell level to attack rolls' options.

module/data/item/_module.mjs, module/data/item/consumable.mjs, module/data/item/container.mjs, module/data/item/equipment.mjs, module/data/item/templates/equippable-item.mjs, module/data/item/templates/physical-item.mjs, module/data/item/tool.mjs, module/data/item/weapon.mjs
Creates a new `AttunementEquippedTemplate` and moves those values out of `PhysicalItemTemplate` so they don't appear on loot, containers, or consumables.
=> [#1835] Move equipped and atunement to seperate template

dnd5e.mjs, lang/en.json, module/applications/actor/character-sheet.mjs, module/documents/actor/actor.mjs, module/documents/combat.mjs
Closes Issues:
- https://github.com/foundryvtt/dnd5e/issues/1632
- https://github.com/foundryvtt/dnd5e/issues/1069
- https://github.com/foundryvtt/dnd5e/issues/811 (wontfix)
Closes PRs:
- https://github.com/foundryvtt/dnd5e/pull/1894 (close without merging)
- https://github.com/foundryvtt/dnd5e/issues/1632 (close without merging)
- Ensure that initiative formula includes bonuses that are currently absent but should be included
- Enable a d20 roll dialog when rolling initiative off the character sheet to support circumstances where initiative can be conditionally rolled with a bonus or advantage/disadvantage
=> Support an initiative roll configuration Dialog for characters

module/documents/token.mjs
I have a branch for support for this as part of the core software also, but here we have overridden the (pending) core methods in order to support the custom `MappingField` that we have in the `dnd5e` system.
=> Add support for data models in TokenDocument.getTrackedAttributes.

module/documents/actor/actor.mjs, module/migration.mjs, module/module-art.mjs, utils/packs.mjs
This will prevent `refreshCompendium` from saving any enabled module art and changes our compendium build script to strip out `mystery-man.svg` from actor artwork & token artwork.
=> Prevent refreshCompendium from saving module art

.eslintrc.json, module/applications/actor/base-sheet.mjs, module/applications/actor/group-sheet.mjs, module/applications/actor/movement-config.mjs, module/applications/item/item-sheet.mjs, module/config.mjs, module/documents/item.mjs, module/module-art.mjs
Enables typescript mode in our JSDoc linter to prevent warnings when we use `@internal` and fix a variety of linting issues that have crept in recently.
=> Enable typescript mode for JSDoc comments, fix linting issues

module/applications/advancement/advancement-config.mjs, module/documents/advancement/advancement.mjs, module/documents/item.mjs
Fixes a bug introduced by the interaction between item data models and advancements. Replicates core's app updating behavior using `apps` to automatically re-render config applications when an advancement is updated.
=> [#1944] Fix bug with displaying updates in AdvancementConfig

dnd5e.mjs, module/applications/_module.mjs, module/applications/actor/character-sheet.mjs, module/applications/combat/_module.mjs, module/applications/combat/combat-tracker.mjs, module/dice/d20-roll.mjs, module/dice/dice.mjs, module/documents/actor/actor.mjs
Some adjustments for things I missed in my initial review that came up in later testing such as missing fast-forward rolls and the advantage button not being highlighted in the roll dialog when 'advantage on initiative' was checked. Also adds rudimentary support for `preRollInitiative` and `rollInitiative` hooks.
- Closes #1997
=> [#1997] Add support for preRollInitiative and rollInitiative hooks.

module/applications/actor/group-sheet.mjs, module/documents/actor/actor.mjs
Ideally other actors sheets and the group sheet would inherit from a new base type to remove the code duplication, but this will work well for the moment.
=> [#1949] Prevent dropping unwanted items onto group actor, fix getRollData & inventory bugs

templates/actors/character-sheet.hbs, templates/actors/group-sheet.hbs, templates/actors/npc-sheet.hbs, templates/actors/vehicle-sheet.hbs
This moves all cog icons out of any `h4` tags on all actor sheets to align with the rest that were already outside them.
=> Adjust cogs on actor sheets

module/documents/actor/actor.mjs
Ensures spellcasting is prepared for all spellcasting types regardless of whether the character has a class with that type. Also prevents spellcasting from being prepared on Group actors.
=> [#2053] Fix spellcasting not being prepared if no class exists with spellcasting type

module/applications/journal/class-sheet.mjs, module/documents/actor/actor.mjs, module/documents/actor/proficiency.mjs
Consolidates the code for calculating proficiency into the `Proficiency` class to avoid duplicating this formula. Should also allow for any modules that want to mess with how proficiency is calculated to be able to do it by replacing this single method.
=> Move proficiency calculating into Proficiency class

module/documents/actor/actor.mjs, module/documents/item.mjs
Moves the data preparation for scale value between when item data is prepared but before active effects are applied so they can be modified by active effects. This also allows them to be used as in input for an active effect if a player is using a module like DAE.
Resolves #1605
=> [#1605] Prepare scale values earlier to allow them to be modified by active effects

module/data/actor/character.mjs, module/data/actor/npc.mjs, module/data/actor/templates/attributes.mjs, module/data/actor/vehicle.mjs, module/data/advancement/scale-value.mjs, module/data/item/class.mjs, module/data/item/equipment.mjs, module/data/item/feat.mjs, module/data/item/spell.mjs, module/data/item/tool.mjs, module/data/item/weapon.mjs, module/documents/item.mjs, system.json
**Note**: I've removed the return statement in out overridden `migrateData` methods. The core JSDoc states that `migrateData` should return `source`, but `migrateDataSafe` just ignores that value. Do we think is will be necessary to add `return source;` to each of these methods or are we good as is?
=> [#2064] Fix system DataModel migrations causing issues with core migrations, up minimum core version

templates/actors/character-sheet.hbs, templates/actors/group-sheet.hbs, templates/actors/limited-sheet.hbs, templates/actors/npc-sheet.hbs, templates/actors/parts/active-effects.hbs, templates/actors/parts/actor-features.hbs, templates/actors/parts/actor-inventory.hbs, templates/actors/parts/actor-spellbook.hbs, templates/actors/parts/actor-traits.hbs, templates/actors/vehicle-sheet.hbs, templates/advancement/item-grant-config.hbs, templates/advancement/scale-value-config.hbs, templates/apps/actor-type.hbs, templates/apps/hit-dice-config.hbs, templates/apps/hit-points-config.hbs, templates/items/background.hbs, templates/items/backpack.hbs, templates/items/class.hbs, templates/items/consumable.hbs, templates/items/equipment.hbs, templates/items/feat.hbs, templates/items/loot.hbs, templates/items/parts/item-activation.hbs, templates/items/parts/item-advancement.hbs, templates/items/spell.hbs, templates/items/subclass.hbs, templates/items/tool.hbs, templates/items/weapon.hbs, templates/journal/page-class-edit.hbs
=> [#2018] Replace titles with tooltips on sheets

dnd5e.css, less/actors.less, less/apps.less, module/applications/actor/base-sheet.mjs, module/applications/property-attribution.mjs, templates/actors/character-sheet.hbs, templates/actors/npc-sheet.hbs, templates/apps/property-attribution.hbs
Makes the property attributions more consistent with other parts of the sheet and fixes the rendering issue that was preventing the expansion of attributions to other parts of the sheet.
Resolves #1564
=> [#1564] Convert property attribution to use tooltips

module/dice/damage-roll.mjs, module/dice/simplify-roll-formula.mjs
- Ensure situational bonus dice added are preprocessed to allow crits #2033
- Fix bug introduced by resolving un-numbered dice terms (aka `d4`) #2080 
- Fix repeated warnings from `simplifyRollFormula` when multiplication & division are used #2084
=> [#2033, #2080, #2084] Fix various issues with `ParentheticalTerms` in rolls

module/utils.mjs, templates/actors/parts/actor-features.hbs, templates/actors/parts/actor-inventory.hbs, templates/actors/parts/actor-spellbook.hbs
- Fix issue with crew & passenger sections not displaying on vehicle sheets by adding a new version of the `{{with}}` handlebars helper that can handle the context not being found #2054
=> [#2054] Fix crew & passengers sections not displaying on vehicle sheet

module/applications/actor/base-sheet.mjs, module/applications/actor/character-sheet.mjs, module/applications/actor/npc-sheet.mjs, module/applications/actor/vehicle-sheet.mjs, module/utils.mjs, templates/actors/parts/actor-features.hbs, templates/actors/parts/actor-inventory.hbs, templates/actors/parts/actor-spellbook.hbs, templates/items/parts/item-summary.hbs
Tracks which sections are expanded using the new `ActorSheet5e#_expanded` property.
Moves the actual HTML for the expanded sections into its own template so it can be easily rendered with the other templates.
Resolves #244
=> [#244] Preserve expanded state of items on actor sheets across re-render

module/applications/actor/ability-config.mjs, module/applications/actor/base-sheet.mjs, module/applications/actor/skill-config.mjs, templates/actors/character-sheet.hbs, templates/actors/npc-sheet.hbs
Split off some of the less major changes from #2087. This should fix a bug preventing the proficiency toggle from working with newly added custom skills, an issue with `SkillConfig` not having the right data for custom skills, and the ability score being lost when other sheet data is saved.
=> Fix issues with modifying custom skills

module/applications/actor/base-sheet.mjs, templates/actors/character-sheet.hbs, templates/actors/npc-sheet.hbs
Fixes a critical bug causing skills to lose their associated abilities if the ability abbreviations are localized.
Resolves #2108
=> [#2108] Fix issue with localized ability abbreviations causing issues with skills

dnd5e.mjs, module/applications/actor/ability-config.mjs, module/applications/actor/base-sheet.mjs, module/applications/property-attribution.mjs, module/config.mjs, module/dice/d20-roll.mjs, module/documents/actor/actor.mjs, module/documents/item.mjs
- Merge `DND5E.abilities` & `DND5E.abilityAbbreviations` into single object
- Add `type` to abilities to specify whether they are `"mental"` or `"physical"` and adjust polymorphing to make use of those types rather than hardcoded values (resolves #1848)
- Add a `defaults` object to those where different default values can be specified for different actor types and adjust `Actor5e#_prepareBaseAbilities` to make use of these defaults rather than hardcoding values (resolves #1846)
=> [#1846] Allow ability type & defaults to be defined in config

module/applications/item/item-sheet.mjs, module/data/item/class.mjs, module/data/item/consumable.mjs, module/data/item/equipment.mjs, module/data/item/feat.mjs, module/data/item/spell.mjs, module/data/item/templates/action.mjs, module/data/item/templates/activated-effect.mjs, module/data/item/templates/equippable-item.mjs, module/data/item/templates/item-description.mjs, module/data/item/templates/physical-item.mjs, module/data/item/tool.mjs, module/data/item/weapon.mjs, module/documents/item.mjs, templates/items/class.hbs, templates/items/equipment.hbs, templates/items/parts/item-action.hbs, templates/items/parts/item-activation.hbs, templates/items/weapon.hbs
Moves most of the getter logic from `Item5e` into the various system data models and splits up `abilityMod` and `criticalThreshold` so that each individual type can handle their own type-specific logic.
Adjust the logic of `hasDamage`, `hasSave`, and `isVersatile` to require that `actionType` be set.
Adds `isMountable`, `hasScalarDuration`, `hasScalarRange`, and `hasScalarTarget` getters.
This also refactors `ItemSheet5e` & templates to make more use of getters directly and reorders the getters in `Item5e` to be in alphabetical order.
=> [#2094] Move Item getters into system data models

module/data/actor/templates/common.mjs, module/data/actor/templates/creature.mjs
Fixes a bug preventing `migrateACData` and `migrateMovementData` from being called.
Resolves #2180
=> [#2180] Fix CommonTemplate#migrateData not being called

module/applications/actor/group-sheet.mjs, module/documents/actor/actor.mjs, module/documents/item.mjs
A few bugs that are annoying but easy to fix that should probably be solved sooner rather than waiting for `2.2.0`.
- Fix issue with items in group inventory repeatedly expanding
- Fix issue with spell scrolls not getting spell description
- Fix issue with `transformInto` ignoring `renderSheet` option for linked actors
Resolves #2132 
Resolves #2181 
Resolves #2205
=> [#2132, #2181, #2205] Fix few nagging bugs

module/data/fields.mjs
```javascript
actor.system.schema.getField("abilities");          // Returns abilities MappingField
actor.system.schema.getField("abilities.*");        // Returns ability's SchemaField ("*" can be any value)
actor.system.schema.getField("abilities.*.value");  // Returns value's NumberField
```
Resolves #2229
=> [#2229] Add support for getField requests to MappingField

module/applications/actor/vehicle-sheet.mjs, module/data/item/templates/activated-effect.mjs, module/utils.mjs, template.json, templates/actors/parts/actor-features.hbs, templates/actors/parts/actor-inventory.hbs
- Add `cover` to `ActivatedEffectTemplate` which was missed in initial data models
- Fix issue with deleting value from `qty` or `hp` resulting in data validation error
- Fix `threshold` and `cover` not displaying contents on vehicle sheet
=> [#2166] Fix bug with equipment details not displaying on vehicle sheet

dnd5e.css, less/actors.less, less/character.less, templates/actors/character-sheet.hbs, templates/actors/npc-sheet.hbs, templates/actors/vehicle-sheet.hbs
=> [#2162, #2185] Fix sheet layout issues with long background or class names

templates/actors/character-sheet.hbs
A fix for [this bug](https://github.com/foundryvtt/dnd5e/issues/2175) which was caused by a change [this PR](https://github.com/foundryvtt/dnd5e/pull/2019)
Closes #2175
=> Consult source of hp max for characters

lang/en.json, module/applications/actor/character-sheet.mjs, module/data/actor/templates/creature.mjs
Fixed a typo in the schema ("prof" to "prog") and fixed the SI unit to not be "kilogram seconds".
Closes #2150.
=> [#2150] Fix schema typo and kgs abbreviation

templates/items/parts/item-activation.hbs
A minor usability change that moves the location of the distance types in the range dropdown to the top just below "None".
Current:
Adjusted:
=> Move distance units in range dropdown to top

module/data/actor/templates/common.mjs, module/data/actor/templates/creature.mjs, module/data/fields.mjs, module/data/shared/currency.mjs, module/documents/actor/actor.mjs
The preparation for mapping fields that was initially performed in `_prepareBaseAbilities` and `_prepareBaseSkills` is now performed by the `MappingField` itself. This makes it easier to expand this logic to other places we use `MappingField` (such as with currencies to fix an issue with custom currencies) and allows the system to use a single initial value method rather than having two implementations.
Resolves #2161
=> [#2161] Move base ability & skill prep into MappingField

module/data/actor/templates/common.mjs
=> fix #2333: Cannot create NPC actors when sanity or honor are enabled

module/documents/actor/actor.mjs
Closes #2277.
Before and after, with an empty string init bonus:
=> Don't add init bonus if it is at all falsy

lang/en.json, module/config.mjs, module/data/actor/templates/common.mjs, module/documents/actor/actor.mjs, template.json, templates/apps/ability-config.hbs
Split the maximum ability score from #2158 for separate review.
Adds `max` to abilities that defaults to `20` to allow `AbilityScoreImprovementAdvancement` and other uses to cap an ability score.
- Currently doesn't prevent entering a value over the max on the character sheet
- This ends up also adding `max` to NPCs and vehicles where it isn't useful, should the data models be modified so it is only included on characters?
Resolves #1013
=> [#1013] Add max to ability scores

module/data/item/templates/action.mjs, module/documents/item.mjs, templates/items/parts/item-action.hbs
This introduces an additional option when selecting an item's ability modifier; ~~"flat"~~ "none", which will ignore ability modifiers, ~~proficiency bonus, and any bonuses to melee/ranged weapon/spell attacks~~.
This also adjusts the logic such that an 'equipment' type item is required to have proficient toggled on for proficiency bonus to be added, and removes `@mod` from created spell scrolls, which is not needed any longer (these are set to ~~`flat`~~ `none` if they have an attack).
Example using Circlet of Blasting:
Before (using an actor with a +2 PB and +2 INT):
After (using that same actor, with Proficient toggled off):
Resolves #2026.
Does something to #885.
=> [#885] [#2026] Add 'none' as an option when choosing the ability modifier

lang/en.json, module/documents/item.mjs
Added missing localization in the scroll description.
Added a hook (`dnd5e.createScrollFromSpell`) for those who want to tweak the scroll creation process further (the process cannot be cancelled).
Add concentration tag as a piece of descriptive text under the spell name (closes #1241), only for concentration spells.
=> Tweaks and fixes to the scroll creation process

dnd5e.css, lang/en.json, less/actors.less, module/applications/actor/base-sheet.mjs, templates/actors/parts/actor-inventory.hbs
This adds a smol attunement tracker on the character sheet under Inventory.
It is displayed in the same fashion as spell slot overrides, and should work with active effects overriding it (removing the edit icon).
[att.webm](https://github.com/foundryvtt/dnd5e/assets/50169243/3d8127f1-210d-4401-8bce-e57adb329324)
Closes #1309.
=> Attunement tracker on character sheet

module/documents/item.mjs
This adds a `preCreate` method for feature type items on npc sheets such that the items dropped or created are set to "Monster Feature" unless a feature type already exists on the item data.
Closes #2067.
=> Set feature items on NPCs as 'Monster Feature' by default

module/applications/advancement/ability-score-improvement-config.mjs, module/applications/advancement/ability-score-improvement-flow.mjs, module/config.mjs, module/documents/advancement/ability-score-improvement.mjs
This adds `improvement` to entries in `CONFIG.DND5E.abilities` which, when explicitly `false`, should entirely ignore the given ability for the purpose of Ability Score Improvement advancements.
Closes #2404
=> [#2404] Ignore honor and sanity for ability score improvements

lang/en.json, module/config.mjs, module/data/item/consumable.mjs, module/data/item/feat.mjs, module/data/item/weapon.mjs, module/documents/item.mjs
This re-implements the PB for attack rolls with feature-type items, which are treated as always proficient.
Additionally, the 'Tavern Brawler' feat is added in Special Traits. When checked, the actor is considered proficient with attack rolls of consumable items and weapons that are set as 'Improvised' (unless the item is set to 'not proficient').
Lastly, the 'Natural' weapon type is removed from the CONFIG weapon proficiency mapping and placed inside the same proficiency getter in the weapon data, where it will always be treated as proficient (again unless set as 'not proficient').
Closes #2420
Closes #2439
=> [#2420] Add proficiency bonus to features', consumables, and improvised weapons' attack rolls, and implement 'Tavern Brawler' feat in Special Traits

dnd5e.css, less/advancement.less
Just a small quality-of-life visual change.
Closes #2408
=> [#2408] Gray text and no box shadow on `readonly` advancement inputs

templates/actors/parts/actor-features.hbs
Closes https://github.com/foundryvtt/dnd5e/issues/2243
This small change should be enough to display the quantities of items in NPC sheets too:
=> Display quantities for NPC items too

module/canvas/ability-template.mjs
Closes https://github.com/foundryvtt/dnd5e/issues/2215
=> Add spellLevel to measured template flags

module/dice/simplify-roll-formula.mjs
Closes #2281
There was an issue in _simplifyDiceTerms where a Coin was reduced to its operator and number of faces, then assumed to be a die when passed back out. This ended up turning a coin into a die 2 and combining it with any other die 2s in the Dice Terms.
This was fixed by using a c for the faces value if the DiceTerm is Coin and returning a DiceTerm of Coin, instead of Die, if the face value is c.
(Any DiceTerm other than Coin should default to using the number of faces and return as a Die DiceTerm)
=> Add Coin support in _simplifyDiceTerms

dnd5e.mjs, module/applications/actor/base-sheet.mjs, module/applications/actor/hit-points-config.mjs, module/applications/advancement/ability-score-improvement-flow.mjs, module/applications/advancement/advancement-config.mjs, module/applications/advancement/item-choice-flow.mjs, module/applications/item/item-sheet.mjs, module/applications/trait-selector.mjs, module/documents/actor/actor.mjs, module/documents/item.mjs, module/documents/macro.mjs
Closes #2456.
These seemed to come up a lot more often than just in the macro methods.
Also `ui.notifications.<x>(game.i18n.localize(...))` was unnecessary in a lot of cases. It makes it easier to parse switching to the built-in `localize: true` option.
=> [#2456] Fix methods returning notification ids rather than null

module/applications/advancement/ability-score-improvement-flow.mjs
Closes #2441
- Added NaN Check to _onClickButton to reset assignments value to 0 if it is NaN or undefined.
- Added NaN check to getData() to return the assignment to 0 if NaN.
- Added check to set ability as fixed if ability's initial value matched the ability's max value.
=> Add NaN logic to ASI flow

module/applications/advancement/advancement-flow.mjs
The `AdvancementFlow` inherits drag and drop permissions from `FormApplication` which apparently only allows GMs by default.
Closes #2457.
=> [#2457] Fix non-GMs being unable to drop items onto advancement flows

dnd5e.css, less/actors.less, module/applications/actor/character-sheet.mjs, templates/actors/character-sheet.hbs
=> [#2446] Toggle inspiration on the header element

module/data/actor/group.mjs, module/documents/actor/actor.mjs
- `SystemDataModel` now inherits from `TypeDataModel`
- Renamed `_prepareBaseData` on `GroupData` to match naming in core
- Adjusted data preparation to ensure `TypeDataModel` preparation methods are still called
=> [#2495] Allow prepareData methods to be called on module actors

dnd5e.css, less/apps.less, templates/apps/trait-selector.hbs
Just a smol change for ease of use
Closes #2442
https://github.com/foundryvtt/dnd5e/assets/50169243/611c6f39-7d7d-45cb-afeb-b9b2bd277a5c
=> [#2442] Adjust look of trait selectors to always show submit buttons

module/applications/actor/character-sheet.mjs
In the character sheet, not only was `value` (and sometimes `max`) getting deleted, all resource objects were getting mutated with `name` and `placeholder`.
While unsure if actually related, I am also unable to reproduce #2165 with this fix (with a character sheet open or not), but I am if I swap to a different branch without this fix.
=> [#2479, #2232] Prevent resource objects from being mutated

dnd5e.mjs, module/applications/actor/base-sheet.mjs, module/documents/active-effect.mjs, templates/actors/parts/active-effects.hbs
Changes references to `ActiveEffect#label` to use `ActiveEffect#name` and adds a temporary shim to `ActiveEffect5e` on v10 to support that property.
=> [#2515] Fix warning from referenced active effect label

dnd5e.css, less/apps.less, less/items.less, module/applications/accordion.mjs, module/applications/item/item-sheet.mjs, templates/chat/item-card.hbs, templates/items/parts/item-description.hbs
Adds multiple inline editors into items to allow editing normal description, unidentified description, and chat text. When the edit button is clicked the editor replaces the whole tab giving plenty of space to write.
https://github.com/foundryvtt/dnd5e/assets/19979839/09eb8de2-5b2b-409c-830c-5b9d3e559e50
This also will display the chat text in created chat messages rather than the default description if it is provided.
Closes #2135
Closes #2136
=> [#2135, #2136] Add multiple inline editors to items & display chat description

module/data/actor/npc.mjs, module/data/actor/vehicle.mjs, module/data/item/templates/item-description.mjs, module/data/shared/_module.mjs, module/data/shared/source-field.mjs, template.json, templates/actors/npc-sheet.hbs, templates/actors/vehicle-sheet.hbs, templates/items/background.hbs, templates/items/backpack.hbs, templates/items/class.hbs, templates/items/consumable.hbs, templates/items/equipment.hbs, templates/items/feat.hbs, templates/items/loot.hbs, templates/items/spell.hbs, templates/items/subclass.hbs, templates/items/tool.hbs, templates/items/weapon.hbs
First part of #2504 that migrates the data structure to an object. This updates the existing templates to display and reference `source.custom` so a future PR can add a source configuration app.
```javascript
{
book: "",
page: "",
custom: "",
uuid: "",
license: ""
}
```
=> [#2504] Convert source on items & actors into object

dnd5e.css, lang/en.json, less/advancement.less, less/apps.less, module/applications/advancement/_module.mjs, module/applications/advancement/trait-config.mjs, module/config.mjs, module/documents/actor/trait.mjs, module/documents/advancement/_module.mjs, module/documents/advancement/trait.mjs, templates/advancement/trait-config.hbs, templates/apps/parts/trait-list.hbs
Adds the `TraitAdvancement` type and the configuration application.
=> [#1405] Add TraitAdvancement & TraitConfig

module/data/item/templates/action.mjs, module/data/item/templates/activated-effect.mjs, module/documents/item.mjs
Instead of a damage roll requiring a preceding attack roll to gain the benefit of 'ammo damage', the damage roll simply checks if the item has ammo and can attack. The attack roll simply serves to consume ammo, nothing more.
There are some additional benefits to this.
- If one user made the attack roll, another user can still gain the benefit of the ammo on the damage roll, in that weird edge case of two owners of one actor, where before the addition of `_ammo` to the item was local only.
- Users can make all their attack rolls first, and then roll all the damage rolls for easier calculation.
- Users can "redo" a damage roll that was meant to be a critical hit, without having to make another attack roll first.
=> [#2472] Change ammo logic for attack and damage rolls

wiki/Active-Effect-Guide.md, wiki/Home.md, wiki/Roll-Formulas.md
Adds a guide for Active Effect to the wiki
Closes #2481 
tried to include some of the additional md styles outlined here https://github.com/orgs/community/discussions/16925 like this:  
> [!WARNING]  
but it doesnt seem to work in the wiki for some reason https://github.com/orgs/community/discussions/16925#discussioncomment-6883415 hopefully soon, seems potentially useful
I did double check some info from the original guide and made updates/removed changed info, but a second pass would be helpful
Preview on my wiki here: https://github.com/MaxPat931/dnd5e/wiki/Active-Effect-Guide
=> Calego's AE guide

module/documents/actor/actor.mjs
It appears that rollInitiativeDialog creates a _cachedInitiativeRoll before calling rollInitiative which then assumes that a _cachedInitiativeRoll exists for the hook. This would return undefined to the dnd5e.preRollInitiative hook if called directly. (this doesn't cause errors in the initiative roll as foundry code calls getInitiativeRoll and it returns the cached roll if it exists or gets a new roll)
To fix this issue:
- I added a check to see if there is a _cachedInitiativeRoll in rollInitatiative and if not to call getInitiativeRoll to get a new roll and cache it.
- I added a rollOptions to rollInitiative to allow for providing RollOptions to the getInitiativeRoll if the _cachedInitiativeRoll does not exist.
- Moved the delete this._cachedInitiativeRoll from rollInitiativeDialog to …
=> Add cached roll to direct rollInitiative call

lang/en.json, module/applications/actor/character-sheet.mjs, module/applications/actor/npc-sheet.mjs, module/applications/actor/vehicle-sheet.mjs, module/data/abstract.mjs, module/data/actor/character.mjs, module/data/actor/templates/details.mjs, module/data/fields.mjs, module/data/item/background.mjs, module/data/item/race.mjs, module/documents/actor/actor.mjs, module/documents/item.mjs, module/documents/mixin.mjs, module/migration.mjs, system.json, templates/actors/character-sheet.hbs
Displays race item above background on features tab of character sheet.
Adds a `LocalDocumentField` to reference a single item on an actor, and replace `background` & `race` properties with this new field. This field has a `fallback` option so that if the item isn't found, then string is displayed (allowing existing hand-typed Race and Background values to continue displaying properly).
Used a mixin for `Item5e` and `Actor5e` that forwards socket event handler requests to their data models, allowing each type to add custom socket event handler behavior. This behavior is used in `RaceData` and `BackgroundData` to set `system.details.race` and `system.details.background` to reference any newly added items, and unset it when they are deleted. This is also used for any item marked with the …
=> [#342, #2538] Display race on sheet, add singleton logic to race & background items

dnd5e.css, less/items.less, module/applications/item/item-sheet.mjs
Also increases the base height of item sheets to 500px, up from 400px, to accommodate a common amount of item properties in that section.
Closes #1668
=> [#1668] Allow for `.item-properties` to scroll

lang/en.json, module/enrichers.mjs
Implements a damage enricher in the format `[[/damage 1d6 bludgeoning]]` or `[[/damage formula=1d6 type=bludgeoning]]` which will present the normal damage rolling dialog, allowing criticals to be rolled and damage types to be passed through.
Closes #2529
=> [#2529] Implement damage enricher

module/applications/actor/character-sheet.mjs, module/applications/actor/npc-sheet.mjs, module/data/actor/character.mjs, module/data/actor/npc.mjs, module/data/shared/creature-type-field.mjs, module/data/shared/source-field.mjs, templates/actors/parts/actor-traits.hbs
Adds creature type to the PC traits section:
=> [#342] Add creature type data to PCs

module/documents/item.mjs
There are at least for me a lot of cases where I want to keep the creation of spell scrolls under control.
For example, only mages can create them, or to prevent players from messing up when a spell is dragged on the sheet.
A simple preHook in the method is more than enough for any existing use case.
=> Add preHook on the "createScrollFromSpell" function

module/applications/actor/base-sheet.mjs, module/data/actor/character.mjs, module/data/item/race.mjs
- Movement types and senses are applied automatically, assuming the current value on the actor isn't already higher
- ~~Creature type isn't applied yet because we don't have it displayed on the actor, I'll handle that in another PR~~
- When deleting the race, movement and senses are unapplied if the value is equal to that on the race (so we don't get rid of values if the player has changed them)
- We now prompt when removing backgrounds & races with advancement just like with classes & subclasses
- If the player unchecks "Remove advancement changes" when deleting a race, it will not unapply any of the direct changes
=> [#342] Apply senses/movement to actor when race is added

module/documents/advancement/ability-score-improvement.mjs
Displays what ASIs will be granted when in config mode so more information is available at a glance:
=> [#2561] Display ASI values in config mode

dnd5e.css, less/apps.less, less/items.less, module/applications/accordion.mjs, templates/items/parts/item-description.hbs
- Adds an indicator that helps indicate whether the accordion is open or closed (#2569)
- Fixes a jump that occurs when sheet is re-rendered (#2567)
- Fixes spacing for empty accordions that are expanded
https://github.com/foundryvtt/dnd5e/assets/19979839/55c19eda-7fd7-4d11-9177-9d787e048361
=> [#2567, #2569] Add status indicator to accordions, fix jump on sheet re-render

dnd5e.css, lang/en.json, less/apps.less, less/items.less, less/npc.less, module/applications/_module.mjs, module/applications/actor/base-sheet.mjs, module/applications/item/item-sheet.mjs, module/applications/source-config.mjs, module/config.mjs, module/data/shared/source-field.mjs, module/utils.mjs, templates/actors/npc-sheet.hbs, templates/apps/source-config.hbs, templates/items/background.hbs, templates/items/backpack.hbs, templates/items/class.hbs, templates/items/consumable.hbs, templates/items/equipment.hbs, templates/items/feat.hbs, templates/items/loot.hbs, templates/items/parts/item-source.hbs, templates/items/race.hbs, templates/items/spell.hbs, templates/items/subclass.hbs, templates/items/tool.hbs, templates/items/weapon.hbs, templates/journal/page-class-edit.hbs
Add a source editor for configuring the new source data on items and NPCs:
The editor uses a data list to display recommendations for Book and License, but it doesn't require they match something in config:
I've only added on book and license at the moment for the SRD, but it might be worth it to add other options even if we aren't going to use them for built-in system content to aid players creating stuff themselves.
=> [#2504] Implement editor for source data

dnd5e.css, less/apps.less, module/applications/actor/type-config.mjs
=> [#2579] Fix creature type still being editable despite being overridden by an Active Effect.

module/documents/actor/actor.mjs
Not sure why we were checking `_source.attributes.hp.max` rather than the regular value. I changed it over any everything still seems to be working.
=> [#2401] Allow max HP to be overriden by effects

module/applications/accordion.mjs
~~This fix at least ensures that the contents of the accordion are always visible, but it doesn't animate for the first expanding after changing another property. I would welcome thoughts as to a better fix.~~
Found a better fix that properly stores the height.
> [!Note]
> I switched from using `setTimeout` to `requestAnimationFrame` for the accordion timing here because it felt more appropriate, but that isn't part of the actual bug fix.
=> [#2607] Fix collpased accordion sections not opening after editing description

module/applications/item/ability-use-dialog.mjs, templates/apps/ability-use.hbs
When a spell is set to "pact," a warning is always shown despite there being pact slots available if the actor has no regular slots of the spell's level.
This changes it so warnings are not shown for spells set to "pact" if there are slots of the spell's level _or_ there are pact slots available.
=> Amend warning on AbilityUseDialog for pact slots

module/applications/actor/type-config.mjs, module/config.mjs, module/data/actor/npc.mjs, module/documents/actor/actor.mjs
Changes `CONFIG.DND5E.creatureTypes` to be nested objects, each with `label` and optionally `detectAlignment`.
I opted not to do something like `alignment: "good"`, since the official rules seem to be shying away from such things.
[Related](https://github.com/foundryvtt/dnd5e/pull/2269#discussion_r1269791096)
=> Update creatureTypes to be object

module/data/item/_module.mjs, module/data/item/consumable.mjs, module/data/item/equipment.mjs, module/data/item/fields/item-type-field.mjs, module/data/item/loot.mjs, module/data/item/tool.mjs, module/data/item/weapon.mjs
Modified how the new type fields are created so that we can exclude the fields that aren't used on certain types (e.g. no `baseItem` on consumables or `subtype` on weapons). Also cleaned up a few comment and export issues.
=> [#2168] Tweak item types to allow certain fields to not be included

dnd5e.css, lang/en.json, less/chat.less, module/enrichers.mjs, module/utils.mjs, templates/chat/request-card.hbs
Adds a button that is displayed for GMs next to enriched checks & saves to request a roll from players:
This creates a chat card that can then be clicked by players:
- Option to hide the DC of the check from players
- Ability for GM to whisper the request to certain players
- Nicer chat card design
=> [#2513] Add link for GMs to request roll from inline roll

module/data/item/spell.mjs, module/documents/item.mjs
Swap spell components over to using the new properties migration system added to avoid potential data loss.
=> [#2636] Modify spell component migration to avoid losing properties

module/applications/item/item-sheet.mjs, module/data/item/consumable.mjs, module/data/item/equipment.mjs, module/data/item/templates/item-description.mjs
Allows individual item types to define their own custom properties behavior rather than ballooning the method on the item sheet for each exception.
=> [#2636] Move valid properties into system data models

module/data/item/consumable.mjs, module/documents/item.mjs
Adds `concentration` as a valid item property if the consumable subtype is `scroll`, and fixes a few issues with `Item5e#createScrollFromSpell`.
=> Add 'concentration' to scroll properties, fix createScrollFromSpell

module/documents/item.mjs
This adds the item ID and the parent name and ID to the warning message output in the console when the formula simplification fails for an item, and also provides the full error object rather than just the message. The motivation behind this is to make it much easier to identify the source of this warning.
=> Add more detail to formula simplification failure warning message

module/data/actor/character.mjs, module/data/actor/npc.mjs, module/data/actor/templates/common.mjs, module/data/actor/vehicle.mjs, module/documents/actor/actor.mjs
This moves the getRollData to a system method (if it has one).
Also adds `flags` to getRollData, which is a common ask.
Also moves `attributes.spellmod` to data prep where it probably should always have been. \:-)
Closes #2698
=> [#2698] Move getRollData to system models

module/applications/item/item-sheet.mjs, module/documents/actor/actor.mjs
The 2.5 branch broke AC due to a missing word.
This also adds the ability to add shield 'subtypes', in line with how other armor proficiency categories work. To clarify, the issue is that adding anything to `CONFIG.DND5E.shieldIds` does not allow a user to set an item to be of this newly added shield type.
=> Fix armor class, allow for shield subtypes

module/documents/token.mjs
Remove the fallback that appends `-subject` to the inferred subject path because it is causing a lot of 404 errors for users. Technically a breaking change if anyone was using it, but not a big one.
=> [#2819] Remove subject fallback to prevent 404s

less/v2/inventory.less
Align encumbrance arrows on their centres. Position of arrow in image is just to show an easy reference point.
Partially closes #2796 depending on the handling of the bar's border width.
=> [#2796] Align encumbrance arrows on centre

lang/en.json, templates/actors/tabs/character-details.hbs
=> [#2827] Fix localization strings for bypasses, make tooltip clearer

module/documents/item.mjs
In a [module](https://github.com/krbz999/babonus/issues/222), I read several properties of the item being used for attack rolls, damage rolls, and tool checks. When the tool checks were moved over to the actor, I lost the ability to read any additional properties in the tool's flags for my purposes. This adds a simple reference to the tool, if any specific one was used, so I can do that again.
=> Add reference to the tool being used in tool checks

less/v2/inventory.less, module/applications/actor/character-sheet-2.mjs, templates/shared/inventory2.hbs
Allows for the encumbrance arrows on the encumbrance card to adjust based on thresholds:
=> [#2798] Support adjustable encumbrance arrows

module/applications/actor/character-sheet-2.mjs
There was an issue in character-sheet-2.mjs _renderOuter() when mapping a callback we return a new Tabs5e using the this.options.tabs which used the initial as the active, which overwrote the previous active. New code changes the initial to the previous active tab if the initial does not match the active tab, before passing it to the constructor. 
Additionally changed a check condition in setting GetData() activeTab where the DOM element length was checked and otherwise "details" was set as the activeTab even when we had an existing active tab. This element check was removed.
Closes #2868
=> [#2868] Fix issue with active tab not being saved when sheet is re-opened

module/applications/components/item-list-controls.mjs
The filtering method on ItemListControlsElement creates a mapping between entry IDs and the elements they represent in the list. The problem is that grandchild elements might share identical IDs, but this setup only allows them to be associated with a single element, causing one of the grandchild documents to not appear at all in the list.
The fix was to rely on the `data-parent-id` property already in the list to handle dragging effects to ensure each document has a totally unique identifier in the element map.
=> [#2879] Ensure grandchild documents with identical IDs are displayed properly

lang/en.json, module/config.mjs
Closes #2949.
The string for 'Sleeping' was already there, so this must have been half a mistake. They were named this way in my initial PR.
=> [#2949] Rename some conditions

module/documents/chat-message.mjs
Closes #2976.
Also prevents errors being thrown when actors are missing.
=> [#2976] Use total of all rolls for temphp, prevent errors for broken tokens

module/applications/actor/character-sheet-2.mjs, module/config.mjs, module/data/actor/templates/attributes.mjs, module/documents/active-effect.mjs, module/documents/actor/actor.mjs, templates/actors/character-sheet-2.hbs
Allows for exhaustion to be configured in the `CONFIG` object (or entirely disabled) and generalizes some code surrounding it to match.
=> Allow for exhaustion to be configurable

module/applications/actor/character-sheet-2.mjs, templates/actors/tabs/character-spells.hbs
Showing "Always Prepared", "Prepared", and "Unprepared" spells:
Here is an alternative icon:
=> [#2992] Use different icons for unprepared & always prepared states

module/applications/actor/base-sheet.mjs, module/applications/item/item-sheet.mjs, module/data/abstract.mjs, module/data/actor/character.mjs, module/data/actor/group.mjs, module/data/item/background.mjs, module/data/item/race.mjs, module/documents/item.mjs
Move singleton property from `SystemDataModel#metadata` to `ItemDataModel#metadata` and reworked data model metadata as frozen object with proper default values.
Added `supportsAdvancement` metadata option to `ActorDataModel#metadata` to indicate actor types that can have advancement applied. Using the new metadata property in `deleteDialog` should ensure no errors for module-provided actor types.
=> [#2947] Add metadata.supportsAdvancement, fix issue with deleteDialog failing

module/applications/actor/character-sheet-2.mjs
Adds a context menu on ActorSheet5eCharacter2 targeting any element with `data-item-id` that is inside `.pills-lg`, which allows it to target all the concept items that exist outside the normal inventory elements.
In order to properly activate the context menus on these elements it fetches the `InventoryElement` on the features tab and uses its `_onOpenContextMenu`.
Closes #2867
=> [#2867] Add context menus to race, background, classes, & subclasses

module/applications/context-menu.mjs
Previously the tooltip sizing wasn't available because it didn't yet exist in the DOM. Moving the `appendChild` call to the top of the method resolved that.
This also required anchor the tooltip by its bottom edge when expanding up to ensure the display/hiding animation occurred in the correct direction.
Closes #2876
=> [#2876] Fix context menus being displayed off the bottom of the screen

module/data/token/token-system-flags.mjs
Adds the flags that track transformation status into `TokenSystemFlags` so they can be properly tracked and merged during transformation.
=> [#2995] Fix transformation reversion errors

module/applications/components/effects.mjs, module/documents/active-effect.mjs
Just changes the names of active effects that belong to items that are unidentified.
The details of the active effect can still be determined by opening its sheet, but modifying that behavior is a much larger change.
=> [#2885] Hide active effect names when from unidentified item

module/documents/actor/actor.mjs
Previously the scrolling damage numbers and token flashes would be calculated based on the damage amount, without regards to how much HP the actor currently has. This results in showing floating numbers even when nothing about the actor's HP has been modified.
This change clamps the change to HP based on their current HP (for damage) or the negative of their current damage (for healing). To assist with this `hp.damage` has been added during hit points preparation for easy reference.
One limitation of this is that the damage numbers reflect only the damage applied, not the total damage taken, which might underrepresent massive hits. An alternative solution is to do the same clamping, but only check if `deltaTemp + deltaHP` is zero and don't pass `dhp` to the update function if nothing was …
=> [#2979] Clamp damage/healing amount so it doesn't exceed HP bounds

module/migration.mjs
First fix was a bug that was thrown if the `origin` on an effect was `null`. The existing check assumed all origins were strings, which would throw an error on `null` origins and prevent checks against subsequent effects from occuring.
The second fix was due to the way the effect de-duplicate worked with the `persistSourceMigration`. The de-duplication operated by calling `deleteEmbeddedDocuments` on the document being migrated to remove the effects, but when `persistSourceMigration` was set it would perform an update on the actor data without diffing resulting in the effects being added back. To fix this we swap to removing the effects from the source data if that flag is set. This fix is only necessary for compendium migrations because world migrations perform the update before the …
=> [#2934] Fix issue with active effect de-duplication

module/documents/actor/actor.mjs
Copy over the token ring flags when transforming the actor and restore/remove them properly when reverting.
=> [#3055] Fix issue with token ring not being handled properly when transforming

module/applications/advancement/advancement-selection.mjs, module/applications/item/item-sheet.mjs, module/config.mjs, module/data/fields.mjs, module/data/item/race.mjs, module/documents/actor/actor.mjs, module/documents/advancement/ability-score-improvement.mjs, module/documents/advancement/advancement.mjs, module/documents/advancement/hit-points.mjs, module/documents/advancement/scale-value.mjs, module/documents/advancement/size.mjs, module/documents/item.mjs
Changes `advancementTypes` into an object and moved `validItemTypes` from `Advancement#metadata` into the configuration object, so module custom types can define what advancement types they accept.
The deprecations should ensure everything continues working for any custom advancement types.
=> [#2747] Move advancement valid item types into config so module subtypes can change it

module/applications/item/ability-use-dialog.mjs
Modules can use `dnd5e.preUseItem` to add their own properties to the configuration, but this is not be available in the `AbilityUseDialog`.
Currently we can only use a render hook, and *assume* that the key must be `true` if the item is able to do the related thing (and otherwise do nothing), but it would be good to be able to make use of the pre-use hook as well in case a user wants to programmatically skip the prompt; i.e., set it to `null` or `false`.
With this, a module can read the key in `abilityUseDialog.configuration` and set the default value accordingly (or not at all if `null`).
=> Expose ItemUseConfiguration in AbilityUseDialog

module/applications/item/item-sheet.mjs
Previously we forced the height of the item sheet to certain values whenever the app was moved (due to overriding `setPosition`). The approach in this PR only automatically changes the height when the tab changes, rather than any time the app moves.
We can also just rely on the standard auto height sizing to adjust the size of the sheet for the content (like for a class or subclass sheet). This results in fewer non-standard cases and is more consistent UX IMO.
Closes #2224
[changing tabs on the item sheet](https://github.com/foundryvtt/dnd5e/assets/1226888/fe0e96b1-e346-44f6-8559-de1835d9e345)
=> [#2224] Only automatically set item sheet height on tab change

dnd5e.mjs, lang/en.json, module/applications/_module.mjs, module/applications/actor/character-sheet-2.mjs, module/applications/sheet-config.mjs, module/config.mjs, module/settings.mjs, templates/shared/sheet-config.hbs
Replaces the standard sheet configuration dialog with one that includes a theme dropdown:
It also adds the same theme dropdown into the system settings.
Doesn't implement any themes itself, but will add `data-theme="<name>"` to the sheet if selected on the sheet, or the body if set in the global settings.
=> [#2864] Add theme option to sheet config & system settings

less/v2/apps.less, less/v2/character.less
Swapped a bunch of relative units used for spacing and positioning with absolute ones to fix the worst of the layout issues at alternate font sizes. Font size can go down as low as 1 and everything still lays out fine, but it still has some issues going much higher than 7.
=> [#3058] Fix bad spacing with alternate font sizes

lang/en.json, less/v1/apps.less, module/applications/actor/_module.mjs, module/applications/actor/armor-config.mjs, module/applications/actor/base-config.mjs, module/applications/actor/base-sheet.mjs, module/applications/actor/character-sheet-2.mjs, module/applications/actor/damage-modification-config.mjs, module/applications/actor/hit-points-config.mjs, module/applications/actor/movement-config.mjs, module/applications/actor/trait-selector.mjs, templates/actors/tabs/character-details.hbs, templates/apps/damage-modification-config.hbs
Displays damage modifications on the sheet beneath vulnerabilities:
And provides a new configuration application for setting them:
Closes #2849
=> [#2849] Display damage modification on sheet, add configuration app

lang/en.json, less/v1/items.less, module/applications/item/_module.mjs, module/applications/item/item-sheet.mjs, module/applications/item/summoning-config.mjs, module/config.mjs, module/data/item/templates/action.mjs, templates/apps/summoning-config.hbs, templates/items/parts/item-action.hbs
Adds a new item action mode, "Summon", which displays a configuration application for configuring summoning from that item:
The application allows for configuring several potential summoning profiles, which at the moment are limited to summoning a single actor via UUID but could be expanded in the future to support referencing certain creature types & CRs for something like Conjure Animals.
The configuration window also displays changes made to the summoned actor and any items on that actor during the process of summoning, allowing changes to armor class & hit points to match summoner's stats or spell level, and matching proficiency, attacks' to hit, and saving throw DCs.
The is the initial part of the process of merging the functionality from [Arbron’s …
=> [#893] Add data model & configuration data for summoning

less/v1/apps.less, less/v1/inventory.less, less/v2/apps.less, less/v2/inventory.less, templates/actors/parts/actor-features.hbs, templates/actors/parts/actor-spellbook.hbs, templates/actors/tabs/character-features.hbs, templates/actors/tabs/character-spells.hbs, templates/shared/active-effects.hbs, templates/shared/active-effects2.hbs, templates/shared/inventory.hbs, templates/shared/inventory2.hbs
Adds `inventory-element` and `effects-element` classes to any place we use `dnd-inventory` and `dnd-effects` custom elements to allow those sections to be styled even when the custom element is swapped for something else. 
Closes #2944
=> [#2944] Modify inventory/effect styles to not use element name

module/applications/components/_module.mjs, module/applications/components/adopted-stylesheet-mixin.mjs, module/applications/components/filigree-box.mjs, module/applications/components/icon.mjs, module/applications/components/proficiency-cycle.mjs
For details of the actual buggy behavior see: https://github.com/League-of-Foundry-Developers/fvtt-module-popout/issues/109
TL;DR - Moving a custom (or otherwise) HTML element to a new window involves adopting it into the new windows document. However any use of constructed CSS (i.e. new CSSStyleSheet) will be silently stripped or fail outright unless we are careful to construct new copies of the CSSStyleSheet object via the new window's constructor.
For custom elements that use constructed CSS, we have to implement the adoptedCallback method and manually reconstruct and reattach a new CSS object to the shadow DOM. This is because when a custom element is moved to a new document, any constructed CSS objects that it has adopted already are silently stripped.
We also need to update how we …
=> Popout! compatibilty (Fixes #3044)

module/documents/item.mjs, templates/chat/item-card.hbs
I was working on an project using `dnd5e` which required me to store temporary item data in chat cards rather than relying on an actual item that exists on an actual actor.
This worked fine because of our chat card framework supporting the possibility of `storedData = message.getFlag("dnd5e", "itemData")` on the chat message itself, but this broke down if that item contains active effects which should apply to its usage because the `case "applyEffect"` handler required the effect to be retrieved by `uuid` rather than using a local `id` within the `item`.
This change prefers an effect local to the item of the chat card rather than a UUID lookup.
=> Allow stored item data in chat cards to contain active effects

module/config.mjs, module/data/actor/character.mjs, module/data/actor/templates/attributes.mjs
- Fixed: *Prone* condition halved the movement speed incorrectly.
- Changed: Apply flat speed reductions of encumbrance after speed halving of *Exhaustion 2*.
- Fixed: Halved movement speed was rounded (floored).
- Added: Support for metric units in movement speed calculations.
=> Movement speed calculation fixes

module/applications/token-config.mjs, module/documents/token.mjs, module/utils.mjs
The goal of this PR is to simplify the usage of the new item resources without fully replicating the system's behavior. Working around the current implementation of `TokenConfig._prepareResourceLabels` is very difficult because it runs after the entire rendering pipeline. This is resolved by moving the logic to the earliest possible place. More specifically:
- Moved the attribute grouping to `TokenDocument.getTrackedAttributeChoices` to allow modules to use the localized groups.
- Moved the item attributes to `TokenConfig.getData` to allow dealing with them in the regular rendering pipeline.
- Moved the item name resolution to `getHumanReadableAttributeLabel` to allow resolving relative item names globally.
- Changed the selector in `TokenConfig._prepareResourceLabels` to …
=> Improve compatibility of localized token resources.

module/enrichers.mjs
Did a bit of re-ordering of enrichers to keep things grouped together for easier code perusal.
Closes #3116
=> [#3116] Add ability to embed actor & item descriptions

module/documents/actor/actor.mjs
Shifts damage calculation into separate method so it can be used to preview damage that will be applied.
Closes #3125 
Closes #3126
=> [#3125, #3126] Move damage calculation to own method

lang/en.json, module/data/item/equipment.mjs, module/data/item/templates/equippable-item.mjs, module/data/item/weapon.mjs, module/documents/actor/actor.mjs, module/documents/item.mjs, templates/items/equipment.hbs, templates/items/weapon.hbs
Introduces `system.magicalBonus` to weapons and `system.armor.magicalBonus` to equipment to represent bonuses to attack, damage, and AC from the magical part of these items.
Also introduces `system.magicAvailable` to physical items that indicates whether the magical effects of these items is available. Currently this is only based on current attunement, but could be expanded later to other things that might make magic unavailable.
=> [#3147] Add magical bonus to weapons & armor

module/data/item/consumable.mjs, module/documents/item.mjs, templates/items/consumable.hbs
Calls `Roll.replaceFormulaData` on the ammo attack bonus before it is added to the weapon's to hit formula to avoid errors with string terms not resolving.
Adds `magicalBonus` to ammunition that acts like that on weapons. This adds to the attack bonus for the weapon when it is being used with the ammunition. The damage bonus is appended to the first damage formula on the weapon, and the damage properties gain any physical properties provided by the ammunition so silvered or magical ammo properly carries through to the weapon damage.
This also changes how additional ammo damage is added to make use of the new system for multiple rolls on damage. Ammunition damage is now constructed as separate rolls with their own type data rather than being appended to the base weapon damage formula. …
=> [#2920, #3147] Add magical bonus to ammo, fix attack bonus data

module/documents/actor/actor.mjs
Adding the actor method to roll a concentration saving throw, allowing for a DC and other properties to be provided.
Adds two standard hooks.
Making use of `concentration.roll.min` and `.max` for modifying the D20Roll is left as follow-up work since this is [blocked by the roll refactor](https://github.com/foundryvtt/dnd5e/pull/1760#issuecomment-1866519625).
=> [#3033] Add concentration actor method and hooks

lang/en.json, module/applications/item/ability-use-dialog.mjs, module/data/item/templates/action.mjs, module/data/item/templates/activated-effect.mjs, module/documents/item.mjs, templates/apps/ability-use.hbs, templates/apps/summoning-config.hbs, templates/chat/item-card.hbs, templates/items/parts/item-action.hbs
Adds summoning configuration to the item usage configuration and the ability use dialog. Players will see a checkbox to indicate whether summoning should occur and if the item has more than one summoning profile, a dropdown for selecting which profile to use:
This also introduces a `prompt` boolean similar to the one used for measured templates and limited uses to control whether it is done by default or not. If the `"Place Summons"` checkbox is checked, then the selected summoning profile ID is stored in flags in the chat message.
A new `"Summon"` button has been added to the chat message to perform the summoning if not done automatically through the ability use process:
If the button is clicked it will try to summon whatever profile is specified in the flags, or if none is specified it …
=> [#893] Add summoning to item activation workflow

module/data/abstract.mjs, module/documents/actor/actor.mjs, module/documents/item.mjs, module/enrichers.mjs
Adds a new enricher that allows for looking up values within roll data and displaying them as is:
This includes an extra `extended` option for `getRollData` that includes the creature's name. This could be extended in the future to include additional data, like perhaps the localized creature type or anything else that would be useful in this context but not in standard roll formulas.
=> [#997] Add lookup enricher for including non-roll data

less/dnd5e.less, less/elements.less, less/v2/apps.less, less/v2/character.less, less/v2/dark/apps.less, less/v2/high-contrast/apps.less, less/v2/high-contrast/character.less, less/v2/high-contrast/inventory.less, less/v2/inventory.less, less/variables.less, module/settings.mjs
This uses `matchMedia` to set a high contrast flag. This is handled as a flag list in preparation for additional theme flags.
Moves all the high contrast changes into separate folder to match dark mode separation.
=> Adapt high contrast mode to dark mode

module/migration.mjs
Should do the job to gate those active effect migrations, but I haven't tested it on a world that requires those migrations yet.
=> [#2935] Prevent effect migrations from running more than once

module/data/actor/character.mjs, module/data/actor/npc.mjs, module/data/actor/templates/attributes.mjs, module/data/actor/templates/common.mjs, module/data/actor/vehicle.mjs, module/documents/actor/actor.mjs, templates/actors/npc-sheet.hbs, templates/apps/hit-points-config.hbs
Moves most of the logic from `Actor5e._prepareHitPoints` into a new `AttributesFields.prepareHitPoints` method with changes to allow different types to customize how their hit points are prepared.
In order to make that change it also required the moving of `Actor5e._prepareAbilities` to `CommonTemplate.prepareAbilities` so that ability modifiers could still be calculated before the hit points.
`NPCData` now fetches `HitPointsAdvancement`s from its classes and adds those to the hit points it calculates.
Closes #3185
=> [#2094, #3185] Move ability & hp prep, fix advancement HP on NPCs

less/v2/chat.less
Per https://developer.mozilla.org/en-US/docs/Web/CSS/position#absolute "The element is positioned relative to its closest positioned ancestor (if any) or to the initial containing block." 
This was causing an issue where the exploded marker was being placed relative to message-content as it the last positioned ancestor for non-min or non-max rolls. (the color filter appeared to cause min and max rolls to have a containing block allowing them to position correctly.) This was fixed by adding a relative position to .roll (instead of unset) 
Closes #3130
=> [#3130] Modified roll CSS Position

module/config.mjs
These were deprecated on the 2.5 branch, then un-deprecated during v3.0.0 development, then properly deprecated again in a minor update.
This adds the notes of deprecation to them, which were missing. I opted for v3.3 due to the above circumstances.
=> Add deprecation note to spell comps and tags

module/data/actor/character.mjs, module/data/actor/npc.mjs, module/data/actor/templates/attributes.mjs, module/data/actor/templates/creature.mjs, module/data/shared/roll-config-field.mjs, module/documents/actor/actor.mjs
Removed `bonus` field from `RollConfigField`. This would have conflicted with those properties, like `skills`, that have `bonus` as derived data. Instead individual properties define `bonuses` with 'check' and/or 'save'.
Seems the only property that has `bonus` as an actual field is `attributes.init`, but it doesn't - in my opinion - seem worth it to migrate this to `attributes.init.bonuses.check`.
=> Convert several attribute fields to use `RollConfigField`

module/applications/actor/npc-sheet.mjs, module/data/actor/character.mjs, module/data/actor/npc.mjs, module/data/actor/templates/attributes.mjs, module/data/item/race.mjs
Introduces a new `AbilitiesFields#prepareRace` method that takes a race item and applies its stats to the actor, either complementing the default values or replacing them depending on whether the `force` option is set.
This then replaces the existing code in `CharacterData` that used to apply race data and is added to `NPCData`.
Closes #2668
=> [#2668] Derive NPC details from race item if present

module/dice/dice.mjs, module/documents/item.mjs
In `3.0.0` we modified `Item5e#rollDamage` to support separate rolls for multiple damage parts and added `returnMultiple` option for backward compatibility. The issue with that initial implementation is that if `returnMultiple` is `false`, it returns the first roll made rather than matching previously behavior of having all the damage parts merged into a single roll.
This change alters the bahavior of `damageRoll` if `returnMultiple` is `false` and there are more than one roll to create a new merged roll from the evaulated rolls and return that.
The separate rolls are still stored in the chat message and used by the system, but the combined rolls are now available to modules that rely on the `dnd5e.rollDamage` hook or call `Item5e#rollDamage` directly.
=> [#3183] Adjust rollDamage to return merged roll, rather than first

lang/en.json, module/applications/item/summoning-config.mjs, module/data/item/_module.mjs, module/data/item/fields/summons-field.mjs, module/data/item/templates/action.mjs, module/documents/item.mjs, templates/apps/summoning-config.hbs
Moves the summoning data into an `EmbeddedDataField` to allow for the summoning methods to be defined there rather than taking up a bunch of space in `ActionTemplate`.
Introduces `SummonsData#summon` method which takes the ID of a summoning profile and proceeds through the process of summoning the actor:
1) Fetches the actor to summon based on the profile. This will eventually need some extra work to handle summoning from compendiums.
2) Minimizes the actor sheet (if open) and determine placement on scene. Currently the placement is a placeholder method that just places the summons in a fixed position.
3) Iterates over all token placements, requesting updates that will be made to the actor and its contained items for each placement.
- Match proficiency is applied using an active effect
- …
=> [#893] Add summoning actor updates & overall workflow

module/applications/advancement/advancement-config.mjs, module/applications/advancement/item-choice-config.mjs, module/applications/advancement/item-choice-flow.mjs, module/applications/advancement/item-grant-config.mjs, module/applications/advancement/item-grant-flow.mjs, module/data/advancement/item-choice.mjs, module/data/advancement/item-grant.mjs, module/data/fields.mjs, module/documents/advancement/item-choice.mjs, module/documents/advancement/item-grant.mjs, templates/advancement/item-choice-config.hbs, templates/advancement/item-grant-config.hbs
Necessary migration to allow for additional per-object configuration of granted items or choices. Now granted & chosen items are represented by and object with a `uuid` value, rather than a straight UUID string.
May be a breaking change for any custom migrations relying on the drop functionality built in to `AdvancementConfig` which now assumes objects rather than strings as the target value. This could be made to not be a breaking change if we added some extra handling to detect the field type of the target (about a 3 line change if desired), but I'm not sure anyone is relying on this at the moment.
Had to remove `AdvancementDataField#_cleanType` which was interfering with the migrations, but I don't think it is necessary because cleaning is handled during the sub-model initialization.
=> Migrate ItemGrant & Choice to store items as objects rather than UUIDs

module/applications/item/ability-use-dialog.mjs, module/documents/item.mjs
Closes #3245.
Additionally added a check for `Item5e#isActive` since ability use notes should not matter for inactive items (this could cause the "no uses left" note to show up when an item had 0 quantity or 0 uses).
=> [#3245] Special handling for concentration icon and 'passive' items

lang/en.json, module/data/item/fields/summons-field.mjs, templates/apps/summoning-config.hbs
Adds three bonuses that add to attack damage, saving throw damage, and healing. Formula data in these is resolved at summoning time based on the summoner stats so something like `@item.level` can be used to add the spell's level of damage to an attack.
=> [#893] Add damage & healing bonuses to summoning configuration

module/applications/item/ability-use-dialog.mjs, module/documents/item.mjs
Hides spell upcasting, spell warning, and the concentration checkbox when summoning from chat:
=> [#893] Hide options in ability use dialog when summoning from chat

module/documents/chat-message.mjs, module/documents/item.mjs
Adds a check when preparing `ItemUseConfiguration` to ensure scene is open before presenting the option to place a template.
Also adds a check when rendering chat messages to ensure a scene is open and the user has permission to place template. The one limitation of the chat card change is that the button will not re-appear when a scene is opened, requiring a refresh to see the button. An alternate approach would be adding a style that hides the button if no scene is open, but that would require a class or property somewhere up the DOM that it could check, which isn't currently available.
Closes #3165
=> [#3165] Prevent template placement if no scene is open

module/documents/actor/actor.mjs, module/documents/chat-message.mjs
If a `DamageDescription` with the type `healing` is encountered in `Actor5e#calculateDamage` it will now be automatically inverted rather than relying on the `multiplier` option. This simplifies the usage of `applyDamage` and opens up the possibility of mixing damage and healing (if you wanted to do a risky healing feature that does 1d4 bludgeoning damage and heals 1d6, that is now possible).
This inversion is applied by default, but can be turned off by the new `invertHealing` option passed to `applyDamage`.
Another new option is `only`, which tells the damage system to only apply damaging or healing damage parts. This option should be useful for reworking the damage application interface to allow for three options: "Apply All", "Apply Damage", & "Apply Healing".
=> [#3248] Invert healing automatically in `calculateDamage`

lang/en.json, module/data/item/fields/summons-field.mjs, module/data/item/templates/action.mjs, module/data/token/token-system-flags.mjs, module/documents/chat-message.mjs, module/documents/item.mjs, module/settings.mjs
Adds a `SummonsData#canSummon` property that determines whether a scene is open and whether the user has permissions to summon. If not, then no summoning control is displayed in the `AbilityUseDialog` and the chat button is removed.
If user is trying to summon and actor that they do not have ownership of the will be shown an error.
Also introduces a check for file browser permission when creating token data if the token is set to use a wildcard image. If the user lacks permission here, then the token will fall back to using the portrait image and a warning will be displayed in the console.
Adds a new `SummonsData#fetchActor` data which handles locating the actor to be summoned. If the actor is in the world, then it just returns that version. If the associated actor is in a compendium, it …
=> [#893] Improve permissions checks & allow compendium summoning

module/dice/_module.mjs, module/dice/aggregate-damage-rolls.mjs, module/documents/chat-message.mjs
Adds a new dice helper function `aggregateDamageRolls` which splits and re-combines damage rolls based on the roll's type, term flavor, and optionally any roll properties. This function is then used by `ChatMessage5e#applyChatCardDamage` before rolls are totaled to ensure that damage types are properly split.
The function starts by using a `chunkTerms` helper function which goes through the terms in a roll grouping into chunks based on the operators. Addition and subtraction cause new chunks to be created while multiplication and division are included in the same chunk. This is so that a damage type defined in flavor of a term can spread to other terms that it is multiplied or divided with. So if you have a formula `1d6 + 5 * 1d4[fire]` that has the overall type of piercing, the `1d6` …
=> [#3250] Aggregate damage types before passing to `applyDamage`

module/dice/aggregate-damage-rolls.mjs, module/documents/chat-message.mjs
Switch to using the `aggregateDamageRolls` function while enriching damage tooltips to get damage split into groups by type. The method for creating breakdowns no longer needs to worry about types.
The `aggregateDamageRolls` function has been modified to strip out any damage-type flavor for the resulting terms (preserving other flavor) so that it doesn't clutter up the final formula displayed.
This change also allows us to rely on the damage total from each aggregated roll which means the totals per-type are always accurate. There is still some trouble with how multiplication and division are displayed in the roll breakdown, but the totals should now always be correct.
=> [#3158, #3250] Use `aggregateDamageRolls` to improve chat damage previews

lang/en.json, less/v2/chat.less, module/applications/components/_module.mjs, module/applications/components/damage-application.mjs, module/documents/chat-message.mjs, module/documents/item.mjs, module/enrichers.mjs, templates/chat/item-card.hbs
Introduces a new `DamageApplicationElement` that is inserted into chat cards to handle applying damage to actors. It features two targeting modes, one that uses the tokens that were targeted when the damage was rolled and another that uses the currently selected tokens on the scene. For players the application will only display if one of their tokens was targeted by the damage. They will only see targeted selection mode and only the tokens of theirs that were targeted will be listed.
Each target lists the amount of damage calculated after resistances, immunities, and vulnerabilities are taken into account. Beneath that are a list of multiplier controls that appear for each target, make it easy to apply damage changes outside the automatic ones. Changes to the damage from these buttons is …
=> [#1015, #1372] Add damage application tray to chat cards

module/documents/actor/actor.mjs, module/documents/token.mjs
Closes #3035.
This adds the 'dnd5e.healActor' and 'dnd5e.damageActor' hooks (I don't feel strongly that pre-hooks are necessary).
An additional benefit is that this removes the odd dependencies on a "dhp" or "dtemp" property being passed along in updates to get scrolling damage/healing numbers; the event listeners simply take care of it, and the scrolling damage numbers will also display when damage is applied through the sheet, not just via the chatlog or other hardcoded methods.
=> [#3035] Remove various dependencies on "dhp" and "dtemp" properties and add damage/healing hooks

module/data/advancement/scale-value.mjs, module/utils.mjs
Closes #2918.
This adds a new property, `modifiers`, to dice scale values, intended for properties like `min2` or `r<3`.
Using this ensures that scale values won't get pummeled into strings by appending such onto the scale value itself, or onto `.faces` or `.number`.
Adds the `dnd5e.utils.isValidDiceModifier` method, and the `denom` and `mods` getters to dice scale values.
=> [#2918] Add modifiers Set to dice scale values

lang/en.json, less/v2/chat.less, module/applications/components/damage-application.mjs, module/documents/actor/actor.mjs
Displays what resistances, immunities, vulnerabilities, and modifications are modifying the damage to be applied. Each of these can be clicked on to ignore that source of change or, if it is an immunity, downgrade it. The total damage that will be applied is updated as you click these buttons just like the multiplier buttons below.
Closes #1372
=> [#1372] Add display of resistances, etc. in damage application

module/documents/actor/actor.mjs
Creates chat message prompting for concentration whenever damage it taken and an actor is concentrating.
Splits out the DC calculating into a separate method in case a module wants to tweak it.
=> [#3028] Prompt for concentration save when damage is taken

module/applications/actor/character-sheet-2.mjs, module/config.mjs
We already have *diseased* as a condition even though it technically isn't one so that it shows up nicely under *Condition Immunities* for paladins and monks. So we might as well add some of the other non-RAW conditions, I think. Probably controversial.
- Bleeding: Perhaps useful considering there's blood magic that is only able to target creatures with blood.
- Cursed: I couldn't find a creature that is immune against curses, but it might be possible, not sure.
- Silenced: If you can be immune against blinded and deafened, I imagine you could possibly be immune against being silenced.
- Surprised: Some creatures are immune to being surprised unless incapacitated (e.g. Canoloth). There's also the Helm of Awareness (Artificer Infusion).
- Transformed: Some creatures are immune to any spell …
=> Add bleeding, cursed, silenced, surprised, and transformed to conditions

dnd5e.mjs
Closes #3153.
Moved `_configureTrackableAttributes` as well as `_configureConsumableAttributes` and `_configureStatusEffects` for good measure to the `setup` hook to allow modules to update `CONFIG.DND5E` on `init` before these are generated. Saves having to update these objects as they'd most likely need to be rebuilt or looped through to remove attributes that no longer exist in the config.
=> Move trackable attributes to setup

lang/en.json, less/v2/chat.less, module/documents/chat-message.mjs
Related to #2892.
- Prevent damage context menu options in roll types that are not damage. (If a message has no roll type, nothing is changed.)
- Add context menu options for selecting hit or missed targets in attack roll messages.
- Sort the targets of an attack roll by hit first, then misses.
- Add hover-in, hover-out, and click event handlers for the targeted tokens in attack roll messages. (With visible inspiration from `CombatTracker`.)
=> [#2892] Quality of life changes to attack/damage roll messages

lang/en.json, module/documents/actor/actor.mjs, module/documents/item.mjs, module/settings.mjs
Closes #3038.
When enabled, removing concentration from the AbilityUseDialog and not causing any prompts for conc saves seems more than sufficient.
=> [#3038] Add setting to disable concentration

module/canvas/_module.mjs, module/canvas/token-placement.mjs, module/data/item/fields/summons-field.mjs
The `TokenPlacement` class right now is small and only delegates to the `TokenPlacementTemplate` which is responsible for rendering and returning placement information. With the V12 improvements to placeables hopefully we'll be able to shift more logic out of the `MeasuredTemplate` subclass and into the `TokenPlacement` class.
The `TokenPlacementConfiguration` data structure currently just includes the prototype token information, but will eventually have quantity, origin, and range values to handle multiple summons and restricting range from the summoner.
Works with tokens of any size or scale on the square grid. On hex grids, it handles 1x1 tokens pretty good with only a bit of offset on the final token placement. Stranger token sizes lead to some issues with positioning, but I'm not …
=> [#893] Add system for selecting summoning placement

module/applications/item/ability-use-dialog.mjs
An empty string is considered non-null and wont be coalesced.
=> Corrects default summon label

module/documents/item.mjs, packs/_source/spells/1st-level/magic-missile.json
Fix spell scaling from checking a property that doesn't exist. Also adjusts Magic Missile to not have spell scaling so it doesn't upcast incorrectly.
=> [#3311] Fix bug with rolling upcast damage, fix Magic Missile scaling

module/data/fields.mjs
Can go in 3.1.2 or 3.2, whichever you have a better feeling for.
This was a change we made in core to allow `DataField`s to recursively apply their own migrations/cleaning, and I never followed-up in the dnd5e repo. These `migrateSource` changes are in v11, it's not just a v12 thing, for the avoidance of doubt.
=> Reinstate advancement data cleaning and ensure migrations are run before cleaning.

module/config.mjs, module/data/item/equipment.mjs
Removed Armor check from validProperties for stealthDisadvantage for equipment.
This allows all equipment to be marked with stealthDisadvantage.
Closes #3098
=> #3098 Removed armor check for Stealth Disadvantage

module/data/item/spell.mjs
Adds spell components to spell listing:
Also considered adding the full names, but that felt a bit long:
Closes #3269
=> [#3269] Add spell components back to chat cards

module/dice/simplify-roll-formula.mjs
=> [#3263] Preserve dice modifiers when simplifying formulas

less/v2/apps.less, less/v2/chat.less, module/config.mjs
- Moved object fit styles to common gold-icon class.
- Fixed necrotic SVG path.
- Bumped up damage icons in application tray from 11px to 13px.
=> Miscellaneous CSS tweaks

module/applications/actor/base-sheet.mjs, module/applications/actor/character-sheet-2.mjs, module/config.mjs
- Closes #3375 
This is a simple quality of life change for any spell preparation mode, allowing them to toggle whether a spell is prepared or not on the actor sheet.
Only remaining issue beyond this is that there is no way to set a spell as 'always prepared' as this is always implied to be a type of regular 'leveled' spell but that is a much larger undertaking than this PR would deal with.
=> Use the CONFIG to determine (or override) whether a spell preparation mode prepares or simply knows its spells

module/documents/item.mjs, module/enrichers.mjs, module/utils.mjs
Moves the logic that `Item5e` uses for selecting roll targets into a utility method and adjusts enricher rolls to iterate over targets instead of only applying to the first. This change applies to all enricher rolls except damage, where it doesn't make sense.
Closes #3354
=> [#3354] Allow enricher rolls to target multiple actors

module/config.mjs, module/documents/item.mjs, packs/_source/rules/appendix-e-rules.json, packs/_source/rules/chapter-11-dm-tools.json
Adds a configuration object that is passed to `createScrollFromSpell` to allow for more customization of the creation process. Right now it has a single option `explanation` which controls how much of the spell scroll rules are included in the created scroll.
- `full`: Existing functionality including entire spell scroll rules
- `reference`: Adds scroll level, reference link to rules, and potentially a concentration note to beginning of description
- `none`: Just includes the original spell description
In order to support `reference` mod a non-level-specific version of the spell scroll rules have been added to the magic items section of the SRD rules and a reference of `&Reference[Spell Scroll]`.
Closes #3326
=> [#3326] Add option to create spell scrolls with reduced description

dnd5e.mjs, lang/en.json, module/applications/components/inventory.mjs, module/documents/item.mjs
Adds context menu options to the sidebar directory and compendium listing that will create a new scroll in the sidebar, and to the actor's inventory that will create a new scroll on the actor.
Closes #3320
=> [#3320] Add option to convert spell to scroll from context menu

module/documents/item.mjs
The `SpellScrollConfiguration` object now has a `level` parameter that causes the created spell scroll to include a spell at a higher level than normal. This stores the increase level information in `flags.dnd5e.spellLevel`, which contains the original leve, the casting level, and the scaling information.
`Item5e#rollDamage` has been modified to now check for the new flag before scaling damage, and use that information if present. The scaling information is stored in the flag because otherwise it would be lost when converting to a consumable type.
Closes #3321
=> [#3321] Allow spell scrolls to be created at increased level

lang/en.json, module/applications/actor/base-sheet.mjs, module/applications/actor/group-sheet.mjs, module/data/user/user-system-flags.mjs, module/documents/item.mjs, templates/apps/spell-scroll-dialog.hbs
Creating spell scrolls will now display a dialog with options for how much explanation & the level of the created scroll:
Saves the explanation setting in user preferences so it doesn't have to be set every time.
=> [#3320, #3321] Add configuration dialog for spell scroll creation

less/v1/items.less, module/applications/item/item-sheet.mjs, templates/items/parts/item-activation.hbs
Displays the list of hit dice consumption options for items not in an actor so they can be selected.
For attributes, changes the select dropdown to a text input so the attribute can be entered or modified manually for non-embedded items.
=> [#1856] Allows HD & attribute consumption to be set on world items

lang/en.json, less/v1/items.less, module/applications/item/ability-use-dialog.mjs, module/applications/item/summoning-config.mjs, module/data/item/fields/summons-field.mjs, module/documents/item.mjs, templates/apps/ability-use.hbs, templates/apps/summoning-config.hbs
Introduces a new `creatureTypes` set in summoning configuration that defines creature types that the summoned creature will be turned into upon summoning. If more than one type is listed, then the player will have the chance to choose that in the usage dialog.
Makes use of Foundry's new `<multi-select>` element for input.
This feature is necessary for spells like Find Familiar, Find Steed, & Find Greater Steed.
=> [#3242] Add ability to change creature type when summoning

lang/en.json, module/dice/damage-roll.mjs, module/enrichers.mjs
Allows for `[[/healing 2d6]]` and `[[/damage 2d6 healing]]` for normal healing and `[[/healing 2d4 temp]]` and `[[/damage 2d4 type=temphp]]` for temp HP.
Closes #3260
=> [#3260] Add healing enricher & healing types to damage enricher

less/v2/chat.less, less/variables.less, module/applications/components/damage-application.mjs, module/documents/actor/actor.mjs
Any damage rolls with the `temphp` type are now not included in the total damage and instead split off. Then, after any damage is applied to current & temporary HP, that temp value is used to set the new temporary HP floor.
The damage application interface has been adjusted to display temp HP separately from other changes. The display of normal damage has also changed to add subtle colors (red for damage, green for healing, blue for temp HP). The signs have also been adjusted, so healing will always have a "+", damage will always have a "-", and temp HP will be unsigned.
These changes should make it more clear what each of the numbers represents, but just in case this also adds tooltips to each number.
Closes #3358
=> [#3358] Properly handle temporary hit points in `applyDamage`

lang/en.json, less/v1/items.less, module/applications/item/item-sheet.mjs, module/data/abstract.mjs, module/data/item/consumable.mjs, module/data/item/equipment.mjs, module/data/item/feat.mjs, module/data/item/spell.mjs, module/data/item/templates/activated-effect.mjs, module/data/item/weapon.mjs, module/documents/actor/actor.mjs, module/documents/item.mjs, templates/items/parts/item-activation.hbs
Items with the consumption modes of ammo, item uses, and resource will now be display their target as a text input field which accepts an item UUID. When the item is then added to an actor, it will search for an item on the actor with a matching `sourceId` and set that item's ID as its consumption target. This should allow for pre-configuring consumption in compendium items.
Closes #1856 
Closes #3342
=> [#1856, #3342] Allow UUIDs to be used as consumption targets

lang/en.json, module/applications/actor/short-rest.mjs, module/config.mjs, module/data/actor/npc.mjs, module/documents/actor/actor.mjs, module/documents/advancement/hit-points.mjs
Calculates the hit dice max and denomination based on a NPC's HP formula with a fallback based on their size if necessary. On NPCs `HitPointAdvancement` will now determine the die size based on the NPC's hit die denomination rather than what is specified in the class.
Adjust the `Actor#rollHitDie` method to be able to handle rolling hit dice on NPCs and the resting methods to be able to properly recover NPC hit dice.
Closes #3353
Closes #3361 
Closes #3362
=> [#3353, #3361, #3362] Add support for NPC hit dice based on HP formula

lang/en.json, module/applications/advancement/item-choice-flow.mjs, module/data/item/feat.mjs, templates/items/feat.hbs
Adds a new `prerequisites.level` field to feature items which indicates which class or character level at which the item can be taken.
This data is then used by `ItemChoiceAdvancement` to only display or support drops from features if their meet the level requirement.
Closes #1833
=> [#1833] Add level prerequisite to feature items used by item choice

lang/en.json, module/applications/actor/group-sheet.mjs, module/canvas/token-placement.mjs, module/data/actor/group.mjs, module/data/item/fields/summons-field.mjs, templates/actors/tabs/group-members.hbs
Includes modifications to the `TokenPlacement` class to fully support multiple token placements. The functionality of that system has been changed slightly so right clicking will now skip the current placement, but not cancel the whole process. This should allow skipping certain group members when placing the group.
There is a current limitation that prevents the already placed tokens from displaying in the scene.
Closes #3345
=> [#3345] Add Place Members buttons to group to place into scene

packs/_source/monsters/summons/_folder.json, packs/_source/monsters/summons/arcane-eye.json, packs/_source/monsters/summons/arcane-hand.json, packs/_source/monsters/summons/arcane-sword.json, packs/_source/monsters/summons/mage-hand.json, packs/_source/monsters/summons/unseen-servant.json, packs/_source/spells/1st-level/unseen-servant.json, packs/_source/spells/4th-level/arcane-eye.json, packs/_source/spells/5th-level/arcane-hand.json, packs/_source/spells/7th-level/arcane-sword.json, packs/_source/spells/cantrip/mage-hand.json
Adds new "Summons" folder to the monsters compendium and adds them to these spells:
- Arcane Eye
- Arcane Hand (has an issue with grasping hand damage, needs to get the spellcasting modifier added to its damage but that isn't possible at the moment)
- Arcane Sword
- Mage Hand
- Unseen Servant
=> Add more SRD summoning spells

module/applications/actor/character-sheet-2.mjs, module/applications/actor/hit-dice-config.mjs, module/applications/actor/short-rest.mjs, module/applications/item/ability-use-dialog.mjs, module/data/actor/character.mjs, module/documents/_module.mjs, module/documents/actor/HitDice.mjs, module/documents/actor/actor.mjs, templates/actors/character-sheet.hbs
Redo of #2519.
Closes #2100.
Closes #1074.
Saves people from https://github.com/foundryvtt/dnd5e/issues/2100#issuecomment-1986962845.
This moves most hit dice related logic into a single class, which simplifies a lot of code throughout.
=> [#2100] Implement HitDice helper class

lang/en.json, less/v1/items.less, module/applications/item/ability-use-dialog.mjs, module/applications/item/summoning-config.mjs, module/data/item/fields/summons-field.mjs, module/documents/item.mjs, templates/apps/ability-use.hbs, templates/apps/summoning-config.hbs
Similar to the recent change adding selection of creature types during summoning, this adds creature size to the options. When a size is selected both the actor details and the token will be adjusted to the appropriate size.
Closes #3412
=> [#3412] Allow specifying creature size during summoning

lang/en.json, less/v1/items.less, less/v2/apps.less, less/v2/chat.less, module/applications/item/ability-use-dialog.mjs, module/applications/item/summoning-config.mjs, module/data/item/fields/summons-field.mjs, templates/apps/summoning-config.hbs
Adds a minimum and maximum level to each summoning profile hidden beneath an "Additional Settings" tray. These values determine whether the profile will be visible for a given spell, character, or class level.
For summoning on a spell item, it will always use the spell's level. On all other items it uses the character level by default unless a class identifier is entered, in which case it will use that class's level.
The ability use dialog has been updated to dynamically refresh the list of summoning profiles as the casting level is changed.
=> [#3242] Add level limits to summoning profiles

module/dice/damage-roll.mjs
There was an issue where the Powerful Critical was created by summing all the die faces times number, and adding a numerical term to the terms. 
It appears this was trying to add Powerful Critical as the type however due to a bug no flavor was getting added. This was modified to use a Map to sum all dice of matching types and add a Numeric term with matching flavor for each. 
This later allows the aggregate-damage-rolls.mjs's chunkTerms to aggerate the powerful critical rolls to their matching type as non flavored values are added to the default damage roll type. 
Closes #3176
=> [#3176] Powerful Critical Preserve flavor

lang/en.json, less/v1/items.less, module/applications/actor/base-config.mjs, module/applications/item/item-sheet.mjs, module/documents/active-effect.mjs, module/documents/actor/actor.mjs, module/documents/item.mjs, templates/items/consumable.hbs, templates/items/container.hbs, templates/items/equipment.hbs, templates/items/loot.hbs, templates/items/tool.hbs, templates/items/weapon.hbs
Active Effects created with `flags.dnd5e.type` of `enchantment` will now apply to the item in which they are included, not the actor.
The existing item sheets will now identify fields that have been modified by an enchantment effect and disable them, similar to how field are disabled in actor configs.
=> [#3374] Add enchantment active effect that modifies an item

lang/en.json, module/applications/components/effects.mjs, module/applications/item/item-sheet.mjs, module/config.mjs, module/data/abstract.mjs, module/data/item/consumable.mjs, module/data/item/container.mjs, module/data/item/equipment.mjs, module/data/item/loot.mjs, module/data/item/tool.mjs, module/data/item/weapon.mjs, module/documents/item.mjs, templates/items/parts/item-action.hbs, templates/shared/active-effects.hbs
Adds a new feature type "Enchantment" with sub-types matching the two existing enchantment types in class features: "Artificer Infusion" and "Rune". When this type is selected a new section appears in the effects tab for "Enchantments" that allows for creating a new enchantment active effect.
Two new sections are added for other items listing "Active" and "Inactive" enchantments to keep them separate from other effects.
Added a new metadata property to `ItemDataModel` for `enchantable`, which determines whether enchantment active effects will be applied to this item. Items that are not enchantable can still hold enchantment active effects but they will not be able to modify the item.
=> [#3374] Add enchantment feature type, improve effects tab

lang/en.json, less/v1/items.less, less/v2/apps.less, module/applications/components/effects.mjs, module/applications/item/enchantment-config.mjs, module/applications/item/item-sheet.mjs, module/config.mjs, module/data/item/_module.mjs, module/data/item/feat.mjs, module/data/item/fields/enchantment-field.mjs, module/data/item/fields/summons-field.mjs, module/data/item/spell.mjs, templates/apps/enchantment-config.hbs, templates/apps/summoning-config.hbs, templates/items/feat.hbs, templates/items/parts/item-action.hbs
Adds a new `EnchantmentData` embedded data model onto `feat` & `spell` items that contains configuration data for enchantments. This includes a number of helper methods to determine if an item represents an enchantment or enchantment source.
For enchantments, restrictions are added for whether the enchantment can be applied to magical items and what types of items it can apply to. There is also a `canEnchant` method that takes an item and determines whether it meets the required criteria.
For enchantment sources there is a formula for the maximum number of enchantments in effect at a time and the period at which enchanted items can be re-bound.
Closes #3418
=> [#3418] Add enchantment configuration & restrictions

module/data/item/weapon.mjs
Closes #3453.
To summarize finesse:
> When making an attack with a finesse weapon, you use your choice of your Strength or Dexterity modifier for the attack and damage rolls. You must use the same modifier for both rolls.
There is no mention of the weapon needing to be a melee weapon.
Two changes in this PR:
- Finesse properly applies to ranged weapons when the Strength is greater than the Dexterity modifier.
- The alternative ability modifier is only used if *strictly* greater, not if equal.
=> [#3453] Adjust how finesse is applied

module/applications/advancement/item-choice-flow.mjs
Fixes #3483.
Did a search for other uses of the prerequisites field, and the rest all appear to have the null-optional-chaining `?` on them
=> Allow for null/undefined prerequisites value in items when advancing

module/documents/actor/actor.mjs
Doesn't override a `active` object created during the `preCalculateDamage` hook and incorporates any multiplier into the auto-calculated multiplier.
Closes #3452
=> [#3452] Don't replace `damage.active` set in `preCalculateDamage`

lang/en.json, module/applications/advancement/ability-score-improvement-flow.mjs, module/applications/advancement/item-choice-flow.mjs
Uses the new level prerequisite data on feature items when adding a feat using the `AbilityScoreImprovementAdvancement`. This uses the overall character level rather than the specific class level.
=> [#1833] Check level restriction for feats in ASIAdvancement

less/v1/journal.less, module/applications/journal/spells-page-sheet.mjs, module/enrichers.mjs, templates/journal/page-spell-list-table.hbs, templates/journal/page-spell-list-view.hbs
Spell list journal pages can now be embedded. By default they display just like the normal spell list page without the "Grouping" selector. It uses the page's default grouping by default, but that can be changed using `[[/embed UUID grouping=alphabetical]]` to explicitly set the grouping.
There is also a `table` option with changes the display to show the spell list in a table grouped by level.
=> [#1787] Allow spell lists to be embedded

module/data/item/background.mjs, templates/items/background.hbs, templates/items/class.hbs, templates/items/race.hbs, templates/items/subclass.hbs
Adds `identifier` to the data for backgrounds so it can be set. Adds identifier input to the background and race sheets, which includes adding a new details tab to race sheets. Also added the identifier restrictions to the hint beneath each identifier input.
Closes #2597
=> [#2597] Add identifier field to background, add identifier input

module/applications/actor/character-sheet-2.mjs, module/applications/components/adopted-stylesheet-mixin.mjs, module/config.mjs, module/data/fields.mjs, module/data/item/container.mjs, module/data/item/equipment.mjs, module/data/item/spell.mjs, module/data/item/templates/activated-effect.mjs, module/data/item/templates/equippable-item.mjs, module/data/item/templates/identifiable.mjs, module/documents/active-effect.mjs, module/documents/actor/actor.mjs, module/documents/actor/trait.mjs, module/documents/token.mjs
This extends the deprecation period for `getBaseItem` indexes another 2 versions because fixing this requires a compendium migration and there are still people who haven't done that.
=> Remove features whose deprecation period ends with `3.2`

lang/en.json, module/applications/item/ability-use-dialog.mjs, module/data/item/fields/summons-field.mjs, templates/apps/summoning-config.hbs
Adds summoning count formulas to summons profiles which allow specifying how many creatures are summoned, modifiable based on spell level or any other calculations required.
The ability use dialog has been updated to display how many of each profile will be summoned and will update dynamically when the spell level is changed.
=> [#3242] Support summoning more than one creature at a time

less/v2/inventory.less, templates/actors/tabs/character-features.hbs, templates/actors/tabs/character-spells.hbs
Adds the uses as the first column on the player's spellbook tab. These uses only display when the spellbook is wide enough and are editable like in the features tab.
If the sheet it too narrow, then the uses are instead displayed in the spell's subtitle alongside and required components. In the narrow mode they are not editable.
Closes #2773
=> [#2773] Display limited spell uses on sheet

packs/_source/monsters/summons/arcane-eye.json, packs/_source/monsters/summons/arcane-hand.json, packs/_source/monsters/summons/arcane-sword.json, packs/_source/monsters/summons/dancing-lights-medium.json, packs/_source/monsters/summons/dancing-lights-tiny.json, packs/_source/monsters/summons/mage-hand.json, packs/_source/spells/4th-level/giant-insect.json, packs/_source/spells/6th-level/create-undead.json, packs/_source/spells/cantrip/dancing-lights.json
Sets up summoning for three more SRD spells. For dancing lights, this adds two actors for whether you decide to have your lights split into 4 or in a single blob.
=> [#3242] Setup Giant Insect, Create Undead, & Dancing Lights summons

lang/en.json, less/v1/journal.less, module/applications/journal/spells-page-sheet.mjs, module/applications/journal/spells-unlinked-config.mjs, module/data/journal/spells.mjs, module/data/shared/source-field.mjs, module/utils.mjs, templates/journal/page-spell-list-edit.hbs, templates/journal/page-spell-list-unlinked-config.hbs, templates/journal/page-spell-list-view.hbs
Adds a new `unlinkedSpells` array to spell list journal pages for holding information on spells that may potentially become unlinked. This is useful for when a spell list might need to include spells that aren't in the current module or in the SRD.
In order to properly display, this data structure contains the name of the spell, its level, and its school. It also contains the source object for tracking where the spell originated. This source object can contain a UUID so if the module that contains the spell is active it will display linked like the rest, but if the module is inactive then it will display as a static entry.
=> [#1787] Support potentially unlinked spells in spell lists

module/tooltips.mjs
Seems to be working for all cases I tested, but I'm not sure if there is some case that the original positioning code was written for that the normal core code doesn't take into account.
Closes #3071
=> [#3071] Fix rendering issues with UP & DOWN item tooltips

module/applications/actor/character-sheet.mjs, module/data/abstract.mjs, module/data/item/consumable.mjs, module/data/item/container.mjs, module/data/item/equipment.mjs, module/data/item/loot.mjs, module/data/item/tool.mjs, module/data/item/weapon.mjs
Adds `inventoryItem` to metadata for item data models that allows them to automatically be listed in the inventory tab, as opposed to the former hard-coded list of types.
=> [#3500] Allow module item types to appear in inventory

module/data/actor/character.mjs, module/data/actor/templates/creature.mjs
Moved the getRollData method, which retrieved the class and subclass, from character to creature, which is inherited by both character and npc.
Closes #3475
=> [#3475] Moved getRollData method from character to creature

lang/en.json, module/applications/components/effects.mjs, module/applications/item/enchantment-config.mjs, module/applications/item/item-sheet.mjs, module/data/item/feat.mjs, module/data/item/fields/enchantment-field.mjs, module/data/item/spell.mjs, module/data/item/templates/action.mjs, module/documents/active-effect.mjs, module/documents/item.mjs, templates/items/parts/item-action.hbs
When adding an enchantment to an item that accepts enchantments, the restrictions specified in the enchantment source will now be enforced. It will also prevent the creation of an enchantment effect directly on an actor.
Enchanted items in the world will register themselves with a static registry of all enchanted items so the enchantment items can easily determine what items they have enchanted.
Support has been added for items that might offer enchantments or receive them (to support a weapon that can enchant other weapons for example). This uses the `origin` data to track whether the enchantment effect is applied to the item or not. To this end the default origin for new enchantments isn't set like for normal effets. The origin is only set when an enchantment is dragged to another item. …
=> [#3305] Enforce enchantment restrictions when dropping onto item

dnd5e.mjs, module/applications/actor/group-sheet.mjs, module/applications/actor/hit-dice-config.mjs, module/applications/actor/vehicle-sheet.mjs, module/applications/advancement/ability-score-improvement-flow.mjs, module/applications/award.mjs, module/applications/components/inventory.mjs, module/applications/item/ability-use-dialog.mjs, module/canvas/token.mjs, module/data/actor/character.mjs, module/data/actor/templates/attributes.mjs, module/data/item/container.mjs, module/documents/active-effect.mjs, module/documents/actor/actor.mjs, module/documents/actor/hit-dice.mjs
Moves the monkey patching of `measureDistances` on canvas behind a V12 check because this isn't needed anymore.
Replaces all uses of `Math.clamped` with `Math.clamp` and registers an alias in V11 to keep everything working. This avoids a bunch of deprecation warnings that weren't being properly suppressed and gets us ahead on the work when we go V12-only.
Closes #3516
=> [#3516] Fix SquareGrid & clamped deprecation warnings

module/config.mjs, module/documents/active-effect.mjs
Closes #3498.
Adds a `riders` property for add-on conditions that should be applied separately.
=> [#3498] Add prone separately for sleeping/unconscious

module/documents/active-effect.mjs
Adds the option when apply and OVERRIDE change to a string value to include the original string value by using `{{}}`. So an effect with the change value of `Enhanced {{}}, +1` might be interpolated as `Enhanced Breastplate, +1` when applied.
Closes #3426
=> [#3426] Add simple string interpolation to active effects

less/v2/dark/character.less
Added .content-link to dark/character.less
Sets the background to dnd5e-color-dark-gray and the boarder to dnd5e-border-dark predefined values. 
Closes #3380
=> [#3380] Added .content-link to dark/character.less

lang/en.json, less/v2/chat.less, module/applications/components/_module.mjs, module/applications/components/enchantment-application.mjs, module/applications/item/ability-use-dialog.mjs, module/applications/item/enchantment-config.mjs, module/data/item/fields/enchantment-field.mjs, module/documents/active-effect.mjs, module/documents/chat-message.mjs, module/documents/item.mjs, templates/apps/ability-use.hbs, templates/items/parts/item-action.hbs
Introduces enchantment to the `AbilityUseDialog` using the `applyEnchantment` and `enchantmentProfile` options, with similar details to how summoning is handled.
When enchantment is performed it adds a new "Enchant" tray to chat cards. This tray has a place to drop an item which is then enchanted when the apply button is pressed.
Enchantments are tracked with concentration, so if concentration on the enchanting spell ends then the enchantments will be removed.
=> [#3305] Add enchantment usage dialog & application tray

lang/en.json, module/applications/item/ability-use-dialog.mjs, module/applications/item/enchantment-config.mjs, module/data/item/fields/enchantment-field.mjs, module/documents/item.mjs, templates/apps/ability-use.hbs, templates/apps/enchantment-config.hbs, templates/apps/summoning-config.hbs
Adds `min` and `max` level limits as flags to the enchantment effects that are used to limit when those enchantments appear. This is based off spell level if it is a spell, or either character or class level for other items depending on whether a class identifier is provided.
If the "Enchantment Prompt" option is not checked, then the system will take level restrictions into account when selecting which enchantment to provide. This should make it easy to configure a feature like "Enhanced Defense" artificer infusion which swaps enchantments depending on artifier level, without requiring the player to view the ability use dialog everytime they want to use the infusion.
Closes #3512
=> [#3512] Allow enchantments to be limited by level

module/data/item/fields/summons-field.mjs
Simply adds the `@mod` value from the summoning item to be used as `@flags.dnd5e.summon.mod` on the summoned creature.
Closes #3534
=> [#3534] Add summoner modifier into summoned flags

module/applications/actor/character-sheet.mjs, module/data/abstract.mjs, module/data/item/consumable.mjs, module/data/item/container.mjs, module/data/item/equipment.mjs, module/data/item/loot.mjs, module/data/item/tool.mjs, module/data/item/weapon.mjs
Introduces a new `inventoryOrder` metadata property that is used to specify which order inventory categories will appear. This value will only be used if `inventoryItem` is also set in the metadata. If not specified, category will be sorted to the end of the list.
=> [#3500] Allow ordering of inventory categories to be set

module/data/item/fields/summons-field.mjs, module/documents/actor/actor.mjs, module/documents/item.mjs, module/documents/token.mjs
Similar to what is implemented for Enchantments, this introduces a static registry within `SummonsData` where each summoned actor can register to make it easy to determine what creatures each actor or item have summoned.
Adds `SummonsData#summonedCreatures` which returns what creatures were summoned by that item, and `Actor5e#summonedCreatures` getter which returns all creatures summoned by that actor.
Also fixes a bug where sometimes `flags.dnd5e.summons.origin` wouldn't get the proper UUID for summons created using the chat message button.
=> [#3544] Add static registry of summoned creatures in world

lang/en.json, module/applications/components/chat-tray-element.mjs, module/applications/components/damage-application.mjs, module/documents/chat-message.mjs, module/settings.mjs
Adds a new setting allowing setting the initial expanded state of damage & effect application trays in chat cards. The settings are "Expand All" and "Collapse All" plus "Collapse Older", which expands newly created cards but collapses any cards more than five minutes old.
To better support the expanding trays, a new CardTrayElement has been added which adds support for the `open` attribute on card trays to explicitly control its behavior. This attribute matches the behavior of the `open` attribute on `<details>` elements, so adding or removing the attribute will open and close the tray, and toggling the `open` property will cause the attribute to be added or removed. The tray also fires off a `toggle` event that matches the one fired by `<details>`.
=> [#3291] Add setting to control chat card tray expansion

module/applications/actor/character-sheet-2.mjs, module/config.mjs
Takes advantage of the existing `CONFIG.DND5E.sourcePacks` object to define packs for backgrounds, classes, and races.
Closes #2780
=> [#2780] Allow default concept compendiums to be defined

module/config.mjs
The metrics values have never been correct since the system was released. Here they are with the correct values.
Translations of books using the metrics system use a simplified version of the conversion, 2.5 for 5, for simplicity.
Close : https://github.com/foundryvtt/dnd5e/issues/3257 - https://github.com/foundryvtt/dnd5e/issues/1226 - https://github.com/foundryvtt/dnd5e/issues/1228
=> Update metrics values

lang/en.json, module/applications/item/enchantment-config.mjs, module/documents/active-effect.mjs, module/documents/item.mjs, templates/apps/enchantment-config.hbs
Enchantments can now define one or more effects that will be added whenever the enchantment is added and removed when the enchantment is removed. These are configured in the enchantment config.
In order to prevent any effects used as ride along effects from being transfered to the actor when not necessary, they get the `rideAlong` flag which is removed when applied. This prevents these effects from being transfered to the actor or being offered in the chat card. This separate flag allows for transfer and non-transfer ride along effects.
Closes #3511
=> [#3511] Add additional effects that ride along with enchantments

lang/en.json, less/v1/items.less, module/applications/actor/vehicle-sheet.mjs, module/config.mjs, module/data/item/container.mjs, module/data/item/templates/physical-item.mjs, module/documents/actor/actor.mjs, module/utils.mjs, templates/items/parts/item-description.hbs, templates/shared/inventory.hbs
Item weights now define a specific unit which will make it possible to have a mixture of imperial and metric object weights, as well as represent large items in vehicle inventories. Defines these weights along with a conversion method in `CONFIG.weightUnits`.
Closes #1909
=> [#1909] Add units to item weight & properly convert for calculating encumbrance

less/v2/dark/character.less
In dark/character.less:
Added a ids under .roll-link
Added a ids under .reference-link
Added .inline-roll
Added .award-link
To .content-link added in #3531
Closes #3533
Tested with
@UUID[Actor.PU5J4XCoeTeIViCA]{Newer}
[[/save dex]]
[[/r 5d20]]
[[/check dexterity athletics]]
[[/tool thief dex]]
[[/damage formula=2d6 type=fire]]
[[lookup @details.type.config.label]]
&Reference[prone]
[[/award 50gp 50xp]]
=> [#3533]Added multiple enricher type classes to dark/character.less

module/data/abstract.mjs, module/data/item/templates/activated-effect.mjs, module/documents/item.mjs, module/utils.mjs, templates/items/parts/item-activation.hbs
Converts the targets value into a formula field so spells can change their values as they upcast. In order to support this and reduce code duplication the formula resolution logic used by max uses & duration fields was moved into its own method. All of the activated effect template data preparation was also moved into the data model at the same time.
In order to ensure these formulas resolve properly using item data for non-embedded items (Bless should show targets even when not on an actor), this modifies `getRollData` to always return item data even for non-embedded items.
In addition, the `replaceFormulaData` method has been moved from `Item5e` into utils to make it more generally available.
Closes #3537
=> [#2094, #3537] Convert target value into formula, move prep logic

lang/en.json, module/data/item/fields/enchantment-field.mjs, module/documents/item.mjs, templates/apps/ability-use.hbs, templates/items/parts/item-action.hbs
Unchecking "Enchant Prompt" is useful when there is only a single enchantment available at any given time to help players to avoid seeing the ability use dialog if no other configuration is required, but if the dialog is shown then it requires the player to click "Apply Enchantment" or else the enchantment area won't appear in chat. For a more streamlined approach it would probably be simpler to just remove that checkbox so the enchantment area is always shown in chat if there is enchantments available. In this case the ability use dialog is only necessary when there is more than one enchantment profile to select.
=> [#3305] Allow "Enchant Prompt" to still enchant if prompt is shown

lang/en.json, module/applications/actor/base-sheet.mjs, module/applications/actor/character-sheet-2.mjs, module/applications/actor/character-sheet.mjs, module/applications/components/inventory.mjs, module/config.mjs, module/data/actor/character.mjs, module/data/actor/npc.mjs, module/data/item/consumable.mjs, module/data/item/container.mjs, module/data/item/equipment.mjs, module/data/item/templates/equippable-item.mjs, module/data/item/tool.mjs, module/data/item/weapon.mjs, module/documents/item.mjs, templates/items/consumable.hbs, templates/items/equipment.hbs, templates/items/tool.hbs, templates/items/weapon.hbs
Splits `system.attunement` into two values, `attunement` which takes a string to indicate what kind of attunement is required, and `attuned` which is a `boolean` indicating whether the item is currently attuned.
This change allows simplification of a lot of the logic for attuning/un-attuning and for resetting attunement for dropped items.
This also adds the "Optional Attunement" mode that is used for the Spell Gem items and some 3rd party content. If attunement is optional then active effects and magical bonuses won't be suppressed if the item isn't attuned.
Also fixes a bug causing `_prepareItems` from being called twice on the new character sheets.
Closes #2111
Closes #3551
=> [#2111, #3551] Split attunement & attuned, add optional attunement

module/data/actor/character.mjs, module/data/actor/npc.mjs, module/data/actor/templates/attributes.mjs
I noticed in certain cases we currently end up with prepared `null` range/units instead of `0`/`"ft"`.
=> Fix preparation of movement/senses ranges and units

templates/actors/group-sheet.hbs, templates/actors/tabs/group-members.hbs
Makes the award button available even when XP tracking is disabled.
=> [#3565] Move Award button to group actor control bar

lang/en.json, module/applications/item/item-sheet.mjs, templates/items/parts/item-action.hbs
Displays a list of creatures summoned by an item on its details tab similar to how enchantments are displayed. Currently the only control is to view the actor because un-summoning is yet to be implemented.
=> [#3544] Add summoned creature list of item details tab

module/data/actor/character.mjs, module/data/actor/npc.mjs, module/data/actor/templates/attributes.mjs, module/data/actor/vehicle.mjs, module/documents/active-effect.mjs, module/documents/actor/actor.mjs
Moves the encumbrance calculation logic into `AttributesFields` to be called by individual data models.
Also adds bonuses and multiplier fields that can be used to modify encumbrance in a more fine-grained level using active effects. There are formulas targeting the three encumbrance thresholds and one that applies to all three thresholds.
Closes #3259
=> [#2111, #3259] Move encumbrance calcs & add multipliers & bonuses

module/data/item/fields/summons-field.mjs
* Unlinked actor summoning remains the same.
* Linked actor summoning:
* additionally considers the `dnd5e.summon.origin` flag, which associates a given summoned actor instance with a specific item on a specific actor. 
* actor/item/effect changes are applied to the actor via standard CRUD operations instead of inserting directly into the token's `delta` field.
* Intended for use with 'permanent' summons/companions.
=> Summoning considerations for linked (e.g. unique) actors.

lang/en.json, less/elements.less, less/v2/apps.less, module/applications/item/enchantment-config.mjs, module/data/item/fields/enchantment-field.mjs, module/documents/active-effect.mjs, module/utils.mjs, templates/apps/enchantment-config.hbs
Adds rider items referenced by UUID that are added to a parent actor when one of their items is enchanted and removed when it is disenchanted.
Includes a backported version of `<document-tags>` from V12 as the interface for this to avoid having to implement something new.
=> [#3305] Add ability for enchantments to add rider items

module/data/item/fields/summons-field.mjs, module/documents/active-effect.mjs, module/documents/item.mjs
Rather than changing items on summoned actors directly, this now uses an enchantment with a fixed ID for those changes to ensure that it can be properly updated on re-summoning linked actors.
In order to get this to work on all actor types this removes the restriction on applying enchantments. Enchantments can still only be added manually to item types marked `enchantable`, but any enchantments created programatically on those items can be properly applied.
Closes #3444
=> [#3444] Re-implement summoned item modifications using enchantments

less/v2/character.less, less/v2/dark/character.less, module/applications/actor/character-sheet-2.mjs, module/config.mjs
There was an issue where a leading slash (/) was causing the url() css to use a absolute url path instead of a relative path. This worked without a routePrefix because the url path was the same if for both absolute and relative, however with a routePrefix we need to preserve the prefix, this was done by removing the leading slash for icons paths and in the case of a less defined url a leading ../../ was added to remove the /systems/dnd5e/ that would be added to the relative path.
Closes #3441
=> [#3441] Removed leading / on css url() and on icon in config.mjs

wiki/Modifying-Your-Game-with-Scripts.md, wiki/Roll-Formulas.md
=> Wiki updates for 3.2.x

module/documents/token.mjs
`TokenDocument#hasDynamicRing` is called in `TokenDocument#prepareData`. If `Token#hasDynamicRing` is used, the first time the `TokenDocument` is prepared before the canvas is ready, `TokenDocument#hasDynamicRing` is false. Also if the Token Ring is toggled, we'd probably probably lag behind because `Token#hasDynamicRing` doesn't become false immediately.
=> Don't call `Token#hasDynamicRing` in `TokenDocument#hasDynamicRing`

less/v1/items.less
* No line breaks on first column of roll table embeds
* 'caption-top' class ported from journal styling with alterations to more closely match surrounded text style
* 'no-tables' and 'no-secrets' class added for better control over rich embeds. Hides display of tables or secrets from the description of the embedded document.
For #3572 
Example using `@Embed[RollTable.XYZ classes="caption-top"]`
=> [#3572] Embed enricher styling for item sheets.

module/applications/advancement/advancement-manager.mjs
Prevents a bug with advancement when `details.race` is populated by the legacy string value rather than a race item.
Closes #3622
=> [#3622] Fix advancement when race uses legacy string value

module/data/item/consumable.mjs, module/data/item/container.mjs, module/data/item/equipment.mjs, module/data/item/templates/equippable-item.mjs, module/data/item/tool.mjs, module/data/item/weapon.mjs
Had to move the preparation of equipped data to the final step to ensure it is only called once after enchantments have been applied, otherwise it would set `attuned` to `false` before the enchantment changed `attunement` to `required`.
Closes #3616
=> [#3616] Fix attunement not being settable when attuned is set by enchantment

module/documents/active-effect.mjs, module/documents/actor/actor.mjs
Filters on `allApplicableEffects` rather than overriding the transfer value.
Closes #3635
=> [#3635] Fix unconfigurable transfer value after effect is made a rider

module/applications/actor/sheet-mixin.mjs, module/applications/source-config.mjs, module/data/abstract.mjs, module/data/item/fields/summons-field.mjs, module/utils.mjs, utils/packs.mjs
V12 has a compatibility lookup when accessing `sourceId` using `getFlag`, but there is a number of places in the codebase we are getting that property directly so that compatibility shim doesn't apply.
Closes #3650 
Closes #3651
=> [#3650, #3651] Fix references to `sourceId` in V12

module/applications/journal/class-page-sheet.mjs, module/enrichers.mjs, module/utils.mjs
Adds `draggable` attribute to content links created through embed citations and `linkForUuid` method when running V11 so they can be dragged.
Also modifies the class journal page to use `linkForUuid` rather than its own solution.
Closes #3604
=> [#3604] Fix non-draggable content links in V11

module/documents/combat.mjs
Fixes:
```
combat.mjs:20 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'refreshDynamicRing')
at Combat5e.nextTurn (combat.mjs:20:20)
at async CombatTracker5e._onCombatControl (foundry.js:90534:17)
```
=> Fix previous/next Combat turn causing an error if there are no combatants

module/applications/advancement/advancement-selection.mjs, module/config.mjs
Adds the `hidden` option to advancement configuration which hides that advancement type in the selection dialog.
Closes #3663
=> [#3663] Add option to hide advancement types from selection

less/v2/journal.less
Moves the styling for special blocks to allow them to be used on actor & item sheets as well as journals.
Closes #3078
=> [#3078] Allow special journal blocks to be used on other sheets

module/canvas/_module.mjs, module/canvas/map-location-control-icon.mjs, module/config.mjs
The font family for marker styles now uses the `fontFamily` param, rather than just `font`, so it will be properly used by the marker.
Adjusted drawing to have a separate `shadowColor` parameter rather than using `borderColor` so that different border colors can be used without affecting the shadow.
Closes #3707
=> [#3707] Fixes marker font, add shadow color, improve documentation

module/applications/item/ability-use-dialog.mjs
Properly adjusts the slot level when pact level is selected in the dropdown and creates an initial clone at the proper level before rendering the dialog for if a level other than the default is set.
Closes #3676
=> [#3676] Fix issue with summoning using pact slot not setting level

module/documents/actor/actor.mjs
Related core changes: https://github.com/foundryvtt/foundry-vtt/pull/2478
=> Don't display scrolling combat text if the token is secret

templates/actors/character-sheet-2.hbs
The parameter `level` was missing from the `aria-label="{{ localize "DND5E.LevelNumber" }}"` in Character Sheet v2
Close #3752
=> Add missing param level to Character Sheet aria-label string

lang/en.json, less/v2/compendium-browser.less, module/applications/actor/character-sheet-2.mjs, module/applications/compendium-browser.mjs, templates/compendium/browser-entry.hbs, templates/compendium/browser-footer.hbs, templates/compendium/browser-results.hbs
Adds a selection interface and API for making choices within the compendium browser and returning those results to another part of the application for further use. This uses the new API for the controls for adding race, background, and classes to a character sheet.
The Compendium Browser application options get a new `selection` object with the minimum and maximum number of items that can be selected. If either of these are defined then checkboxes appear in the results list and a new footer which displays the number of selected documents and contains the submit button.
To make this easy to interact with a pair of new factor methods have been added: `select` and `selectOne`. The `select` method takes the provided options and returns a set of UUIDs or `null` if no selection was made. The …
=> [#3730] Add selection system for choosing options from browser

module/canvas/map-location-control-icon.mjs, module/config.mjs, module/data/journal/map.mjs
Map location marker style now includes an option for configuring the map marker icon class, so it can now be completely replaced in a style if desired.
This also moves the marker rendering code into a separate method in `MapLocationControlIcon` to make it easier for sub-classing markers to replace the rendering while retaining the other helpful parts of the class.
Closes #3705
=> [#3705] Add option to completely replace map location page markers

module/documents/actor/actor.mjs
Perhaps there is a better place to handle this. Or perhaps we prevent toggling of statuses in the first place if the actor is immune against them: but that is a bit more tricky considering implicit statuses and also the fact that petrified adds poison and disease immunities.
=> Remove statuses that the actor is immune against

lang/en.json, less/v2/chat.less, module/applications/components/enchantment-application.mjs
Adds a small display beneath the enchantment area on chat cards that displays the number of items that can be enchanted and the number currently enchanted. The enchantment limit is based off the target field on the enchanting item and scales with spell level.
Closes #3647
=> [#3647] Display enchanted item count & limit on enchantment cards

wiki/Roll-Formulas.md
Updated from  #3817
Link: https://github.com/foundryvtt/dnd5e/wiki/Roll-Formulas#skills
Typo:
@skills.stl - Slight of Hand
Change:
@skills.slt - Sleight of Hand
----
The more correct way to contribute to the wiki not what was done before.
=> Sleight of Hand Typo in Roll Formulas

module/applications/advancement/advancement-config.mjs, module/applications/advancement/size-flow.mjs, module/applications/advancement/trait-flow.mjs, module/applications/journal/class-page-sheet.mjs, module/data/advancement/base-advancement.mjs, module/data/advancement/item-choice.mjs, module/data/advancement/size.mjs, module/data/advancement/trait.mjs, module/documents/advancement/trait.mjs, templates/advancement/ability-score-improvement-flow.hbs, templates/advancement/advancement-flow.hbs, templates/advancement/hit-points-flow.hbs, templates/advancement/item-choice-config.hbs, templates/advancement/item-choice-flow.hbs, templates/advancement/item-grant-flow.hbs, templates/advancement/parts/advancement-controls.hbs, templates/advancement/scale-value-flow.hbs, templates/advancement/size-config.hbs, templates/advancement/trait-config.hbs
Adds `hint` to the top-level advancement data and migrates any existing hints from within the configuration data. Now if hints are set for any advancement it will display in the flow window.
Closes #2728
=> [#2728] Add hint to all advancement types

lang/en.json, less/v1/items.less, less/v2/apps.less, module/applications/item/ability-use-dialog.mjs, module/applications/item/summoning-config.mjs, module/data/item/fields/summons-field.mjs, templates/apps/ability-use.hbs, templates/apps/summoning-config.hbs
Adds an alternate mode to summoning allowing for specifying CR and type of summoned creatures rather than a specific document link. This CR can be a single value or a formula so it can change with level.
This does not include the actual summoning functionality, since that will be dependent on the compendium browser.
=> [#3772] Add configuration for CR-based summoning mode

module/data/item/spell.mjs, module/documents/actor/actor.mjs, module/documents/item.mjs
Modifies `_typeAbilityMod` property on `SpellData` to first check the associated spellcasting class if specified on the spell before falling back to the global spellcasting ability.
Also made a change to `Item5e#getSaveDC` to first ask the item for its ability to use for the DC before falling back to the global spell DC.
Closes #3763
=> [#3763] Select spellcasting ability based on spell's associated class

lang/en.json, module/applications/components/checkbox.mjs, module/applications/item/ability-use-dialog.mjs, module/data/item/fields/summons-field.mjs
Uses the new compendium browser in V12 to enable summoning based on CR and creature type. For V11 the ability use dialog will display a warning indicating that this functionality only works on V12.
Fixes a bug in `<dnd5e-checkbox>` that prevented it from returning its value.
Closes #3772
=> [#3772] Implement summoning based on CR

less/v2/actors.less, less/v2/apps.less, module/applications/actor/sheet-v2-mixin.mjs, module/utils.mjs, templates/actors/character-sheet-2.hbs, templates/actors/npc-sheet-2.hbs, templates/actors/parts/actor-warnings-dialog.hbs
- Closes #3725 
I had to use a `<dialog>` here because `popover` is only available as of Chrome 114 and the latest v11 electron is Chrome 112.
=> [#3725] Add preparation warnings to v2 sheets.

lang/en.json, module/documents/chat-message.mjs, module/settings.mjs
=> [#3156] Add setting to show attack roll result (AC check) card to players

dnd5e.mjs, lang/en.json, module/applications/_module.mjs, module/applications/activity/_module.mjs, module/applications/activity/activity-sheet.mjs, module/applications/api/application.mjs, module/config.mjs, module/data/activity/base-activity.mjs, module/documents/activity/mixin.mjs, module/documents/activity/utility.mjs, module/documents/mixins/pseudo-document.mjs, templates/activity/activation.hbs, templates/activity/effect.hbs, templates/activity/identity.hbs, templates/activity/parts/activity-consumption.hbs, templates/activity/parts/activity-targeting.hbs, templates/activity/parts/activity-time.hbs, templates/shared/uses-recovery.hbs, templates/shared/uses-values.hbs
Adds a new ApplicationV2-based sheet for editing activities. This sheet is designed to work with the existing `UtilityActivity` and can be easily subclassed for other activty types.
Note: Due to the ongoing item sheet re-design, no work has been done to design this sheet to match the system design, only to get the underlying functionality and UX working.
The sheet consists of three primary tabs, the first of which is the Identity tab containing the activity name and icon. This tab will probably be eventually expanded to include a description and visibility settings once they are added.
The Activation tab contains the bulk of the details with three sub-tabs. The Time tab contains activation time and condition and the duration of the activity.
The Consumption tab contains a list of …
=> [#1964] Add basic activity configuration sheet

lang/en.json, module/applications/activity/activity-sheet.mjs, module/applications/item/item-sheet.mjs, module/config.mjs, module/data/activity/base-activity.mjs, module/data/shared/uses-field.mjs, module/documents/item.mjs, module/utils.mjs, templates/shared/uses-recovery.hbs
Adds full support for configuring attribute & material consumption including a list of targets when embedded. Also adjusts how item uses targest are displayed to list charges remaining or for a period in the same way as they are presented on the current item sheet.
Adds the recharge recovery period that displays a fixed list of recharge rolls (e.g. "Recharge 4–6") to select.
=> [#1964] Add attribute & material consumption & recharge recovery

lang/en.json, module/applications/activity/activity-sheet.mjs, module/data/activity/base-activity.mjs, module/documents/mixins/pseudo-document.mjs, templates/activity/effect.hbs, templates/activity/parts/activity-consumption.hbs, templates/activity/parts/activity-effects.hbs, templates/shared/uses-recovery.hbs
Adds list of effects for an activity to apply. These effects are stored as an array of objects with IDs in case the system needs something like level restrictions in the future (like with enchantments).
Configuring these applied effects is handled through the Effect tab of the activity sheet. There is a list of currently applied effects (unstyled currently) with controls for opening and deleting effects. There is a button for adding new effects directly rather than returning to the item sheet, and a `<multi-select>` allowing for effects that are already on the item to be selected.
=> [#1964] Add applied effects data to activities & sheet

lang/en.json, module/applications/activity/_module.mjs, module/applications/activity/utility-sheet.mjs, module/data/activity/_module.mjs, module/data/activity/utility-data.mjs, module/documents/activity/utility.mjs, templates/activity/utility-effect.hbs
Adds a rolling formula and name that can be rolled when a `UtilityActivity` is used, similar to the "Other Formula" field on items currently.
Closes #941
=> [#1964] Add arbitrary roll to `UtilityActivity`

module/canvas/ability-template.mjs, module/documents/activity/mixin.mjs, module/documents/mixins/pseudo-document.mjs
Adds a new `AbilityTemplate#fromActivity` method and deprecates the old `fromItem` method. This new method supports placing multiple templates at a time.
Also switches to using `getSnappedPoint` rather than the deprecated `getSnappedPosition` which has the added benefit of working properly on hex grids.
Closes #2349
=> [#1964, #2349] Allow placing templates from activities

dnd5e.mjs, lang/en.json, module/data/activity/base-activity.mjs, module/data/shared/uses-field.mjs, module/documents/activity/mixin.mjs, module/documents/activity/summon.mjs, templates/activity/parts/damage-parts.hbs, templates/activity/parts/summon-profiles.hbs
Adds a static `localize` method to activities which performs pre-localization tasks. During the `i18nInit` hook the system iterates over all activities and calls this method.
This method calls the normal `localizeDataModel` method on the activity itself and then calls `Activity#_localizeSchema` to localize any `SchemaField`s in arrays (this method is necessary because core's `localizeSchema` method is private).
=> [#1964] Add method to localize schemas in `ArrayField`s

module/dice/simplify-roll-formula.mjs
Occurs when a parenthetical term containing deterministic terms is used for a die quantity. Now detects a deterministic, but non-numerical number of die and further simplifies the expression for cleaner display.
Note: The actual roll and display of the roll in the chat log behaved as expected. This change affects the display of non-trivial roll formulas in sheet and other "display-only" summaries.
=> Corrected roll formula simplification for display purposes.

dnd5e.mjs, less/v1/advancement.less, module/applications/actor/sheet-mixin.mjs, module/canvas/token-placement.mjs, module/data/item/fields/summons-field.mjs, module/dice/aggregate-damage-rolls.mjs, module/dice/d20-roll.mjs, module/dice/damage-roll.mjs, module/dice/simplify-roll-formula.mjs, module/documents/actor/actor.mjs, module/documents/chat-message.mjs, module/documents/item.mjs, module/utils.mjs, templates/advancement/parts/advancement-controls.hbs
- Remove the silences warning on `foundry.dice.terms` and change references to avoid the globally namespaced terms
- Swam `{{filepicker}}` with `<file-picker>` in advancement config
- Change access of `flags.core.sourceId` with `_stats.compendiumSource`
- Swap from `getCenter` to `getCenterPoint` in `TokenPlacement`
=> Resolve additional deprecated issues with V12

wiki/Enchantment.md
Similar to the Active Effect Guide, add a section to the Enchantment wiki page to document the active effects. It has some common sections (i.e. Common Examples, Common Usage Examples, and Common Action Examples) plus sections for those item types that have other things in their data model an enchantment could realistically change. Not surprisingly, the Loot type doesn't have its own section since it doesn't have much to begin with and is covered by the Common Examples section.
There are some parts of the data model I decided to leave out since I didn't think they made sense to change in an enchantment or were very unlikely to be changed:
- `system.source`
- `system.type`
- `system.identified` and `unidentified`
- `system.quantity`, `weight`, `price`, and `rarity`
- `system.attunement`, …
=> Document the Enchantment active effects

lang/en.json, module/data/activity/attack-data.mjs, module/data/activity/base-activity.mjs, module/data/activity/damage-data.mjs, module/data/activity/enchant-data.mjs, module/data/activity/summon-data.mjs, module/data/item/consumable.mjs, module/data/item/equipment.mjs, module/data/item/feat.mjs, module/data/item/spell.mjs, module/data/item/templates/action.mjs, module/data/item/templates/activated-effect.mjs, module/data/item/templates/activities.mjs, module/data/item/templates/mountable.mjs, module/data/item/tool.mjs, module/data/item/weapon.mjs, module/data/shared/activation-field.mjs, module/data/shared/duration-field.mjs, module/data/shared/range-field.mjs, module/data/shared/target-field.mjs, module/documents/activity/mixin.mjs, templates/activity/parts/activity-identity.hbs, templates/activity/parts/attack-damage.hbs, templates/activity/parts/attack-details.hbs, templates/activity/parts/damage-damage.hbs
All of the item types in the system that mix in `ActivityTemplate` no longer use `ActionTemplate` or `ActivatedEffectTemplate`. To avoid breakages they now call `_applyActivityShims` which adds shims to all of the old properties from those templates where possible.
This PR also includes changes to `WeaponData` that includes base damage & versatile damage as well as changes to `SpellData` that includes activation, duration, range, and target objects.
A few additional data changes had to be made to due to gaps:
- `cover` and `crewed` have moved from `ActivatedEffectTemplate` to `MountableTemplate`
- `chatFlavor` has been added to all activities and is now used in the created chat messages
- Critical bonus formula has been added to attack & damage activities, and critical threshold has been …
=> [#1964] Remove Action & Activated Effect data & add shims

module/data/activity/attack-data.mjs, module/data/item/weapon.mjs
Migrates the first damage part on a weapon to its base damage and the versatile formula if present into the versatile damage. If `@mod` is included it will be automatically stripped because that will be added automatically for weapon's base damage, and the type isn't stored in the versatile damage object because it will also match the type of the base damage.
Modifies the initial advancement creation for `AttackActivity` to separate out the first damage part from the rest. The first damage part is kept to be the item's base damage while the rest are added to the activity.
=> [#1964] Migrate weapon base & versatile damage

module/data/activity/base-activity.mjs, module/data/item/spell.mjs
Performs minor migration on spell activation to rename `cost` to `value` and adds a shim for the old value.
Also migrates the old target data to the new format with several shims to support accessing the old values as best as possible.
Modifies the initial advancement creation to avoid populating these values on the created activity if the item type is a spell.
=> [#1964] Migrate spell activation & target

less/v2/actors.less, less/v2/apps.less, less/v2/items.less, module/applications/actor/sheet-v2-mixin.mjs, module/applications/item/sheet-v2-mixin.mjs, module/applications/mixins/sheet-v2-mixin.mjs
- Closes #3893 
This also fixes the error thrown when clicking certain header buttons sometimes, by shifting to the `.pseudo-header-button` class for header buttons that are added but don't exist in the `_getHeaderButtons` data.
=> Item Sheet V2: Add equipped/identified toggles

lang/en.json, module/applications/activity/activity-sheet.mjs, module/config.mjs, module/data/activity/base-activity.mjs, module/data/item/spell.mjs, module/data/item/templates/activities.mjs, module/data/item/weapon.mjs, module/data/shared/activation-field.mjs, module/data/shared/duration-field.mjs, module/data/shared/range-field.mjs, module/data/shared/target-field.mjs, module/data/shared/uses-field.mjs, module/documents/activity/mixin.mjs, module/utils.mjs, templates/activity/parts/activity-consumption.hbs, templates/activity/parts/activity-targeting.hbs, templates/activity/parts/activity-time.hbs
Implements that final formula resolution and other preparation for duration, range, and target fields on spells and activities, and in the uses field everywhere. Some behavior previously implemented in `ActivatedEffectTemplate` to resolve formulas is now in the new `prepareFormulaValue` utility function.
This also re-implements the label generation previously handled in `ActivatedEffectTemplate` for spells and weapons.
=> [#1964] Prepare final formulas and labels

lang/en.json, module/applications/activity/activity-sheet.mjs, module/data/activity/base-activity.mjs, module/data/item/spell.mjs, templates/activity/parts/activity-targeting.hbs, templates/activity/parts/activity-time.hbs
During activity preparation this copies data from the item over to the activity unless the `override` option is set. If the original data couldn't be found on the item, then the override checkbox won't appear and the activity values will be used.
After the copying occurs a copy of the activity data is saved in `_inferredSource` so that the activity sheet has a way to show inferred data before any final formula resolution occurs.
The sheet then selects the item data or activity data based on the override checkbox, and if override isn't set it will disable the whole `<fieldset>`.
=> [#1964] Copy inferred data from items to activity, add overrides

lang/en.json, less/v2/forms.less, module/applications/activity/activity-sheet.mjs, module/applications/activity/attack-sheet.mjs, module/config.mjs, module/data/abstract.mjs, module/data/activity/attack-data.mjs, module/data/item/spell.mjs, module/data/item/weapon.mjs, module/documents/item.mjs, templates/activity/parts/damage-part.hbs, templates/activity/parts/damage-parts.hbs, templates/activity/parts/save-damage.hbs, templates/activity/parts/save-details.hbs
Infers attack type & classification from the containing item and displays a label indicating the inferred value if no overriding value is specific on the `AttackActivity`. Also displays the potential ability options that might be used for the attack.
When base damage is included, this adds the weapon's base damage to the list of parts but disables its form elements, so users can view the weapon's damage on the activity sheet.
Also fixed a bug on the `SaveSheet` causing the incorrect DC calculation value to be displayed.
=> [#1964] Add inferred attack data, fix bug in save sheet

lang/en.json, module/applications/activity/attack-sheet.mjs, module/data/activity/attack-data.mjs, module/data/activity/base-activity.mjs, module/data/activity/damage-data.mjs, module/data/activity/heal-data.mjs, module/data/activity/save-data.mjs, module/data/item/class.mjs, module/data/item/equipment.mjs, module/data/item/feat.mjs, module/data/item/spell.mjs, module/data/item/templates/activities.mjs, module/data/item/weapon.mjs, module/data/shared/activation-field.mjs, module/data/shared/duration-field.mjs, module/data/shared/range-field.mjs, module/data/shared/target-field.mjs, module/data/shared/uses-field.mjs, module/documents/activity/mixin.mjs, module/documents/item.mjs, module/utils.mjs, templates/activity/parts/attack-details.hbs, templates/activity/parts/save-details.hbs
This should resolve any data preparation warnings caused by data that has been moved into activities. This means that most labels are now generated on an activity's `label` object rather than on the item, unless it is something like a spell or weapon that has certain intrinsic data.
The handfull of type-specific label generation that is left on items has been moved into data models to clean up `Item5e`.
The `ability` data for `AttackActivity` and `SaveActivity` has been moved into the `attack` and `save` objects respectively to make room at the top level for an `ability` getter which is used to set `@mod` in roll data.
A number of the getters on `Item5e` have been marked as deprecated if they call into deprecated getters on the data model.
=> [#1964] Remove activation-based preparation from items

module/applications/item/ability-use-dialog.mjs, module/documents/active-effect.mjs, module/documents/activity/mixin.mjs, module/documents/actor/actor.mjs, module/documents/chat-message.mjs, module/documents/item.mjs
Migrates the old chat usage chat flags (`itemData` and `use`) to a new data structure to better support activities and provide shims for accessing the data from the old locations.
=> [#1964] Migrate chat message flags to new structure, add shims

module/documents/activity/mixin.mjs, module/documents/activity/utility.mjs, module/documents/actor/actor.mjs, module/documents/chat-message.mjs, module/documents/item.mjs, templates/chat/activity-card.hbs
Buttons created in chat messages through activities can now take `[data-action]` parameters which will automatically call handlers defined in the activity's metadata.
The `UtilityActivity` now has a rolling button which calls the `rollFormula` method, duplicating the functionality of the old method from `Item5e` using the new rolling API.
The old `rollFormula` method has been deprecated and will call the new method provided a `UtilityActivity` is present on the item.
=> [#1964] Add buttons to activity messages, rollFormula for Utility

lang/en.json, module/applications/activity/utility-sheet.mjs, module/data/activity/utility-data.mjs, module/documents/activity/utility.mjs, templates/activity/utility-effect.hbs, templates/activity/utility-identity.hbs
Gives two options to the roll on `UtilityActivity` controlling whether the roll configuration dialog is displayed and whether the roll button is visible to all users or just the creator.
=> [#1964] Add options to utility roll

module/data/activity/attack-data.mjs, module/data/item/spell.mjs, module/data/item/templates/activities.mjs, module/data/item/weapon.mjs, module/dice/d20-roll.mjs, module/documents/activity/attack.mjs, module/documents/activity/mixin.mjs, module/documents/activity/utility.mjs, module/documents/actor/actor.mjs, module/documents/chat-message.mjs, module/documents/item.mjs
Adds the Attack button to attack activities and the `rollAttack` method, which replicates the behavior of that method from `Item5e` but uses the new rolling API. Internally this constructs config objects according to the new API to call the `preRollAttackV2` hook, and then translates that back into the old configuration format for calling the deprecated hooks and the roll constructor.
A new `criticalThreshold` getter on `AttackActivity` now handles most of the functionality of the old getter on `ActionTemplate`. The `criticalThreshold` getter on `ItemDataModel` replaces `_typeCriticalThreshold` which is no longer required (but is still checked for backwards compatibility).
A few of the signatures of the new rolling hooks have changed. The pre hooks no longer pass the activity as the first …
=> [#3910] Move rollAttack to AttackActivity

less/v2/chat.less, module/data/item/feat.mjs, module/documents/activity/mixin.mjs, module/documents/activity/save.mjs, module/documents/activity/utility.mjs, module/documents/actor/actor.mjs, module/documents/chat-message.mjs, module/documents/item.mjs, module/enrichers.mjs, module/utils.mjs, templates/chat/activity-card.hbs
Adds a saving throw button to the card generated by the `SaveActivity` and transfer the logic from `_onChatCardAction`.
Modifies the logic in `ChatMessage5e` for hiding buttons to give activites more control over what buttons are visible. Right now they can use `data-visibility` to specify whether a button is available only go GMs (`gm`), to the message creator (blank value), or everyone (`all`). It then asks the activity using the `shouldHideChatButton` method to implement more complex logic if necessary.
=> [#3911] Add Saving Throw button for `SaveActivity`

module/data/activity/attack-data.mjs, module/data/activity/base-activity.mjs, module/data/activity/damage-data.mjs, module/data/activity/heal-data.mjs, module/dice/damage-roll.mjs, module/documents/activity/damage.mjs, module/documents/activity/heal.mjs, module/documents/activity/mixin.mjs, module/documents/item.mjs
Adds the `rollDamage` method to the activity mixin which provides a shared method for all activity types that roll damage. This calls into `getDamageConfig` and `processDamagePart` which provide places for individual activity types a place to configure the data provided to damage rolls.
This PR implements rolling damage for `DamageActivity` and `HealActivity`, and leaves out some parts of the damage data preparation that are only relevant to attack damage rolls.
Note: Currently just falls back to using the first of the provided damage types.
=> [#3912] Implement damage rolls for Damage & Heal activities

lang/en.json, module/data/activity/damage-data.mjs, module/data/activity/save-data.mjs, module/documents/activity/mixin.mjs, module/documents/activity/save.mjs, module/documents/activity/utility.mjs, module/documents/chat-message.mjs
Adds the damage button for the save activity. Saves are set to not allow critical damage.
Also adds a flag to the chat message indicating how much damage is done on a save, which is displayed in the chat message.
=> [#3911] Add damage rolls for `SaveActivity`

module/documents/actor/actor.mjs
From a discussion on Discord, someone imported some beasts from the Monsters SRD compendium to wildshape into. When they did, the new token didn't have the Vision Enabled value checked because it wasn't enabled on the beast's prototype token they imported. While they can fix it by enabling vision on the beasts they import, it'd be a better UX if the system kept the original value of that particular token property rather than requiring the GM to update the prototype token of each beast they import for the Druid PC to wildshape into.
=> Keep the original token's sight.enabled value when transforming an actor

module/data/activity/attack-data.mjs, module/data/shared/damage-field.mjs, module/documents/activity/attack.mjs, module/documents/activity/damage.mjs, module/documents/item.mjs
Adds the damage button for the attack activity and handles all of the attack-specific bonuses.
This adds a new option to the configuration for `mode`, which will be determined by the attack roll and modifies damage based on whether it is a one-handed, two-handed, off-hand, or thrown attack.
=> [#3910] Add damage rolls for `AttackActivity`

dnd5e.mjs, module/module-registration.mjs
Adds a registration step for modules that detects declarations in active modules and automatically integrates them during system preparation.
The only declaration currently supported is `dnd5e.sourceBooks`, which declares source books in the same format as the `sourceBooks` config object in the system. The key is a abbreviated name for the source and the value is the full name, which can be a localization string.
Closes #3799
=> [#3799] Add option to register source books directly in manifest

lang/en.json, module/applications/activity/activity-usage-dialog.mjs, module/applications/dice/roll-configuration-dialog.mjs, module/config.mjs, module/data/activity/base-activity.mjs, module/data/shared/uses-field.mjs, module/documents/activity/mixin.mjs, module/documents/activity/utility.mjs, module/documents/actor/actor.mjs, module/documents/chat-message.mjs, module/utils.mjs, templates/activity/activity-usage-concentration.hbs, templates/activity/activity-usage-consumption.hbs, templates/activity/activity-usage-creation.hbs, templates/activity/activity-usage-notes.hbs, templates/activity/activity-usage-scaling.hbs, templates/activity/parts/activity-consumption.hbs
Adds the initial activity usage dialog which re-implements the item usage dialog in ApplicationV2. The new setup should be more flexible to allow for specific activity types like Enchant and Summon to add their own controls. It also now re-renders when changes are made allowing for dynamic inputs and messages.
The dialog currently doesn't implement the consumption warnings from the original dialog pending the implementation of the consumption system, nor does it re-scale the item when changes to scaling are made.
=> [#1964] Implement initial activity usage dialog

module/data/item/templates/activities.mjs
Other places where similar checks happend in the system don't assume `_stats` is present, this can cause issues when creating documents from data.
=> Don't assume _stats is present in activities migration

module/applications/activity/activity-usage-dialog.mjs, module/data/abstract.mjs, module/data/activity/base-activity.mjs, module/data/actor/character.mjs, module/data/actor/npc.mjs, module/data/item/spell.mjs, module/data/shared/damage-field.mjs, module/documents/_module.mjs, module/documents/activity/mixin.mjs, module/documents/item.mjs, module/documents/scaling.mjs
Changes how scaling occurs to be able to handle scaling on all items, not just spells. It does this by adding the `dnd5e.scaling` flag which contains the number of steps an item was activated ahove its base level. So for a spell cast at its base level, this would be `0` and it would go up `1` for each level it is upcast.
This value is made available in roll data in two ways. For spells, their roll data is automatically updates to `@item.level` always coresponds to the proper spell level without having to update that value when cloning the item. There is also the `@scaling` value which is the scaling value and `@scaling.increase` which is the increase.
So for a spell that targets one creature at its base level and one additional creature for each slot above base level, you would just enter …
=> [#1964] Properly scale items when activated

module/applications/combat/combat-tracker.mjs
Modifies context preparation on CombatTracker5e to drop any decimal digits after the initiative value.
=> [#1192] Hide dex tiebreakers in combat tracker

module/data/actor/templates/attributes.mjs, module/documents/active-effect.mjs, module/documents/actor/actor.mjs
Adds a new `attributes.ac.min` property. If this evaluates to something higher than what `ac.value` would evaluate to, it is used instead.
This allows spells like Barkskin to function (an AC that cannot be below 16 regardless of armor).
Unblocks #2258.
=> Add armor class minimum property

lang/en.json, module/applications/actor/npc-sheet-2.mjs, module/settings.mjs
Adds a setting for skills that appear on NPC sheets regardless of level of proficiency.
Using a `DataField` for the setting, so requires v12.
Closes #3865.
=> [#3865] Add setting for default skills.

module/documents/chat-message.mjs
Since properly summarizing complex operators like multiplication is hard to do without just showing the whole roll formula, this simply removes the constant number portion of the damage roll tooltip if any operators other than addition or subtraction are found. This still allows the dice rolls to be seen and the total displays correctly, but removes any potentially confusion values.
Before:
After:
Closes #3596
=> [#3596] Remove multiplication constant from damage tooltips

lang/en.json, module/config.mjs, module/data/activity/attack-data.mjs, module/data/actor/templates/attributes.mjs, module/documents/actor/actor.mjs, module/documents/actor/hit-dice.mjs, module/settings.mjs
Adds a setting to change between the Legacy (2014) and Modern (2024) rules and implements a few of those rules changes:
- Exhaustion now reduces D20 tests by 2 and speed by 5 for each level of exhaustion, without the other legacy effects.
- Jack of All Trades no longer adds to initiative bonus
- Remarkable athlete no longer adds half proficiency, but does give advantage on initiative rolls
- All hit dice are recovered on a long rest
Closes #3920
Closes #3982
=> [#3920, #3982] Add rules version setting, implement new exhaustion

module/data/activity/base-activity.mjs, module/dice/damage-roll.mjs, module/dice/dice.mjs, module/documents/activity/mixin.mjs, templates/chat/roll-dialog.hbs
Adds the damage type selection to the damage roll dialog, falling back to the first damage type specified if the dialog is skipped.
Closes #3911
Closes #3912
=> [#3910, #3911, #3912] Add damage type selection to roll dialog

lang/en.json, module/applications/components/enchantment-application.mjs, module/config.mjs, module/data/abstract.mjs, module/data/activity/attack-data.mjs, module/data/activity/enchant-data.mjs, module/data/item/templates/activities.mjs, module/data/item/weapon.mjs, module/dice/d20-roll.mjs, module/dice/dice.mjs, module/documents/active-effect.mjs, module/documents/activity/attack.mjs, module/documents/chat-message.mjs, module/registry.mjs, templates/chat/roll-dialog.hbs
Adds attack modes that can be declared by item and are selectable within the attack roll dialog. When one of these modes is selected it is stored in the attack roll message flags.
When the damage button is clicked for an `AttackActivity`, it fetches the attack mode from the most recent attack roll performed from the same chat message and passes that to `rollDamage`. This is facilitated by a new `rollMessages` entry in the registry.
=> [#3910] Add attack mode selection, relay mode to damage rolls

lang/en.json, module/applications/activity/enchant-sheet.mjs, module/data/activity/enchant-data.mjs, module/data/item/consumable.mjs, module/data/item/equipment.mjs, module/data/item/loot.mjs, module/data/item/templates/item-type.mjs, module/data/item/tool.mjs, module/data/item/weapon.mjs, module/documents/activity/enchant.mjs, templates/activity/parts/enchant-restrictions.hbs
Adds an enchantment restriction based on item category that takes multiple options, allowing for restricting to categories such as "Simple Melee" weapons or "Heavy Armor". The category lists per-type are fetched from the data model using a new `itemCategories` static getter to make it easy for module-provided types to provide their own category lists.
Also adds a restriction based on item properties. Currently the restriction requires just one of the provided properties to be considered valid, but it might also make sense to require all of them or provide a toggle between those two modes.
Adds a new hook to the `canEnchant` method so modules can provide their own enchantment restrictions.
Closes #3590
=> [#3590] Add additional enchantment restrictions

lang/en.json, module/applications/activity/attack-sheet.mjs, module/applications/item/item-sheet-2.mjs, module/config.mjs, module/data/activity/attack-data.mjs, module/data/item/consumable.mjs, module/data/item/weapon.mjs, templates/items/details/details-consumable.hbs, templates/items/details/details-damage.hbs, templates/items/details/details-weapon.hbs, templates/items/parts/item-activation.hbs
Updates the names for ammunition types and add "Firearm Bullet" type to bring everything up to date with the 2024 rules.
Adds damage data to consumable items that is only visible for ammunition. This damage has an additional option defining whether it supplements the weapon damage or replaces it.
Adds a "Ammunition Type" field to weapons defining what type of ammo they use. This data will be used in a followup PR to add a ammo selection UI to the attack roll dialog that only lists ammo that can be used with the weapon.
Also modified the damage section on weapons to add a hint about how the weapon damage is used and how `@mod` isn't necessary. Plus hide damage types for versatile damage since the system just fetches those from the base damage. Finally it displays a placeholder for the …
=> [#1866, #4011] Update ammo types, add ammo damage & type to weapon

module/data/activity/attack-data.mjs, module/data/item/weapon.mjs, module/dice/d20-roll.mjs, module/dice/dice.mjs, module/documents/activity/attack.mjs, templates/chat/roll-dialog.hbs
Adds a list of usable ammunition types to the attack dialog determined by the ammunition type on the weapon. When one of these is selected any magic bonus it has is added to the attack roll and a piece of ammunition is consumed. If the consumption destroys the ammunition then it is stored in the roll message to ensure it can be used for damage calculation.
When rolling damage the ammunition used on the last attack is sent to the `rollDamage` method. If the ammo has its own damage it either replaces the weapon's base damage or adds a new damage part. The ammo's magical bonus is added to the base damage.
Closes #1039
Closes #3268
Closes #3314
=> [#1039, #3268, #3314] Add ammo selection, consumption, & bonuses

lang/en.json, module/config.mjs, module/data/item/templates/activities.mjs, module/data/shared/uses-field.mjs, module/documents/actor/actor.mjs, module/documents/actor/hit-dice.mjs
Re-implements uses recovery to support uses on items and activities and multiple recovery profiles. Rest types now declare what type of periods they recover in prefered order.
This also introduces some other changes to the resting system to support better configuration of the process, allowing rest types to declare what types of spellcasting slots they recover and whether they recover hit points or hit dice. This should make it more feasible to implement custom rest types.
=> [#1964] Re-implement uses recovery, adjust resting design

lang/en.json, module/applications/activity/activity-usage-dialog.mjs, module/applications/components/enchantment-application.mjs, module/documents/activity/attack.mjs, module/documents/activity/damage.mjs, module/documents/activity/heal.mjs, module/documents/activity/mixin.mjs, module/documents/activity/save.mjs, module/documents/activity/summon.mjs, module/documents/activity/utility.mjs, module/documents/chat-message.mjs, module/documents/item.mjs
Add the "Place Template" and "Consume Resource" buttons back to the chat card if necessary.
Also modified the `clone` data on items to automatically call `prepareFinalAttributes` to prevent bugs caused by cloned items not being fully prepared.
=> [#1964] Add back Place Template & Consume Resource buttons

module/data/activity/base-activity.mjs, module/data/item/templates/activities.mjs, module/documents/item.mjs, module/migration.mjs
- Remove call to `pack.migrate` to fix core bug with missing `template.json`
- Doesn't migrate charged state if charged formula is `null`
- Create activities before item migration
- Creates separate `SaveActivity` if a save ability is set and the main activity isn't `SaveActivity`
- Creates separate `UtilityActivity` if formula is set and the main activity isn't `UtilityActivity`
=> [#1964] Tweak how activity migrations are performed

module/data/activity/attack-data.mjs, module/data/activity/base-activity.mjs, module/data/activity/damage-data.mjs, module/data/activity/enchant-data.mjs, module/data/activity/heal-data.mjs, module/data/activity/save-data.mjs, module/data/activity/summon-data.mjs, module/data/activity/utility-data.mjs, module/data/item/templates/activities.mjs, module/data/item/weapon.mjs, module/migration.mjs
- Creates additional `DamageActivity` for items that aren't weapons but have versatile damage
- Migrates `range.value` to `range.reach` for melee waepons without the thrown property
- Adjust the API of `refreshCompendium` to call `migrateCompendium` first with proper error handling if the migration fails
=> [#1964] Migrate reach & versatile damage for non-weapons

module/data/item/templates/activities.mjs, module/migration.mjs
Performs a concrete migrate for `uses.value` because it relies on the resolved max uses formula. The involved some changes to how migrations are called to pass the fully prepared item through the process.
Also fixed a migration issue for items that have charges but not a recovery formula set getting a recovery period.
=> [#1964] Migrate uses, fix recovery on charges items w/o formula

lang/en.json, module/config.mjs, module/data/activity/base-activity.mjs, module/data/item/spell.mjs, module/documents/item.mjs, templates/activity/parts/activity-time.hbs
Adds `concentration` into the duration data on activities and removed it as a property on all items except spells. This allows concentration to be handled on a per-activity basis rather than for an item as a whole.
For spells, they get the derived `duration.concentration` value based on their properties and that will be inferred on the activity unless the duration is overridden.
=> [#1964] Move concentration into activity duration

lang/en.json, less/v2/dark/forms.less, less/v2/forms.less, module/applications/api/application.mjs, templates/activity/parts/activity-consumption.hbs
We can't really use normal hint text in these form groups because they are of variable height, so I've made this PR to restore the use of them via a tooltipped icon. Having lots of these in a form will make it very busy so they should still be used sparingly though, and not on every single input.
=> Restore hint text to label-top form groups.

lang/en.json, module/applications/activity/activity-sheet.mjs, module/applications/activity/activity-usage-dialog.mjs, module/data/activity/base-activity.mjs, module/documents/activity/mixin.mjs, templates/activity/parts/activity-consumption.hbs
Adds `consumption.spellSlot` that only appears when an activity is on a spell that controls whether a spell consumes a slot. If a spell wouldn't normally consume a slot then this setting does nothing. Unchecking this still allows upcasting the spell.
=> [#1964] Support activities on spells that don't consume slots

less/v2/activities.less, less/v2/apps.less, less/v2/compendium-browser.less, less/v2/dark/apps.less, less/v2/dark/forms.less, less/v2/forms.less, module/applications/activity/activity-usage-dialog.mjs, module/applications/activity/summon-usage-dialog.mjs, module/applications/api/application.mjs, module/applications/fields.mjs, templates/activity/activity-usage-concentration.hbs, templates/activity/activity-usage-consumption.hbs, templates/activity/activity-usage-creation.hbs, templates/activity/activity-usage-scaling.hbs, templates/activity/enchant-usage-creation.hbs, templates/activity/summon-usage-creation.hbs
Adjusts the styling of the activity usage dialog to match the V2 system styling more closely. This includes a redesigned range input which wasn't previously styled.
Adds a subtitle to the header of all V2 sheets configurable via `options.subtitle` or the `subtitle` getter. This will be hidden when the application is minimized.
Also changes the outer element of the usage application to be a `<dialog>` element and the content tag to be `<form>`.
Note: Resource consumption currently isn't styled awaiting a followup PR that makes more significant changes to those options.
=> [#1964] Adjust styling of usage, switch to <dialog> element

lang/en.json, less/v2/activities.less, less/v2/dark/activities.less, module/applications/activity/activity-usage-dialog.mjs, module/config.mjs, module/data/activity/fields/consumption-targets-field.mjs, templates/activity/activity-usage-consumption.hbs
Creates hints for each resource consumption target in the usage dialog displaying what will be consumed and how much, adjusting automatically based on the scaling.
=> [#1964] Communicate consumption costs in usage dialog

module/config.mjs, module/documents/activity/mixin.mjs, module/documents/chat-message.mjs, module/documents/item.mjs
Modifies spell scroll creation to deal with activities rather than the old activation data. This involves copying over the activities, merging in data that was originally inferred from the spell, and applying save DC & attack bonus changes directly to the proper Save and Attack activities. Because the reference scroll data no longer contains the values we used to use for determining DC & attack bonus under the 2014 rules, this adds a config object to provide those values.
This also fixes a couple of bugs preventing activities from being used from destroyed items.
Note: While the API side has been updated to support custom DC and attack bonus values for the 2024 rules, the spell scroll UI hasn't been updated to provide those values yet.
=> [#1964] Update spell scroll creation to work with activities

dnd5e.mjs, module/data/item/subclass.mjs, module/registry.mjs
Adds a "Has Spellcasting" filter to subclasses in the compendium browser indicating the subclass provides spellcasting. Also adds the ability to filter by the class to which the subclass belongs.
To support the second filter, this introduces the `ItemRegistry` to the system registry that scans compendiums and loads all classes registered in different compendium packs. These are grouped by identifier and different versions of a class in different packs are consolidated with their UUIDs listed in the `sources` list. This only supports classes at the moment but could easily be expanded to incude subclasses, backgrounds, or species, which maybe useful to work on spell lists.
Closes #3836
Closes #3853
=> [#3836, #3853] Add Has Spellcasting & Class filters to subclasses

module/module-registration.mjs, module/registry.mjs, system.json
Adds a new registry entry for tracking spell lists. This contains `SpellList` objects grouped by type and identifier, with all spell list journal entry pages contributing spells to the shared list. Each `SpellList` object contains the means to access the UUIDs, indexes, and fully-loaded spell documents for all listed spells.
A new module data registration method has been added to allow for modules to declare spell lists in their package manifets using the `dnd5e.spellLists` flag.
Closes #3786
=> [#3786] Add system for consolidated spell lists

module/data/item/templates/activities.mjs
Some items that do not have activities, when imported, if they do not have an old system.save entry, fail migration/import
=> Activities Migration: Conditionaly check for save

lang/en.json, module/applications/activity/activity-usage-dialog.mjs, module/applications/actor/character-sheet-2.mjs, module/applications/api/dialog.mjs, module/applications/item/create-scroll-dialog.mjs, module/data/item/class.mjs, module/data/item/fields/spellcasting-field.mjs, module/data/item/subclass.mjs, module/documents/item.mjs, templates/apps/spell-scroll-dialog.hbs
Reworks the Create Scroll using ApplicationV2 in a way that allows for dynamic updates of the form. It now displays fields for spell save DC and attack bonus with placeholders updating dynamically when the spell level is changed.
These fields can also be set manually, overriding the default DC of spells. If using the modern rules version and create a scroll directly from a spell in an actor's inventory, then these values will be initial set based on that actor's spellcasting stats.
Closes #4043
=> [#4043] Refresh Create Scroll UI, allow custom spell values

module/data/activity/attack-data.mjs, module/data/activity/base-activity.mjs, module/dice/damage-roll.mjs, module/documents/activity/attack.mjs, module/documents/activity/mixin.mjs
Stores previously selected attack mode, ammunition, and damage types in a flag on the item on a per-activity basis and uses those stored values to pre-populate fields in the attack and damage dialogs.
=> [#1964] Remember attack mode, ammunition, & damage types

less/v2/items.less, module/data/item/spell.mjs, module/registry.mjs
Modifies the `SpellListRegistry` to keep track of what spell lists provide a spell in addition to spell lists by type. This allows spells to retrieve a list of spell lists they appear on and turn it into a list of classes to be displayed on the spell sheet.
Part of this work involves fetching the name of the class from the item registry rather than using the name of the spell list itself. In order to get around the loading time involved a new API has been added to the registry that allows defering a callback until all registries have fully loaded.
Closes #1229
=> [#1012, #1229] Display classes providing spells on spell sheet

lang/en.json, module/config.mjs, templates/shared/fields/field-targets.hbs
Modifies how the area of effect types are listed to split them into a list of the six standard types defined in the rules, and the other non-standard types separated by an `<hr>`.
Also adds a new "Circle" type for spells that need a circle template without associated height.
Closes #4063
=> [#4063] Add cylinder AoE type, split AoE list into sections

module/data/activity/base-activity.mjs, module/data/item/tool.mjs, module/data/item/weapon.mjs
Automatically creates an `AttackActivity` on newly created weapons and a `CheckActivity` on newly created tools.
=> [#1964] Automatically create activities on new Weapons & Tools

module/data/actor/templates/attributes.mjs, module/data/item/class.mjs, module/data/item/subclass.mjs, module/documents/item.mjs
If a new class with spellcasting is added to an actor and no primary spellcasting ability is set for that actor, this will set it automatically.
Closes #3701
=> [#3701] Set spellcasting ability when adding new class to character

module/applications/activity/activity-sheet.mjs, module/applications/item/item-sheet-2.mjs, module/canvas/ability-template.mjs, module/config.mjs, module/data/shared/target-field.mjs
Dynamically updates the template size for the emanation area of effect to take the hovered token's size into account when placing the template.
https://github.com/user-attachments/assets/8ed3c78b-ed01-481c-98b0-8e48fb3a9966
Also adjust the code for area of effect dimensions to handle one without a sizes object and merged the two implementations.
Closes #1011
=> [#1011] Adjust emanation template size when placing

module/data/item/spell.mjs
Using the new consolidated spell lists this attempts to pick the proper `sourceClass` for spells when they are added to a character sheet. It uses the following logic:
1. Grab spellcasting classes, if none exists then don't set source
2. If only one spellcasting class exists, set it as the source
3. If preparation mode is pact and a class exists that offers pact casting, then set that class as the source
4. Create intersection of classes on actor with classes that offer the spell, set source as first intersecting class or first class on actor if no intersections are found
Closes #1012
=> [#1012] Select source class for spells when added to sheet

lang/en.json, module/applications/advancement/trait-config.mjs, module/config.mjs, module/documents/actor/select-choices.mjs, module/documents/actor/trait.mjs, module/documents/advancement/trait.mjs
Weapon masteries can now be granted or chosen through `TraitAdvancement` using the new "Mastery" mode.
=> [#3983] Add weapon mastery support to `TraitAdvancement`

module/applications/actor/npc-sheet-2.mjs
Allows the removal of the Perception skill without error by checking if the actor has the `prc` skill before adding it to senses.
=> [#4076] Allow removal of Perception for ActorSheet5eNPC2

lang/en.json, module/applications/advancement/item-choice-config.mjs, module/applications/advancement/item-grant-config.mjs, module/data/activity/save-data.mjs, module/data/advancement/spell-config.mjs, module/data/item/spell.mjs, module/documents/advancement/item-grant.mjs, templates/advancement/parts/advancement-spell-config.hbs, templates/items/details/details-spell.hbs
Handles setting the limited uses on spells granted through an advancement in a way that respects activities. To support all the desired workflows, a "Requires Slot" checkbox has been added to the spell config which controls how the limited uses are applied.
- If preparation mode doesn't require a spell slot by default or "Requires Slot" is checked, then consumption is added to all activities on the spell marked to "Consume Spell Slot"
- If preparation mode requies a slot and "Requires Slot" isn't checked, then each activity marked to "Consume Spell Slot" is duplicated, given consumption, removed spell slot consumption, and has "Free Casting" added to its name
This combination should handle all of the standard configurations needed for official content.
This PR also reintroduces …
=> [#4079] Handle limited uses on granted spells

module/canvas/token-placement.mjs
Closes #3462.
Possible it can be more optimized, however I tested on
- gridless with a token of size 0.5, 1, 2, 3
- square grid with a token of size 0.5, 1, 2, 3
- hexagonal rows (odd) with token of size 0.5, 1, 2, 3
and it seemed to work just fine.
Also implements the ability to hold shift to disable snapping.
=> [#3462] Hex grid TokenPlacement

dnd5e.mjs, module/applications/item/item-sheet-2.mjs, module/applications/item/item-sheet.mjs, module/applications/item/sheet-v2-mixin.mjs, module/data/_module.mjs, module/data/active-effect/_module.mjs, module/data/active-effect/enchantment.mjs, module/data/activity/attack-data.mjs, module/data/activity/fields/consumption-targets-field.mjs, module/data/fields/activities-field.mjs, module/data/item/fields/spellcasting-field.mjs, module/data/item/spell.mjs, module/documents/active-effect.mjs, module/documents/activity/attack.mjs, module/documents/activity/mixin.mjs, module/documents/activity/summon.mjs, module/documents/chat-message.mjs, module/documents/item.mjs, templates/activity/parts/damage-part.hbs, templates/activity/parts/damage-parts.hbs
Adds system data model for enchantment active effects that has custom application logic to handle enchantments targeting fields that no longer exist on items. These handle `attack.bonus`, `attack.flat`, `damage.parts`, `save.dc`, `save.scaling`. These fields cover everything applied by summoning as well as the most common fields modified by enchantment spells or features.
=> [#3913, #3914] Handle enchantments that target moved fields

module/applications/compendium-browser.mjs, module/data/item/spell.mjs, module/registry.mjs
Adds a new filter for spells to the Compendium Browser that allows filtering by a specific spell list. This involves some tweaks to how spell lists are stored in the registry to allow for creating a list of all lists easily.
This new filter allows for easily finding all the spells for a specific class across all modules that register spell lists. It also allows doing things like finding spells that are on the spell list of one class but not on any others.
Closes #2508
=> [#2508] Add spell list filter to compendium browser

module/applications/actor/api/base-config-sheet.mjs, module/applications/actor/base-sheet.mjs, module/applications/api/document-sheet.mjs, module/applications/item/item-sheet.mjs, module/applications/source-config.mjs, module/config.mjs, module/data/actor/npc.mjs, module/data/actor/vehicle.mjs, module/data/item/background.mjs, module/data/item/class.mjs, module/data/item/consumable.mjs, module/data/item/container.mjs, module/data/item/equipment.mjs, module/data/item/feat.mjs, module/data/item/loot.mjs, module/data/item/race.mjs, module/data/item/spell.mjs, module/data/item/subclass.mjs, module/data/item/templates/item-description.mjs, module/data/item/tool.mjs, module/data/item/weapon.mjs, module/data/shared/source-field.mjs, module/module-registration.mjs, system.json, templates/apps/source-config.hbs
Uses the new `sourceBooks` manifest flag to automatically select the proper source book to use for source labels if no source book is specified. This only works for documents in compendiums (or imported from compendiums) for modules that define a single source book.
Also re-designs the source configuration app using ApplicationV2.
Closes #3801
=> [#3801] Automatically determine source book from module

module/dice/basic-roll.mjs
re: #2254
Perhaps something that can be carried over to `DamageRoll`. I tested with making `DamageRoll` extend `BasicRoll` and found `preprocessFormula` to become entirely redundant.
=> Add `simplify` method to `BasicRoll`

module/data/activity/attack-data.mjs, module/data/item/consumable.mjs, module/data/item/weapon.mjs
Uses source data rather than system data for displaying damage types on weapons & armor to avoid polluting base data with enchantment data.
Ensures that the damage clone created for the attack activity includes changes caused by enchantments.
=> [#3914] Fix enchanted damage types into activities

lang/en.json, module/applications/activity/check-sheet.mjs, module/data/activity/check-data.mjs, module/documents/activity/check.mjs, templates/activity/parts/check-details.hbs
Changes the `check.associated` value on `CheckActivity` to be a set of associated values rather than a single value. If multiple associated values are set then more than one button will appear in the chat card.
Setting an explicit ability for the activity will cause all of the created checks to use that ability, otherwise they will attempt to determine the best ability to use (skills from the default value in config, tools from the tool item or character data).
=> [#4024] Rework Check Activity to support multiple checks

packs/_source/items/weapon/longbow-1.json, packs/_source/items/weapon/longbow-2.json, packs/_source/items/weapon/longbow-3.json, packs/_source/items/weapon/longbow.json, packs/_source/items/weapon/shortbow-2.json, packs/_source/items/weapon/shortbow-3.json, packs/_source/items/weapon/shortbow.json, packs/_source/items/weapon/vicious-longbow.json
=> [#4125] New icons for magic bows

less/v2/activities.less, module/applications/activity/summon-sheet.mjs, module/data/activity/summon-data.mjs, module/documents/activity/summon.mjs, templates/activity/parts/summon-changes.hbs
Uses the effects system in activities to set an active effect that is added to summons when placed, allowing the setting of arbitrary values on the summoned creature.
Closes #3242
Closes #3762
=> [#3762] Add arbitrary effects to summoned creatures

lang/en.json, module/applications/activity/activity-choice-dialog.mjs, module/applications/activity/enchant-sheet.mjs, module/data/activity/enchant-data.mjs, module/documents/active-effect.mjs, module/documents/actor/actor.mjs, module/documents/chat-message.mjs, module/documents/item.mjs, module/migration.mjs, templates/activity/parts/enchant-enchantments.hbs
Allows activities to be applied to the item alongside enchantments like effects and items are currently.
The previous method of using a flag on effects to mark them as riders wasn't practical in this case due to activites not having flags, so this stores the rider activities and effects in a new flag on the item itself. A migration is included to move the `rider` flag from the effects to the item flags.
Closes #3803
=> [#3803] Add rider activities to enchantments

module/config.mjs
Closes #4084 using icon `icons/environment/people/group.webp`
Also a replacement for my PR #4036 which I broke.
=> [#4084] Update config.mjs humanoid icon

packs/_source/items/weapon/blowgun-1.json, packs/_source/items/weapon/blowgun-2.json, packs/_source/items/weapon/blowgun-3.json, packs/_source/items/weapon/blowgun.json, packs/_source/items/weapon/vicious-dart.json, packs/_source/items/weapon/whip-1.json, packs/_source/items/weapon/whip-2.json, packs/_source/items/weapon/whip-3.json, packs/_source/items/weapon/whip.json
I made an error in #4083 giving the incorrect icons to Blowguns and missing Whips entirely. This rectifies the issue and also includes Vicious Darts which were left out.
=> Fix icons for Blowguns and Whips

lang/en.json, less/v2/compendium-browser.less, less/v2/inventory.less, less/v2/tooltips.less, module/applications/compendium-browser.mjs, module/data/shared/source-field.mjs, templates/compendium/browser-entry.hbs, templates/compendium/browser-results.hbs, templates/compendium/browser-sidebar-filter-set.hbs, templates/compendium/browser-sidebar-filters.hbs
Some challenges here around filtering on a derived field. I also wasn't able to figure out how to use `compendiumBrowserFilters` without either: scanning all packs at startup in order to identify custom source fields; or only using pack metadata and then losing the ability to filter on custom source fields.
I think this approach ended up not being too messy, with only a small amount of special-casing that is maybe warranted for something as ubiquitous as the source field.
=> Add sources filtering to compendium browser.

module/documents/item.mjs
Removes a lot of old data provided to the template when rending cards directly from items and adjusts the method to take the new config objects.
=> Refactor `Item5e#displayCard` to remove unnecessary data

module/data/fields/formula-field.mjs, module/documents/active-effect.mjs
Moves the custom active effect handling for formulas into the `FormulaField` class using the new system offered by Foundry V12.
Also refactors a lot of the other application behavior in `ActiveEffect5e` to avoid duplicating a bunch of core's code. This includes removing some handling of overriding sets because that is properly handled by core now.
Closes #4143
=> [#4143] Move Active Effect formula changes into FormulaField

lang/en.json, module/data/activity/fields/consumption-targets-field.mjs, module/documents/activity/attack.mjs, module/documents/activity/check.mjs, module/documents/activity/damage.mjs, module/documents/activity/heal.mjs, module/documents/activity/mixin.mjs, module/documents/activity/save.mjs, module/documents/activity/summon.mjs, module/documents/activity/utility.mjs
Adds a button for refunding consumption to chat cards. To support this the system calculates deltas on the actor and item changes during the consumption process and stores those values in the message flags.
Closes #3785
=> [#3785] Add refund button to chat cards

module/registry.mjs
If the Babele module is enabled, defer loading of item registries until Babele has fired its ready hook to ensure that registered items are translted.
Closes #4174
=> [#4174] Defer item regsitry loading if Babel is present

module/applications/activity/check-sheet.mjs, module/data/activity/attack-data.mjs, module/data/activity/base-activity.mjs, module/data/activity/check-data.mjs, module/data/activity/save-data.mjs
Adds "Spellcasting Ability" as one of the options for the check required, allowing something like "Counterspell" to automatically select the correct ability to roll.
=> [#4024] Add spellcasting ability as option for Check activity

module/applications/components/inventory.mjs, module/data/shared/uses-field.mjs, module/dice/basic-roll.mjs, module/documents/activity/attack.mjs, module/documents/activity/mixin.mjs, module/documents/activity/utility.mjs, module/documents/actor/actor.mjs, module/documents/item.mjs
The roll recharge method now makes use of the new configuration structure and rolling hooks to be consistant with other rolls in the system. It also gains a `dnd5e.postRollRecharge` hook that fires after the usage updates have been performed. A similar post hook has been added to `rollHitDice` so that all rolls that perform updates now have a `post*` hook after those updates are complete.
In order to support modifying the chat message flavor based on the result of the recharge roll, a `preCreate` callback has been added to `BasicRollMessageConfiguration` that is called right before the message is creating, allowing for any last-minute changes to the message. This hook will also be very helpful when attack rolls are hit by the roll refactor.
A small tweak has been made to the config and …
=> [#2138] Refactor `rollRecharge` to use `BasicRoll` & new hooks

lang/en.json, module/documents/activity/attack.mjs
Reduces the quantity of a weapon by 1 each time a Thrown attack is made unless the "Returning" property is checked. Also adds a check to ensure that weapon quantity is not zero when attacking.
Closes #3317
=> [#3317] Consume thrown weapon quantity unless Returning is checked

less/v2/apps.less, less/v2/dark/apps.less, module/applications/dice/_module.mjs, module/applications/dice/damage-configuration-dialog.mjs, module/applications/dice/roll-configuration-dialog.mjs, module/dice/damage-roll.mjs, module/dice/dice.mjs, module/documents/activity/mixin.mjs, module/documents/chat-message.mjs, templates/dice/damage-formulas.hbs, templates/dice/roll-buttons.hbs
Reworks parts of `DamageRoll` to match the design of `BasicRoll` and removed a number of methods not needed anymore. Deprecated the `damageRoll` standalone method and changed it internally to use the new `DamageRoll#build` method. Finally adjusted `rollDamage` to use the new build process.
Implemented a new roll configuration dialog for damage rolls that allows for selecting damage type and improved the base dialog to support entering situational bonuses for each damage part, rather than for just the first one.
=> [#2138] Refactor `DamageRoll` to use new rolling API

module/migration.mjs
Sets the identifier for items using a one-time concrete migration. Avoided an in-memory migration because an empty identifier is considered valid.
Adds a `bypassVersionCheck` flag to migrations that allows skipping the check that prevents certain migrations from being applied to items updated in `4.0.0` or later. This is a flag to allow for re-migrating items that have already been migrated to `4.0`.
=> [#1539] Use migration to set identifier on items

less/v2/dark/activities.less, module/applications/actor/character-sheet-2.mjs, module/applications/components/inventory.mjs, module/applications/item/item-sheet-2.mjs, module/documents/activity/mixin.mjs, templates/actors/tabs/creature-features.hbs, templates/actors/tabs/creature-spells.hbs, templates/items/parts/item-activities.hbs, templates/shared/inventory2.hbs
Some additional polish for activities.
- Fires the Activity's context menu if you right-click an activity row inside the character sheet, rather than firing the parent Item's context menu.
- Always show activities in the expanded view, even if the Item only has one.
- Adds context menu to Items inside favourites.
=> Add context menus to in-sheet Activities.

lang/en.json, module/data/activity/attack-data.mjs, module/data/item/consumable.mjs, module/data/item/weapon.mjs, module/documents/activity/attack.mjs
Light thrown weapons can now use the "Offhand Throw" attack mode that consumes weapon quantity and ignores the modifier to damage.
Ammunition can now get the "Returning" property which prevents its quantity from being reduced when fired.
=> Add Offhand Throw attack mode & returning property to ammunition

module/applications/actor/base-sheet.mjs
re: #2418.
The need for a migration was a year ago, so perhaps it is simply too late to migrate; if so, we should stop deleting `system.proficient` and assume that any item set to "Proficient"/"Not Proficient" instead of "Automatic" is intentionally an item that ignores the proficiencies of the actor it is embedded on.
=> Do not delete `proficient` when dropping an item onto actor.

module/data/actor/templates/creature.mjs, module/data/fields/mapping-field.mjs, module/data/shared/roll-config-field.mjs, module/documents/active-effect.mjs
Fix bugs caused by applying an active effect targeting a value in and entry in `system.tools` when the actor doesn't currently have that entry. The bug was caused by the whole object not being created and other parts of the code expecting it to exist.
This solves the problem by checking if an active effect is trying to apply to an `MappingField` entry that doesn't exist yet, and if so it will first create the initial entry before continuing with the application process.
Closes #4135
=> [#4135] Pre-create `MappingField` data before applying effects

module/documents/activity/attack.mjs
This null guard allows the hook to proceed even when calling the deprecated old hook, however, doing so reveals what appears to be a similar issue downstream in mixin.js, as on some subseuqent casts, in
_createDeprecatedConfigs(usageConfig, dialogConfig, messageConfig)
Uncaught (in promise) TypeError: usageConfig.consume?.resources.includes is not a function
=> add null guard around ammoUpdate

packs/_source/items/equipment/bracers-of-defense.json
Fixes small mistake in #4226 with Bracers of Defense being assigned the wrong icon.
=> Fix bracers-of-defense icon

module/migration.mjs
When the `persistSourceMigration` flag was enabled it updates an item with `diff: false`, but when an effect migration is applied the update data contains only partial updates for effects. This would result in the system attempting to update effects without most of their data leading to an error.
This fix resolves this isssue by manually merging changes with the original effect data before performing the full merge.
Closes #4276
=> [#4276] Fix effect bug caused by `persistSourceMigration`

module/applications/activity/activity-sheet.mjs, module/applications/components/effects.mjs, module/documents/active-effect.mjs
The previous solution didn't handle the case of the activity being deleted from the item sheet, only from the activity sheet, so I bit the bullet and overrode `ActiveEffect#createDialog` to give us the options we need pending any core fixes.
It doesn't behave perfectly, because deleting an AE from the parent now does not re-render the activity sheet. But given that it caused the entire sheet to close before, this is probably still an improvement.
=> Fix activity sheet crashing when AEs are deleted on the parent item.

module/data/shared/duration-field.mjs, module/documents/active-effect.mjs, module/documents/activity/mixin.mjs, module/documents/actor/actor.mjs
Changes a number of concentration implementation details to fully work with activities and fix issues with concentration on non-spell items or activities that offer concentration even if the base item does not.
Modified `beginConcentrating` and `createConcentrationEffectData` to accept an activity rather than an item, with a fallback that selects the first activity and shows a deprecation warning.
Deprecated `ActiveEffect5e#getEffectDurationFromItem` and replaced it with a `getEffectData` method on `DurationField` which serves the same purpose.
Modified concentration checks in the activity usage process to use `requiresConcentration` on the activity rather than the item so that activities that require concentration on items that do not still properly trigger.
Also tweaked the flags added …
=> [#4278, #4279, #4297] Fix concentration from activities

lang/en.json, module/data/activity/attack-data.mjs, module/documents/activity/mixin.mjs, module/documents/chat-message.mjs
- Adds activation conditions indiscriminately now under a 'trigger' label, rather than it being hard-coded to reactions only.
- Re-adds the upcast level of the spell to the spell subtitle, something we accidentally regressed during 4.0.
- Adds more rules-accurate attack type information to attack roll cards.
=> Some additional chat card polish.

dnd5e.mjs
Fixes a problem caused by the `game.i18n.translations` object not being populated with the correct values if a non-English language is enabled and no system-specific translation module is enabled.
Closes #4316
=> [#4316] Fix legacy translations

module/data/abstract.mjs, module/data/activity/base-activity.mjs, module/documents/activity/mixin.mjs, module/documents/item.mjs
The `getCardData` method can now take an activity and if passed, it will grab labels from the activity rather that the item.
Closes #4358
=> [#4358] Fix chat pills not showing properties from the correct activity

module/applications/activity/activity-choice-dialog.mjs, module/applications/item/item-sheet-2.mjs, module/data/fields/activities-field.mjs, module/documents/item.mjs
- Closes #4376 
Ensures activities are sorted on initialisation, so that any code that checks the first activity always receives the user-sorted first activity, rather than the first created activity. It also means we don't have to sort activities in multiple places.
=> [#4376] Sort activities on initialisation

module/data/active-effect/enchantment.mjs
I use(d) system.ability for things like Shillelagh
=> Allow legacy system.ability to transfer on enchantment effects

packs/_source/monsters/undead/avatar-of-death.json
Sets the avatar of death's CR to `-`. On the npc sheet, this removes any xp too.
=> [#861] Null avatar of death cr

packs/_source/items/wand/wand-of-secrets.json
- Changes recovery to dawn instead of LR.
- Removes forced template prompt.
- Adds missing units to template.
- Removes damage activity (a wand of secrets does not deal damage).
- Removes "Other" roll from utility activity.
Closes #4341.
=> [#4341] Wand of Secrets

packs/_source/items/container/glass-bottle/_container.json, packs/_source/items/loot/hourglass.json
The `Glass Bottle` container item is set to a capacity of 6 (pounds). The official description says it can hold 1.5 pints of liquid.
Assuming the liquid is water (or any broadly comparable liquid); 1.5 pints = 1.562 pounds.
Taking a 1:1 ratio for simplicity, the capacity has been updated to 1.5 lbs.
Additionally the `Hourglass` item had a typo saying `psaage` instead of `passage`. Description updated.
=> Fix for `Glass Bottle` capacity and `Hourglass` description

module/applications/actor/base-sheet.mjs
#3879 Removed check in spell filtering for actor type of npc that was causing the prepared spell filter to not work on NPC character sheets
=> [#3879] Remove NPC check in prepared spell filtering

less/v2/activities.less, less/v2/apps.less, less/v2/character.less, less/v2/forms.less, less/v2/inventory.less, less/v2/items.less, less/v2/journal.less, less/v2/tooltips.less, less/variables.less, module/applications/activity/activity-sheet.mjs, module/applications/api/dialog.mjs, module/applications/compendium-browser.mjs, module/applications/dice/roll-configuration-dialog.mjs, module/applications/source-config.mjs, templates/actors/tabs/character-biography.hbs, templates/apps/source-config.hbs
This fixes issues where we were mixing App v1 styles into App v2 apps. I've added `.standard-form` classes where they were missing in order to have the appropriate App v2 styles.
Note that this doesn't change the look of anything (or it shouldn't, anyway), it just means that the V1 compatibility layer in v13 applies appropriately to app v1 apps, and doesn't distort our app v2 apps. The system should look identical between v12 and v13 with only these changes.
=> Divorce system Appv2 apps from Appv1 styles.

module/config.mjs, module/data/actor/templates/common.mjs, module/documents/actor/actor.mjs, module/documents/chat-message.mjs, module/utils.mjs
During AC preparation, adds +5 to AC if three-quarters cover, else +2 to AC if half cover, else 0.
If a target has full cover during an attack roll, shows their ac as infinity.
Closes #4489.
=> [#4489] AC cover calculation

module/documents/activity/mixin.mjs
=> [#4536] Fix typo in variable name causing `ReferenceError` in deprecated hooks

module/data/activity/enchant-data.mjs, module/data/activity/summon-data.mjs
This adjusts the level limits for effects associated with enchant or summon activities to refer to the character level, rather than the spell level for cantrips only. Since cantrips scale with character level, this matches other spells that have their activities gated behind the level they are cast at, in order to provide different effects at different levels of scaling.
If you agree with this reasoning, we can make this change, otherwise it's fine to skip.
=> Adjust enchantment and summon level limits to refer to character level

module/applications/token-config.mjs
Closes #4566 
`per` no longer exists - nor is it necessary to check anything except whether `max` exists (as far as I can tell).
=> [#4566] Fix item use tracking

lang/en.json, module/data/activity/base-activity.mjs, module/data/item/templates/activated-effect.mjs, module/data/item/templates/activities.mjs, module/data/item/templates/identifiable.mjs, module/documents/active-effect.mjs, module/documents/activity/cast.mjs, module/documents/activity/mixin.mjs, module/documents/actor/actor.mjs, module/documents/item.mjs, module/documents/mixins/document.mjs
Adds a system for Cast activities to automatically import a copy with changes applied when added to the actor, keep the cached spell updated when the activities change, and remove the cached copy when the item is removed.
Uses an enchantment effect on the spell to apply the actualy changes needed for easy updating.
Currently does nothing to change how these spells appear on the actor sheet, so they will all display in the spell list as if they were normal spells.
In order to better support multiple spells on an actor sheet with the same compendium source, `Actor#sourcedItems` has been changed to store sets of items, rather than just a single item.
=> [#4061] Add spell caching system to Cast activities

module/applications/activity/activity-usage-dialog.mjs, module/documents/activity/cast.mjs, module/documents/activity/mixin.mjs
Overrides the `use` method on `CastActivity` to trigger the cached spell, rather than the activity itself. If the spell isn't cached, it will first create a new cached copy. Triggers the `use` method on the spell item so that the activity selection dialog can be shown if necessary.
The `CastActivity` introduces two new hooks: `dnd5e.preUseLinkedSpell` and `dnd5e.poseUseLinkedSpell`.
Adds a new option to `ActivtyUseConfiguration` called `triggering` which contains the relative UUID of the activity triggering this one as well as resource consumption options. This value is filled automatically if the item has the `cachedFor` flag unless it is explicitly set to `false`.
If `triggering` is set in the usage configuration, then during the consumption process the system will also trigger the …
=> [#4061] Allow Cast Activity to trigger linked spells

dnd5e.mjs, module/applications/dice/_module.mjs, module/applications/dice/d20-configuration-dialog.mjs, module/applications/dice/damage-configuration-dialog.mjs, module/applications/dice/roll-configuration-dialog.mjs, module/dice/_module.mjs, module/dice/basic-roll.mjs, module/dice/d20-die.mjs, module/dice/d20-roll.mjs, module/dice/damage-roll.mjs, module/dice/dice.mjs, templates/dice/roll-buttons.hbs
Rebuilds `D20Roll` to inherit from `BasicRoll`. This involved a change to `BasicRoll` to give subclasses a way to modify message data before the message is created.
As part of this process some of the logic that originally existed in `D20Roll` has been moved to a new `D20Die` class. This includes the getters for determining whether a roll is a critical success or failure and applying advantage, minimums & maximums, and halfling lucky. This change isolates the behavior that is specific to rolling a d20 so that modules can potentially replace that die with their own (e.g. 2d10 or 3d6).
This PR does not cover converting any of the existing rolling methods over to the new API, they simply use the standalone `d20Roll` method and let it handle calling the new API. Future PRs will handle …
=> [#2138] Refactor `D20Roll` for new API, deprecate `d20Roll` method

module/data/item/background.mjs, module/data/item/class.mjs, module/data/item/container.mjs, module/data/item/equipment.mjs, module/data/item/feat.mjs, module/data/item/race.mjs, module/data/item/spell.mjs, module/data/item/subclass.mjs, module/data/item/templates/equippable-item.mjs, module/data/item/templates/physical-item.mjs, module/data/item/tool.mjs, module/data/item/weapon.mjs, module/documents/item.mjs
Moved various `_pre` and `_on` socket event handlers into item data models rather than on the item. All socket handlers have been removed from items except setting the initial identifier during `_preCreate`, performing activity rider updates in `_preUpdate` (though the implementation has been moved), and ending concentration within `_onDelete`.
=> [#2094] Move item socket event handlers into type data models

module/applications/actor/character-sheet.mjs, module/applications/actor/npc-sheet.mjs, module/applications/actor/sheet-v2-mixin.mjs, module/applications/dice/roll-configuration-dialog.mjs, module/dice/basic-roll.mjs, module/dice/d20-roll.mjs, module/dice/damage-roll.mjs, module/documents/actor/actor.mjs, module/enrichers.mjs
Re-implements `rollConcentration` and `rollDeathSave` using the new rolling APIs, and modified `rollDeathSave` so it calls `rollAbilitySave` rather than handling the roll itself.
Also reworked how initiative rolls are prepared, but due to the way in which ability rolls interact with Foundry core these don't fully support the new APIs. To better support this the `build` method on `BasicRoll` can now take `evaluate: false` in the process configuration, skipping the roll evaluation and message creation. This allows the `rollInitiativeDialog` method to use `build` for configuring its roll and calling the configuration hooks.
Added a `dnd5e.preConfigureInitiative` hook that is called for all initiative rolls including those from the combat tracker. This should allow some configuration, but …
=> [#2138, #3140] Re-implement concentration, death saves, & initiative

module/applications/actor/base-sheet.mjs, module/applications/dice/_module.mjs, module/applications/dice/roll-configuration-dialog.mjs, module/applications/dice/skill-tool-configuration-dialog.mjs, module/data/actor/templates/common.mjs, module/dice/d20-roll.mjs, module/dice/dice.mjs, module/documents/activity/check.mjs, module/documents/actor/actor.mjs, module/documents/actor/proficiency.mjs, module/documents/item.mjs, module/enrichers.mjs, templates/actors/character-sheet.hbs, templates/actors/npc-sheet.hbs
Merges the functionality ot skill & tool checks into a single method that takes advantage of the new rolling APIs. These new methods make use of a `buildConfig` callback that is called by `RollConfigurationDialog` during its `buildConfig` method. This allows for more extensive modifications of the configuration when the ability is changed.
Closes #1530
=> [#1530, #2138] Re-implement `rollSkill` and `rollToolCheck`

module/applications/dice/_module.mjs, module/applications/dice/attack-configuration-dialog.mjs, module/data/activity/attack-data.mjs, module/data/item/weapon.mjs, module/data/shared/uses-field.mjs, module/dice/basic-roll.mjs, module/dice/d20-roll.mjs, module/dice/dice.mjs, module/documents/activity/attack.mjs, module/documents/actor/actor.mjs, module/documents/item.mjs
Reworks `rollAttack` to use the new `build` method on `D20Roll` and implement a custom configuration application to support ammunition, attack modes, and mastery.
In the process this moves the preparation of ammunition options into `WeaponData` and reorders the logic for ammunition, attack mode, and mastery options to be easier to follow.
Closes #2138
=> [#2138] Re-implement `rollAttack` using new rolling APIs

module/documents/active-effect.mjs, module/documents/activity/cast.mjs
Makes the DC & Attack overrides on the Cast activity functional. It does this through the Spell Changes enchantment which uses a new syntax to apply directly to all Attack & Save activities on the spell.
The new syntax allows for modifying all activities of a certain type using the change key like `activity.attack.attack.bonus`, where `activity.attack` indicates this should change all attack activities and `attack.bonus` being the key path to the field to change. At the same time this also fixes some issues with applying enchantment changes directly to individual activities by ID.
Closes #4613
=> [#4061, #4613] Add Cast overrides, activity changes via enchanting

module/documents/activity/attack.mjs, module/documents/activity/damage.mjs, module/documents/activity/heal.mjs, module/documents/activity/mixin.mjs
Adds a step after the end of the activity usage that allows specific activity types to trigger a primary action. For example, this allows an `AttackActivity` to trigger its attack roll dialog immediately after the item is activated, rather than requiring a separate click in chat.
- `AttackActivity`: Triggers attack dialog
- `DamgeActivity`: Triggers damage dialog
- `HealActivity`: Triggers healing dialog
Adjusts the `dnd5e.postUseActivity` hook to be cancelable, allowing modules to prevent these subsequent actions. The new method is intentionally not awaited allowing `use` to return immediately rather than waiting for these actions to resolve.
=> [#4459] Add action that triggers automatically with activity use

module/data/item/templates/activities.mjs, module/documents/activity/mixin.mjs, module/documents/chat-message.mjs
Stores the data for any items deleted as part of the item usage process within the chat message `dnd5e.use.consumed` flag. This allows for entire items to be restored when the "Refund Resource" button is pressed in chat.
As part of this process the deleted item data previously stored in the `dnd5e.item.data` flag has been removed and a reference from that to the data in the consumed flag has been added, so all existing workflows should continue working.
These changes also allow for the Cast activity to be used on items that are consumed on empty such as spell scrolls.
Closes #4603
=> [#4603] Stored deleted items in consumed flag, add item restore

module/documents/actor/actor.mjs
Fixes issues noted in #4485 with actor's `_onUpdate` by adding a check for a HP-related update in the `data`.
=> [#4485] Check for HP-related update in `_onUpdate`

module/documents/activity/summon.mjs
By linking to the activity's parent UUID rather than the individual activity, linked summons (e.g. Primal Companion) will no longer import a duplicate linked creature for alternate summoning activities on the same item, such as summoning with or without a spell slot.
Unlinked summons (majority use case) are unaffected entirely as they always resolved by source actor UUID.
=> Associates linked summons with item rather than activity

lang/en.json, module/applications/actor/character-sheet-2.mjs, module/applications/actor/sheet-v2-mixin.mjs, module/data/activity/save-data.mjs, module/documents/activity/save.mjs, templates/actors/character-sheet-2.hbs, templates/actors/parts/columns/column-roll.hbs, templates/actors/tabs/creature-spells.hbs
Modifies `SaveActivity` to store a set of abilities rather than a single one that can be rolled to save. When multiple are selected if will display multiple buttons in chat to roll.
Closes #4192
=> [#4192] Support multiple save abilities to `SaveActivity`

packs/_source/classfeatures/paladin/paladin-features/lay-on-hands.json
Allows the paladin's Lay On Hands feature to actually roll healing, and scaling to use more than one point from the pool at a time.
Also adds a second activity called "Cure Disease and Poison" that consumes 5 points at a time from the pool, and also allows scaling do cure more than one disease in a single action.
=> Update Lay On Hands to roll healing

packs/_source/items/weapon/hammer-of-thunderbolts.json
This item was a mess.
- Fixed recovery being set to LR instead of Dawn.
- Fixed both activities consuming limited uses (neither should).
- Changed and renamed the save activity.
- Added two new activities: Ranged attack and the "ranged" saving throw. The ranged attack is the only activity that consumes a charge.
- Set the range of the weapon to 5 ft, and the range of the ranged attack to 20ft. Not possible to give it a 20/60 range.
- Added an effect for +4 STR and STR max raised to 30.
- Moved the template into the ranged saving throw.
=> Various fixes to Hammer of Thunderbolts

module/applications/actor/character-sheet-2.mjs, module/data/item/facility.mjs
Adds a range filter for the facility level requirement when using the Compendium Browser and automatically adds a restriction for that when opening using the "Add Facility" control on the sheet.
Also adds a negative filter restriction for the non-selected type, so you cannot use filters to display Special facilities when clicking the add basic facility button and vice versa.
Closes #4669
=> [#4669] Add level filter for facilities in Compendium Browser

module/data/item/templates/physical-item.mjs
Turns out we can't use `Item5e#render` for this since operation context doesn't make it to `ClientDocument#render` options. It's not clear whether this is intentional or not though.
=> Fix some v13 errors. Respect options.render when calling PhysicalItemTemplate#_renderContainers.

module/canvas/ability-template.mjs
`PlaceableObject`, from which `AbilityTemplate` (via `MeasuredTemplate`) inherits, has a `getSnappedPosition` method. When dragging the template preview, it is preferable that the snapped position is determined by using the template's own `getSnappedPosition` method instead of the layer's method. This allows modules (e.g., my Walled Templates module) to affect snapping of the specific template associated with a given spell. 
Note that by default, `MeasuredTemplate#getSnappedPosition` just calls `this.layer.getSnappedPoint` so this should not affect anything for a default setup.
=> Use the template's `getSnappedPosition` method when dragging preview

lang/en.json, module/applications/activity/activity-usage-dialog.mjs, module/documents/activity/mixin.mjs, templates/activity/activity-usage-consumption.hbs
Updates activities to consume legendary actions automatically if their activation type is set to Legendary Action, they are being used on an NPC actor, and they don't have existing legendary action consumption configured using the old resource setup.
Closes #4718
=> [#4718] Automatically consume legendary actions

module/data/abstract.mjs, module/data/actor/npc.mjs, module/documents/combat.mjs, module/documents/combatant.mjs
Automatically resets NPCs legendary actions count at the start of a new combat and at the end of the actor's turn. The reset is at the end of the turn to avoid issues with using legendary actions between the end of the previous combatant's turn and this one.
This works using a new `_recoverUses` method on `Combat5e` that is called by `startCombat` and `nextTurn`. It is passed a series of recovery periods with either `true` (indicating that this should be recovered for all combatants) or a specific combatant (indicating that this should only be recovered for that specific combatant). At the start of combat the `encounter` recovery is called for all combatants, and on `nextTurn` the `turnEnd` is called for the previous combatant and `turnStart` is called for the incoming combatant.
This …
=> [#2359] Automatically reset legendary actions during combat

lang/en.json, module/documents/actor/actor.mjs, module/settings.mjs
Adds a new property to `InitiativeRollOptions` that allows using a flat value rather than rolling. This pairs with a new setting that controls whether initiative should always be rolled, whether GM-controlled NPCs should use their initiative score instead, or whether all initiative should be handled using scores.
Closes #4812
=> [#4812] Add setting to use initiative scores rather than rolls

wiki/Active-Effect-Guide.md
Closes #4778. Closes #4820.
Also reordered the attack types - not alphabetical but I think most enumerate them weapon before spell and melee before ranged.
=> [#4778, #4820] Fix minor issues on AE wiki page.

lang/en.json, less/v1/chat.less, less/v2/journal.less, module/enrichers.mjs
Adds support for variable damage types when rolling damage through a damage enricher as well as multiple damage parts.
To indicate variable damage types, the explicit `type` key must be used when writing the enricher and the different types must be separated by a pipe (`|`) character:
```
[[/damage 2d6 type=fire|cold]]
```
To specify multiple damage parts the enricher config is split by an amperand (`&`), with each side supporting its own formula and damage types:
```
[[/damage 1d6 fire & 1d6 cold]]
[[/damage 1d6 fire & 1d6 cold average]]
```
Any configuration options that apply to the whole enricher can be placed anywhere in the configuration.
If the average option is used and there are exactly two damage parts, then they will be written as "A plus B", otherwise they will be written "A …
=> [#3357] Support variable types & multiple damage parts in enricher

lang/en.json, less/v2/journal.less, module/applications/actor/npc-sheet-2.mjs, module/config.mjs, module/data/actor/npc.mjs, module/utils.mjs, templates/actors/embeds/npc-embed.hbs
Adds a new option when embedding NPC actors that allows displaying the NPC's statblock (in 2024 style) rather than the description:
```
@Embed[Compendium.dnd5e.monsters.Actor.8aCTKP5qaBPFOqxM statblock]
```
Embeds also support two-column layout for larger statblocks. This is handled by using the `double-column` class on the embed.
=> [#3798] Add embeddable NPC statblocks

module/config.mjs, module/data/item/weapon.mjs, module/enrichers.mjs
Adds the ability for attack and damgae enrichers to be linked to a specific activity, allowing them to fetch their formulas and any other information directly from that activity and to roll that activity when clicked, rather than using the generic rolling.
This can be done in two ways, either by explicitly stating the activity ID: `[[/attack activity=RLQlsLo5InKHZadn]]`, or by not specifiying a formula and letting the system find the first matching activity: `[[/attack]]` or `[[/damage average]]`.
This also adds support for specifying the attack mode in the enricher. For attack enrichers this just controls what attack mode is selected in the dialog by default (or used if the dialog is bypassed), and for damage enrichers this adjusts the damage formula if it changes based on the attack …
=> [#2568, #3355] Add activity linking for attack & damage enrichers

module/applications/actor/sheet-v2-mixin.mjs, module/applications/api/application-v2-mixin.mjs, module/documents/activity/mixin.mjs, module/documents/mixins/document.mjs, module/documents/mixins/flags.mjs, module/documents/mixins/pseudo-document.mjs, system.json
I tidied up a lot of our loose mixin definitions to use named classes and functions in order to improve intellisense. Aside from that, there's only some bits of type tidying and some adjustments for line length.
It introduces some rightward shift, which is unfortunate, but I don't think it can be avoided since you can't name arrow functions when defining them.
I didn't convert `module/applications/dialog-mixin.mjs` since it seemed to only be used by a couple of dialogs that we haven't yet converted to App V2. And the same for `module/applications/actor/sheet-mixin.mjs`, which will be moved into our App V2 mixins when we move the Actor sheets to App V2.
Pretty much all the changes are just whitespace indentation, but let me know if you have any objections to this technique, or suggestions.
=> Tidy up mixin definitions

module/data/shared/uses-field.mjs, module/dice/basic-roll.mjs, module/documents/activity/attack.mjs
Splits the `build` method on `BasicRoll` into three parts:
1. `buildConfigure`: Applies keybindings, calls the `preRoll` hook, displays the configuration dialog, and calls the `postRollConfiguration` hook.
2. `buildEvaluate`: Evalutes the rolls if `evaluate` is `true`.
3. `buildPost`: Sets the `originatingMessage` flag and posts a message to chat.
The `build` method now calls these three methods in turn.
This process now also adjust `config.hookNames` to incude the empty value rather than using a local variable so the final hook names can be used elsewhere, and saves the created chat message into the message configuration so it can be referenced after the fact.
Closes #4751
=> [#4751] Split `BasicRoll#build` into three parts

lang/en.json, module/data/activity/attack-data.mjs, module/enrichers.mjs
Adds an new formatting option to the attack and damage enrichers that displays them in a fashion similar to full NPC stat blocks:
```html
<em>Melee Weapon Attack:</em> [[/attack]], reach 15 ft.<strong>,</strong> one target. <em>Hit:</em> [[/damage average]] damage.
[[/attack format=extended]]. [[/damage format=extended]].
```
The formatting of the generated content will adjust slightly based on what rules version is being used. This will use the rules version defined in the containing actor if present, then in the containing item, and if neither is found then it will use the global rules setting.
=> [#4828] Add extended formatting option to attack & damage enrichers

module/documents/activity/mixin.mjs
I had a use case for just getting the return of the usage without the follow-up actions.
Note: I considered `followup` as the name for the property but did not want to clash with a possible future feature. Open to suggestions, however.
=> Add parameter for preventing subsequent actions

module/applications/actor/sheet-v2-mixin.mjs, module/applications/components/checkbox.mjs, module/applications/components/proficiency-cycle.mjs, module/applications/components/slide-toggle.mjs, module/applications/item/sheet-v2-mixin.mjs, module/applications/mixins/sheet-v2-mixin.mjs
Modifies `ProficiencyCycleElement` to extend core's form input element directly, and modify `SlideToggleElement` to inherit from `CheckboxElement` and take advantage of most of its code.
Also ensures all three elements are registered with AppV1 actor and item sheets for form submission.
Closes #4840
=> [#4840] Switch custom elements to extend `AbstractFormInputElement`

module/enrichers.mjs
Adds an `activity` option to the lookup enricher that takes an activity ID and allows for grabbing roll data directly from an activity on an item, rather than from the item's roll data:
```
[[lookup @target.template.size activity=dnd5eactivity000]]
```
Closes #4859
=> [#4859] Add option to use lookup enricher on activity

lang/en.json, module/applications/activity/cast-sheet.mjs, module/data/activity/cast-data.mjs, module/documents/activity/cast.mjs, templates/activity/parts/cast-details.hbs
Adds a spellcasting ability override to the cast activity that then sets `system.ability` in the spell enchantment.
Closes #4851
=> [#4851] Add option to override casting ability in `CastActivity`

module/data/actor/npc.mjs
Adds a `dnd5e.renderNPCStatBlock` hook that provides the actor, collection of HTML elements, and embedding configuration for modification before the stat block is fullying inserted.
Closes #4827
=> [#4827] Add hook for when NPC stat blocks are rendered

lang/en.json, less/v2/inventory.less, module/applications/activity/activity-sheet.mjs, module/applications/actor/base-sheet.mjs, module/applications/actor/sheet-v2-mixin.mjs, module/applications/item/item-sheet-2.mjs, module/applications/shared/movement-senses-config.mjs, module/config.mjs, module/data/advancement/scale-value.mjs, module/data/item/race.mjs, module/data/item/templates/activated-effect.mjs, module/data/item/templates/physical-item.mjs, module/data/item/weapon.mjs, module/data/shared/range-field.mjs, module/data/shared/target-field.mjs, module/utils.mjs, templates/activity/columns/activity-column-range.hbs, templates/actors/tabs/creature-spells.hbs, templates/advancement/scale-value-config.hbs
Adds two new utility methods, `formatDistance` and `formatWeight` that perform proper localized formatting of those two unit types. By default these use the standard javascript unit localization, but the config object can be used to override this or provide custom localization for units that javascript doesn't support (such as tons).
=> [#3958] Add formatters for distance and weight units

lang/en.json, module/data/activity/base-activity.mjs, module/data/activity/fields/consumption-targets-field.mjs, module/data/actor/npc.mjs, module/data/item/templates/activities.mjs, module/data/shared/uses-field.mjs
During data preparation for the uses field generates a label that matches the style of the NPC stat blocks, whihc is then used when embedding them. This will use the item uses if available and fall back to the activity uses otherwise. Any uses recovery that isn't normally used for NPCs will not get a label.
=> [#3798] Add limited uses labels for NPC stat block actions

module/data/fields/_module.mjs, module/data/fields/advantage-mode-field.mjs, module/data/shared/roll-config-field.mjs
Adds a new `AdvantageModeField` which tracks the number of effects that apply advantage and disadvantage. The final value is then either -1 if only disadvantages exist (including the initial value), 1 if only advantages exist (including initial value), otherwise 0 if there are both advantages and disadvantages (including initial value).
TODO: Add +5 (-5) to the skill's passive if the actor has advantage (disadvantage).
=> Track advantage modes

dnd5e.mjs, lang/en.json, module/applications/activity/activity-sheet.mjs, module/applications/item/item-sheet-2.mjs, module/config.mjs, module/data/activity/base-activity.mjs, module/data/shared/target-field.mjs, module/enrichers.mjs, module/utils.mjs, templates/items/parts/item-activation.hbs, templates/shared/fields/field-targets.hbs
Adds the targeting information to the extended attack enricher when using the 2014 rules (e.g. "one target"). Two additional localization features were added to support this.
First, `formatNumber` now takes the `spellOut` option which will attempt to write the number out if the current language provides a written form (e.g. `one` instead of `1`). The does not fall back to the default language, so a language where this doesn't make sense can simply not provide the appropriate localization keys and it will just use the numeric form instead. For English this is set up to spell out the numbers 1–9 only.
Second, the targeting localization was modified to include counted plural localizations so now the system will be able to display "2 creatures" rather than "2 creature" when it displays target …
=> [#4384, #4828] Adds plural targets, add target to attack enricher

lang/en.json, module/applications/actor/character-sheet.mjs, module/applications/actor/npc-sheet.mjs, module/config.mjs, module/data/actor/npc.mjs
Adds a new trait for feature items that controls whether that feature is considered passive for grouping on PC & NPC sheets and on NPC stat blocks. When checked, the feature will always be treated as a passive feature regardless of the activities it has.
Closes #4846
=> [#4846] Add "Passive Trait" property to features for group control

lang/en.json
Renames `UtilityActivity` to use an imperative verb for its name to match the other activity types. Doesn't change the underlying type from `utility`.
Closes #4826
=> [#4826] Rename "Utility" activity to "Use"

dnd5e.mjs, lang/en.json, module/applications/actor/base-sheet.mjs, module/applications/shared/movement-senses-config.mjs, module/config.mjs, module/data/actor/character.mjs, module/data/actor/npc.mjs, module/data/item/race.mjs, module/data/item/templates/physical-item.mjs, module/data/shared/movement-field.mjs, module/data/shared/senses-field.mjs, module/data/shared/target-field.mjs, module/documents/actor/actor.mjs, module/settings.mjs, module/utils.mjs
Sets the default value for movement, senses, and grid units to meters if metric length units are enabled in settings.
Updates newly created scenes setting them to the correct units and adjusting the grid distance (so using default settings, scenes in metric mode will be created with a grid of 1.5 m, instead of 5 ft).
Resolves #2071
=> [#2071] Default to metric length units for movement and senses

lang/en.json, module/enrichers.mjs
=> [#4866] Display nicer text for a dc-less passive skill enricher

module/utils.mjs
Repro:
- Disable canvas in Foundry settings
- Use a "save" activity from an actor's sheet
- Click the "DC \<X\> \<Y\> Saving Throw" button in the resulting chat card
=> Avoid crash when getting scene targets when canvas is disabled

module/data/actor/templates/common.mjs, module/utils.mjs
By ~~changing `simplifyBonus` to always return the total of the deterministic terms, (and~~ moving `mod` calculation prior to any bonus determination ~~)~~, something like `system.bonuses.abilities.save | Add | @abilities.cha.mod` will actually display the appropriate bonus on the sheet. ~~All non-deterministic terms are ignored still for sheet display.~~
Update: Changing `simplifyBonus` is actually not necessary for the _main_ functionality of this change, which is to have ability mod bonuses show up on the sheet. It may still be a worthwhile change, but not as part of this PR.
=> Show ability-mod-using bonuses on sheet

module/data/activity/base-activity.mjs
Currently the system uses `parseInt`, which means a bonus such as `0 + 123` gets ignored because `parseInt("0 + 123")` is `0`.
iirc there was a reason we had this small validation step so I changed it for `Number` instead, but it would otherwise seem to me that we could just change to `bonus !== "0"`.
=> [#4924] Change `parseInt` to `Number`

wiki/Modifying-Your-Game-with-Scripts.md
The `icon` property, at least, is required. Otherwise damage traits applications cannot render. Regardless, no reason not to include all properties in the example.
=> Update damage types example

less/v2/forms.less, module/applications/actor/sheet-v2-mixin.mjs, module/applications/components/checkbox.mjs, module/applications/components/inventory.mjs, module/applications/item/item-compendium.mjs, module/applications/item/item-directory.mjs, module/applications/item/item-sheet.mjs, module/applications/item/sheet-v2-mixin.mjs, module/applications/mixins/sheet-v2-mixin.mjs, module/data/item/consumable.mjs, module/data/item/weapon.mjs, templates/actors/parts/actor-classes.hbs, templates/actors/tabs/character-details.hbs, templates/shared/inventory2.hbs
- Closes #4381 
- Closes #4809 
- Closes #4364 
This brings the Item sheet in-line with the V2 Actor sheet in terms of consistency around editability in Edit vs. Play mode. Form fields are now disabled in Play mode, and will now show any enchanted values, where before it was not possible to see them. Switching the sheet to edit mode will make the fields editable, with their source values displayed, avoiding the issue of potentially persisting enchantment-modified values, or making changes that do not visually update due to being enchantment-modified.
The sheets will now default to opening in Edit mode also, where appropriate, as most contexts where the Item sheet is opened imply editability (e.g. the right-click context menu on Actor sheets is labelled 'edit', and opening an Item from the …
=> Improve consistency of Item Sheet display

module/data/fields/advantage-mode-field.mjs
A continuation of #4838.
Modes:
- Add: Adds one source of advantage (1) or disadvantage (-1).
- Upgrade: Makes it impossible to have disadvantage (0, 1).
- Downgrade: Makes it impossible to have advantage (-1, 0).
- Multiply: Does nothing.
- Override: Forces one advantage mode regardless of other sources, downgrade, or upgrades.
- Custom: is custom.
=> More advantage mode coverage

lang/en.json, module/applications/activity/attack-sheet.mjs, module/config.mjs, module/data/activity/attack-data.mjs, module/data/activity/base-activity.mjs, module/data/item/weapon.mjs, module/enrichers.mjs
Reworks how activities fetch their list of available attack types so they can display "Default (melee or ranged)" in the attack activity dialog if relevant (such as thrown melee weapons).
Adjust how that list of valid attack types is generated to that natural weapons can have ranged attacks so long as they have a range value. To ensure modifiers are properly supported this adds a new attack mode of "Ranged" for natural weapons that don't have the thrown property.
Fixes a bug with extra melee critical damage dice being applied even when the weapon is thrown.
Also fixes a bug causing the "reach" migration to be applied when switching weapon modes.
=> Allow natural weapons to make ranged attacks without "thrown"

lang/en.json, less/v2/chat.less, module/applications/activity/activity-usage-dialog.mjs, module/applications/actor/npc-sheet-2.mjs, module/data/actor/npc.mjs, module/documents/activity/mixin.mjs, module/documents/chat-message.mjs, templates/actors/npc-sheet-2.hbs, templates/actors/npc-sheet.hbs
failed by an NPC so long as that NPC has remaining legendary resistances. If a save has been resisted, it is displayed as a successful roll and an indicator is displayed beneath.
Closes #4863
=> Adds a new "Resist" button beneath saving throws that have been

module/documents/actor/actor.mjs, module/enrichers.mjs, templates/chat/request-card.hbs
A single save enricher can now specify multiple abilities:
```html
[[/save ability=strength/dexterity]]
[[/save str dex]]
```
This will result in an enriched link for each ability as well as a request roll link that posts a single chat card with a button for each ability.
=> [#4898] Add support for multiple abilities in single save enricher

module/enrichers.mjs
A single check enricher can now specify multiple skills or toools:
```
[[/check skill=acr/ath dc=15]]
[[/check acrobatics athletics sleightOfHand 15]]
[[/check ability=str skill=dec/per dc=15]]
[[/check tool=thief skill=slt]]
```
The `passive` option doesn't work if multiple skills or tools are provided, nor do custom labels.
Closes #4898
=> [#4898] Add support for multiple skills/tools in single enricher

module/data/actor/npc.mjs
Populates the gear least within NPC embeds with equipment that:
- Has a quantity of at least 1
- Doesn't have the "natural" subtype (weapons or armor)
=> [#3798] Add gear to embedded NPCs

dnd5e.mjs, lang/en.json, less/v2/chat.less, module/data/_module.mjs, module/data/abstract/_module.mjs, module/data/abstract/chat-message-data-model.mjs, module/data/chat-message/_module.mjs, module/data/chat-message/fields/_module.mjs, module/data/chat-message/fields/deltas-field.mjs, module/data/chat-message/turn-message-data.mjs, module/documents/chat-message.mjs, module/documents/combatant.mjs, module/utils.mjs, system.json, templates/chat/turn-card.hbs
Introduces a new chat message type for communicating combat recovery information and offering combat-related controls. At this point the message just displays a summary of recovery changes that occured at the start of combat, the start of a turn, or the end of a turn.
This introduces a new `turn` chat message type which stores information on the relevant combatant, what kind of combat change event triggered the message, and deltas for any changes made to the actor or their items.
=> [#2359, #4799] Add new turn chat message

lang/en.json, module/applications/actor/config/traits-config.mjs, module/applications/actor/sheet-v2-mixin.mjs, module/applications/advancement/trait-config.mjs, module/config.mjs, module/data/actor/character.mjs, module/data/actor/npc.mjs, module/data/actor/templates/traits.mjs, module/documents/actor/trait.mjs, templates/apps/parts/trait-list.hbs, templates/apps/parts/traits-list.hbs
Adds an "All Languages" option. If selected, then only that option will show an all other language proficiencies will be hidden (custom languages and ranged communication will still be displayed as normal). This includes some broader changes that should work as the basis for adding this to other trait types (such as resistance to all damage).
Also modifies how the labels for languages are created to match modern stat blocks that display grouped languages next to the group name (e.g. "Primordial (Terran)"). This also handles some checks to prevent redundant information, such as if you have Primordial proficiency as well as Terran proficiency, it will only show the top-level group and not its children.
=> [#3798, #4644] Add "All Languages", group primordial languages

lang/en.json, less/v2/apps.less, less/v2/chat.less, module/applications/actor/npc-sheet.mjs, module/config.mjs, module/data/abstract.mjs, module/data/actor/npc.mjs, module/data/chat-message/turn-message-data.mjs, module/documents/combat.mjs, module/documents/combatant.mjs, templates/chat/turn-card.hbs
Adds three new activation types in a new "Combat" section: "Start of Encounter", "Start of Turn", and "End of Turn". These activation types will display in the combat chat message with a "Use" button to be easily activated. They also have a tooltip to display the full item description on hover.
The turn chat message stores relative UUIDs of the activiations in its data model to avoid having to check all of the actor's items every time the chat message is rendered.
Closes #4861
=> [#4861] Add combat activation types that display in turn message

lang/en.json, less/dnd5e.less, less/v2/advancement.less, module/applications/advancement/advancement-manager.mjs, module/applications/advancement/subclass-flow.mjs, module/data/advancement/_module.mjs, module/data/advancement/subclass.mjs, module/data/fields/local-document-field.mjs, module/documents/advancement/subclass.mjs, templates/advancement/advancement-visualizer.hbs, templates/advancement/subclass-flow.hbs
Detects items added or removed during the advancement process and adds "synthetic" advancement steps if necessary for those items. This fixes the issue that prevents subclasses from automatically adding their initial features.
Adds a `AdvancementVisualizer` application that can be used to help debugging the advancement steps.
Changes subclass advancement to allow for selection of the subclass during the advancement process.
Resolves #1795
=> [#1795] Add ability for items added with through advancement to trigger their own advancements

lang/en.json, less/v2/forms.less, module/applications/activity/activity-sheet.mjs, module/applications/advancement/_module.mjs, module/applications/advancement/advancement-config-v2.mjs, module/applications/advancement/hit-points-config.mjs, module/applications/advancement/hit-points-flow.mjs, module/applications/api/_module.mjs, module/applications/api/pseudo-document-sheet.mjs, module/documents/activity/mixin.mjs, module/documents/actor/actor.mjs, module/documents/advancement/advancement.mjs, module/documents/advancement/hit-points.mjs, module/documents/mixins/pseudo-document.mjs, templates/advancement/advancement-controls-section.hbs, templates/advancement/hit-points-config.hbs, templates/advancement/hit-points-flow.hbs, templates/advancement/parts/advancement-controls.hbs
Creates `AdvancementConfigV2` based on `ApplicationV2` and converts `HitPointsConfig` to use the new application and styles. Shared functionality between this application and the activity sheets has been moved into a new `PseudoDocumentSheet` class to avoid duplication.
Also uses the `PseudoDocumentMixin` for advancement to get a number of improvements that were added for activities.
=> [#4708] Redesign `AdvancementConfig` & `HitPointsConfig` for V2

lang/en.json, less/v1/advancement.less, less/v2/advancement.less, module/applications/advancement/advancement-manager.mjs, templates/advancement/advancement-manager.hbs
Converts `AdvancementManager` to use `ApplicationV2` and V2 system styles. Because old V1 advancement flow applications are embedded within this application, there are some V1 classes added to ensure that styling of old flows aren't completely broken.
This also takes a number of soft-private properties and methods on the manager and makes them hard-private.
=> [#4708] Convert `AdvancementManager` to V2 app & styles

lang/en.json, module/applications/advancement/ability-score-improvement-flow.mjs, module/applications/advancement/item-choice-flow.mjs, module/data/item/feat.mjs, templates/items/details/details-feat.hbs
Adds "Repeatable" data to the prerequisite data on `feat` items. Repeatable features can be selected more than once inside an item choice advancement.
Closes #4958
=> [#4958] Allow features to be repeatable in item choice

module/config.mjs, module/data/item/feat.mjs
Adds advancement data to `feature` items and allows them to use the `ASIAdvancement`. Holding off on more advancement types until more testing has been performed to ensure granting items will work properly.
Closes #3695
=> [#3695] Add ASI Advancement support to feature items

module/config.mjs, module/data/actor/templates/attributes.mjs, module/utils.mjs
When applying exhaustion speed reduction to an actor, this ensures that the reduction matches the units defined on the actor. This uses a new `convertLength` method for converting the value defined in config from the default imperial units (e.g. `ft`) into whatever units are used for the actor.
Closes #4215
=> [#4215] Ensure exhaustion speed reduction matches movement units

lang/en.json, module/config.mjs, module/data/item/container.mjs, module/settings.mjs, module/utils.mjs, templates/items/details/details-container.hbs, templates/shared/inventory.hbs
Reworks container capacity to allow for defining more than one capacity type (so a container can define a maximum number of items and a maximum weight). Weight capacity now accepts actual units so the weight can be measured in kilograms or tonnes if desired.
Adds a volume capacity type to containers for measuring in cubic feet or liters. This includes the addition of `volumeUnits` to the configuration and a "Use Metric Volume Units" setting to match the other units settings.
Closes #3629
Closes #4142
=> [#3629, #4142] Add units to container capacity, add volume capacity

lang/en.json, module/applications/actor/rest/base-rest-dialog.mjs, module/applications/actor/rest/long-rest-dialog.mjs, module/applications/actor/rest/short-rest-dialog.mjs, module/config.mjs, module/documents/actor/actor.mjs, module/utils.mjs
Updates the rest message to select the proper plural form of Hit Points and Hit Dice to match the number recovered.
Also adjusts the flavor to automatically display the rest time in the message flavor, rather than relying on hard-coded labels for each rest variant. This ensures the flavor will properly display the rest time even if it doesn't exactly match the default values.
In order to support this as well as improve other time-based localization in the future, this PR adds two new utlity methods:
- `convertTime` converts a time from one set of units to another. It will also attempt to pick the best unit automatically if the `to` units are not defined, selecting the largest unit that can fully represent the value (with some wiggle room so it will display 90 minutes, rather than 1.5 …
=> [#3958] Improve localization of rest messages

module/applications/actor/sheet-v2-mixin.mjs, templates/actors/tabs/creature-spells.hbs
Displays the number of remaining uses/total uses on the spells tab for spells derived from the Cast activity. It will display activity uses first if activity consumption is set, and then it will display item uses if item consumption is set.
=> Display activity uses on spells tab for spells from Cast activity

module/applications/actor/character-sheet-2.mjs, module/applications/compendium-browser.mjs, templates/actors/character-sheet-2.hbs, templates/actors/parts/actor-classes.hbs
Shows the "Select Class" button on the features tab of a character sheet whenever the sheet is in edit mode, even if the character already has a class. When clicking on this, it will show a list of classes excluding any they already have, allowing players to easily add an additional class.
To support the extra filters, the Compendium Browser has been modified to support arbitrary filters in the `locked` filters section. These additional filters won't be displayed in the UI and cannot be controled by the user, but will allow for additional control when programatically bringing up the browser. In this case the browser filters out any classes that match the identifiers for the classes already on the character's sheet.
Closes #4249
=> [#4249] Add "Select Class" pill when in editing mode

lang/en.json, module/applications/actor/character-sheet-2.mjs, module/applications/actor/npc-sheet-2.mjs, module/applications/award.mjs, module/data/actor/character.mjs, module/data/actor/group.mjs, module/data/actor/npc.mjs, module/enrichers.mjs, module/utils.mjs, templates/actors/character-sheet-2.hbs, templates/actors/group-sheet.hbs, templates/actors/tabs/group-members.hbs, templates/apps/award.hbs
Formats the NPC XP to display an alternate value if the creature has a lair.
Closes #3798
=> [#3798] Display in-lair XP on embedded NPC stat blocks

module/applications/actor/character-sheet-2.mjs, module/data/activity/save-data.mjs
Closes #5006 
`character-sheet-2.mjs` change fixes bug where sheet couldn't render if a favorited spell's Save activity had `Set([''])` as its `save.ability` property (which could be caused by migrating a poorly configured 3.x save item).
`save-data.mjs` change makes it so that the empty string is considered equally as invalid as a missing or `null` value (which should be the case - a 3.x item missing the save ability stores it as `''`).
=> [#5006] Fix issues around misconfigured save abilities

lang/en.json, less/v1/advancement.less, module/applications/advancement/ability-score-improvement-flow.mjs, module/documents/advancement/ability-score-improvement.mjs, templates/advancement/ability-score-improvement-flow.hbs
In the 2024 rules ability score improvement is presented as: "Take the Ability Score Improvmeent Feat or another feat". This adjusts the interface of the ASI advancement when using the modern rules to hide the ASI interface unless the "Ability Score Improvement Feat" is checked. This change will improve the experience of half-feats because they won't be presented with two ASI interfaces in a row.
Also ignores the "Allow Feats" setting when using the 2024 rules because they are no longer an optional rule.
=> [#3695] Adjust ASI advancement in modern rules to be feat-first

lang/en.json, module/applications/journal/class-page-sheet.mjs, module/utils.mjs
Adds an "Ability Score Improvement" description to class journal pages using either the 2014 or 2024 rules text with the proper levels filled.
Closes #4973
=> [#4973] Add auto-generated ASI description to class journals

lang/en.json, module/applications/actor/vehicle-sheet.mjs, module/applications/item/item-sheet-2.mjs, module/config.mjs, module/data/item/equipment.mjs, module/data/item/feat.mjs, module/data/item/templates/mountable.mjs, module/data/item/weapon.mjs, templates/items/details/details-feat.hbs, templates/items/details/details-mountable.hbs, templates/items/parts/item-mountable.hbs
- Move `cover` from `MountableTemplate` to `FeatData` since feats are the only item type that display this data on vehicles
- Add "Vehicle Feature" type for features and display a cover field if this type is selected
- Remove `armor` from `MountableTemplate` and define directly on `WeaponData`, since `EquipmentData` already has armor
- Move to using localization prefixes for mountable labels
- Change cover labels shown on vehicle sheet to remove distinction between `0` and `null` values
Closes #4929
Closes #4931
=> [#4929, #4931] Fix mountable data models, add cover to feat sheet

lang/en.json, less/v2/character.less, module/applications/actor/api/base-config-sheet.mjs, module/applications/actor/base-sheet.mjs, module/applications/actor/config/death-config.mjs, module/data/actor/character.mjs, module/data/actor/npc.mjs, module/documents/actor/actor.mjs, templates/actors/character-sheet-2.hbs, templates/actors/config/death-config.hbs
Closes #4790.
Character sheet in edit mode:
=> [#4790] Death save bonus and config

lang/en.json, module/applications/activity/activity-sheet.mjs, module/applications/item/item-sheet-2.mjs, module/config.mjs, module/data/abstract.mjs, module/data/activity/fields/consumption-targets-field.mjs, module/data/actor/npc.mjs, module/documents/activity/mixin.mjs, module/documents/combat.mjs, module/documents/combatant.mjs, templates/items/details/details-feat.hbs, templates/items/feat.hbs, templates/shared/fields/field-uses.hbs
Introduces five new uses recover periods relating to combat:
- `encounter`: Recovered at the start of combat
- `turnStart` & `turnEnd`: Recovered once per round at the start or end of a specific combatant's turn
- `turn`: Recovered at the start of all combatant's turns
- `initiative`: Recovered when an actor rolls initiative
First first four (but not `initiative`) are special "combat" recovery types, which changes their behavior outside combat in two ways:
1. They are automatically recovered at the end of combat
2. They will not be consumed by default if combat isn't occuring
The second point means that if an activity is consuming item or activity uses and the only recovery periods are combat periods, then the consumption button will be unchecked by default.
Closes #3214
Closes #4738
=> [#3214, #4738] Add combat-related usage recovery periods

lang/en.json, less/v2/chat.less, module/data/chat-message/_module.mjs, module/data/chat-message/fields/deltas-field.mjs, module/data/chat-message/rest-message-data.mjs, module/data/chat-message/turn-message-data.mjs, module/documents/actor/actor.mjs, module/utils.mjs, system.json, templates/chat/parts/card-deltas.hbs, templates/chat/rest-card.hbs, templates/chat/turn-card.hbs
Adds a new `rest` chat message type that matches the `turn` type and displays more information on the resources recovered during the rest including item uses and spell slots.
Expands `getHumanReadableAttributeLabel` with support for fetching labels for activity & item attributes.
Closes #3788
=> [#3788] Add enhanced rest chat message with recovery info

module/utils.mjs
Closes #5040 
Missing `.split(".")` meant that something like `activities.<id>.uses.spent` was being improperly parsed as `activityId = 'c'` etc, so the full path would be returned instead of the actual label. Can be seen if an activity has recovery during rests with the new rest card.
=> [#5040] Fix human readable attribute labels for activities

module/data/actor/character.mjs, module/data/actor/npc.mjs, module/data/actor/templates/attributes.mjs, module/data/actor/templates/common.mjs, module/data/shared/roll-config-field.mjs, templates/actors/character-sheet.hbs, templates/actors/npc-sheet-2.hbs, templates/actors/npc-sheet.hbs, templates/actors/tabs/character-details.hbs
(Built on top of #4890.)
Adds `system.abilities.<abilityId>.check.roll` and `.save.roll` objects.
Moves the derived `abilities.<abilityId>.save` value into `.check/.save.value` with a `toString` method for the deprecation period.
(Also removes the `ability` property from the `attributes.death` object.)
TODO:
=> Add advantage modes to `abilities` objects

module/applications/activity/attack-sheet.mjs, module/applications/advancement/advancement-selection.mjs, module/applications/token-config.mjs, module/data/abstract.mjs, module/data/actor/character.mjs, module/data/actor/npc.mjs, module/data/actor/templates/attributes.mjs, module/data/actor/templates/creature.mjs, module/data/actor/templates/traits.mjs, module/data/actor/vehicle.mjs, module/data/item/templates/action.mjs, module/data/shared/movement-field.mjs, module/data/shared/senses-field.mjs, module/documents/actor/actor.mjs, module/documents/token.mjs
Moves skill, tool, armor class, initiative, spellcasting ability, condition immunity, and scale value preparation into data models. This leaves only spellcasting preparation in the main actor class.
=> [#2094] Move actor data preparation into data models

module/applications/components/inventory.mjs, module/applications/item/item-compendium.mjs, module/applications/item/item-directory.mjs, module/applications/mixins/sheet-v2-mixin.mjs
- Closes #5049
- 'View' option for item context menus is now always visible, instead of only visible when the user lacks ownership, allowing users to opt-into exactly which mode they intend when opening the item sheet.
- Creating a new item now renders the sheet in Edit mode.
- Opening items from the sidebar or compendium packs will default to Edit mode, but will remember the chosen mode for the session.
=> [#5049] Add view option to item context menus.

dnd5e.mjs, module/applications/_module.mjs, module/applications/chat-log.mjs, module/documents/chat-message.mjs
Stores the state of each chat tray present in a given chat message as well as their collapsed state, and then reuses these details when re-rendering the message.
Because of the way the chat log re-renders messages, the state is stored in the `updateMessage` method on a new custom `ChatLog5e` class.
Closes #4548
=> [#4548] Save chat tray state between message renders

dnd5e.mjs, module/documents/_module.mjs, module/documents/journal-entry-page.mjs
Adds a new `JournalEntryPage5e` with a `getRollData` method that provides the journal entry's name and flags as well as the page's name, flags, and system data.
Also fixes a bug with the `[[lookup]]` enricher causing it to throw an error if used on a document that doesn't provide the `getRollData` method.
Closes #4408
=> [#4408] Add roll data to journal entry pages

module/documents/item.mjs
It probably isn't safe to use the Cast activity for spells scrolls created from world or items on actors, but for ones in compendiums it should be safe. This adds a new method that is called if the provided spell is inside a pack.
Closes #4623
=> [#4623] Add `createScrollFromCompendiumSpell` that uses Cast

dnd5e.mjs, lang/en.json, less/v2/apps.less, module/applications/combat/combat-tracker.mjs, module/documents/combat.mjs, module/documents/combatant.mjs
Adds automatic grouping to the initiative tracker. This will group any combatants with the same initiative and the same base actor into a group.
Groups are displayed as collapsible sections in the combat tracker that use the name from the base actor's prototype token. It lists the number of combatants in the group, and when one of the group members is active it displays how far through the group that actor is.
Currently only offers the one grouping mode, but could be expanded in the future to support different grouping such as splitting it into "friendly" and "hostile" groups.
Also works in V13:
Closes #3667
=> [#3667] Add grouping to initiative tracker

.eslintrc.json, dnd5e.mjs, lang/en.json, less/v2/apps.less, module/applications/actor/base-sheet.mjs, module/applications/actor/character-sheet-2.mjs, module/applications/actor/group-sheet.mjs, module/applications/actor/sheet-mixin.mjs, module/applications/item/container-sheet.mjs, module/applications/item/item-compendium.mjs, module/applications/item/item-directory.mjs, module/applications/mixins/drag-drop-mixin.mjs, module/applications/mixins/sheet-v2-mixin.mjs, module/drag-drop.mjs, module/settings.mjs, module/utils.mjs, templates/shared/inventory2.hbs
Adds the ability to use the OS-defined modifier key (usually Alt on Windows and Option on Mac) to toggle between the default drop behavior and the opposite behavior. So if dragging within the same actor this changes from the default move behaior to copy behavior and the opposite when dragging between different actors or to the sidebar.
Enabling this required access to the current drag payload during the `ondragover` event, so this extends the `DragDrop` class provided by core to store that information during the `ondragstart` event and adds a new handler for the `ondragend` event to clear the stored payload.
Currently this only covers dragging items, with some minor improvements to dragging favorites on the character sheet. This framework could be expanded in the future to support …
=> [#4876] Add support for modifier keys during drag operations

module/applications/activity/activity-sheet.mjs, module/data/active-effect/enchantment.mjs, module/data/activity/base-activity.mjs, templates/activity/parts/damage-part.hbs
Adds the ability for enchantments to replace or add to the damage types for all parts on an activity. This is done using an active effect targeting `system.damage.types`. Using the `OVERRIDE` mode will replace all existing damage types with the specified type, while `ADD` will introduce a new damage type to the existing types.
Closes #3617
=> [#3617] Add enchantment effect for modifying damage types

module/data/activity/base-activity.mjs, module/documents/activity/summon.mjs
Adds `system.damage.bonus` as an enchanntment target that adds to the first damage part for an item, allowing for the damage bonus on summons to be properlty typed.
Closes #3754
=> [#3754] Add `system.damage.bonus` AE target & adjust summoning

dnd5e.mjs, module/applications/actor/character-sheet-2.mjs, module/applications/actor/npc-sheet-2.mjs, module/applications/actor/sheet-v2-mixin.mjs, module/documents/macro.mjs
Adds the ability to drag specific activities into the macro bar and create a macro for them using the `activityName` functionality already supported in `rollItem`. This required some changes to drag & drop on NPC sheets so that activities can be dragged on their own like on the PC sheets.
Also passes the event in to item macros so that keyboard modifiers can be used when activating them.
Closes #4819
Closes #4993
=> [#4819, #4993] Add activity macros, pass event to item macros

lang/en.json, module/applications/dice/skill-tool-configuration-dialog.mjs, module/documents/activity/attack.mjs, module/documents/activity/heal.mjs, module/documents/activity/mixin.mjs, module/documents/actor/actor.mjs, module/documents/chat-message.mjs
Closes #4787 
Also added a check when putting the subtitle for an activity use in a chat card whether the activity was a heal-type, if so display "Healing Roll" instead of "Damage Roll."
Attack Roll:
Damage Roll:
Skill Check:
Ability Check: 
Saving Throw:
Tool Check:
Fixed subtitle for a heal activity:
Haven't tested much with super long item/actor names. Might make sense to put them as subtitles instead of titles.
=> [#4787] More informative roll dialog titles

module/applications/actor/rest/long-rest-dialog.mjs, module/data/actor/group.mjs, module/documents/actor/actor.mjs
Adds the "Advance Bastion Turn" button to the long rest dialog so long as it is a group rest and bastions are enabled.
Right now this advances bastion turns for all actors, not just those in the group, but perhaps that should change.
The normal actor rest also supports the `advanceBastionTurn` config option which advances turn for a specific actor, but it isn't exposed in the UI yet.
Closes #4744
=> [#4744] Add "Advance Bastion Turn" option to group long rest dialog

lang/en.json, module/applications/activity/activity-sheet.mjs, module/applications/activity/heal-sheet.mjs, module/config.mjs
Closes #5093 
Adds `HalfCantrip` and `WholeCantrip` localizations, `labelCantrip` properties to `CONFIG.DND5E.damageScalingModes`'s fields, and uses the them instead of `label` when the item in question is a "spell" type item with `level` of 0.
On a cantrip:
On a non-cantrip:
=> [#5093] Adjust scaling label for cantrips

lang/en.json, less/v2/journal.less, module/data/actor/npc.mjs, module/enrichers.mjs, templates/actors/embeds/npc-embed.hbs
Adds the legendary action description to embedded NPC stat blocks. This will automatically use the description of an item with the `legendary-actions` identifier if present, otherwise it use an auto-generated description based on the rules version.
The auto-generated description is also available from the roll data in `resources.legact.label`. A modification has been made to the lookup enricher so that if it finds a function at its target location, it will call that function with the enricher config as its paremter. This allows for substituting the actor's name: `[[lookup @resources.legact.label name=dragon]]`.
=> [#3798, #4842] Add legendary action description to stat blocks

dnd5e.mjs, module/applications/journal/spells-page-sheet.mjs, module/documents/actor/actor.mjs, module/parse-uuid.mjs
Moves the `parseUuid` changes from `JournalSpellListPageSheet` into a shared implementation and applied it to `SourcedItemsMap` during get and set operations so it always handles remapped UUIDs. Because the initial setup of sourced items occurs before the UUID redirects are loaded, the system will re-adjust the map during the `ready` hook.
=> Adjust sourced items on actors to use remapped UUIDs

module/dice/basic-roll.mjs
Closes #4992 
Allows the type of roll to be ascertained solely from the roll object.
Originally put it under `options.type` but, while that would work fine, that's also where damage rolls store the damage type, so while `??=` wouldn't clobber that (and whether it's a "Damage" roll could be checked by looking at whether it's a `DamageRoll`) it felt cleaner to give it a new property.
=> [#4992] Store roll type (attack, skill, ability, save, damage) in roll options

module/documents/activity/attack.mjs
Partially addresses #4968 
When rolling damage from an attack activity's chat card, check `lastAttack` for whether it was a crit. If so, pass `isCritical` in the `config` argument and `options: { defaultButton: "critical" }` in the `dialog` argument. This way, shift-clicking damage after a crit will roll critical damage, and going through the dialog will show the crit dice & highlight the crit button (similar to the default behavior of advantage/disadvantage for the rolls that currently have that functionality).
=> Recognize when last attack is critical and set damage & default button accordingly

module/data/activity/attack-data.mjs
Would close #4830 
When the activity's `attack.ability` was left to default, it would pull from its item's `availableActivities`, meaning that a spell attack on a weapon would use str or dex, and a weapon attack on a spell would use whatever was set on the spell as the spellcasting ability. By only using the parent item's `availableActivities` if the attack type matches (i.e. weapon attack on a weapon, spell attack on a spell), this problem is avoided without any side effects (to my knowledge).
=> [#4830] Only defer to item abilities if attack activity matches attack type

dnd5e.mjs, module/applications/advancement/advancement-manager.mjs, module/migration.mjs, module/module-registration.mjs, module/utils.mjs, system.json
Adds a new compendium flag `dnd5e.sorting` that sets the default sorting for a compendium if the user hasn't already adjusted the sorting. This allows for setting a compendium to be manually sorted.
To implement this a new `setupModulePacks` method has been added to the module registration system that is called during setup and sets compendium applications and the sorting mode.
Also adds a new `log` utility method that adds the "D&D 5e | " prefix automatically with a nice red color to make system-specific logs distinct from Foundry core logs.
Closes #3751
=> [#3751] Add ability to automatically manually sort compendiums

module/data/activity/save-data.mjs, module/documents/active-effect.mjs
Currently, if wanting to increase the DC of a save activity via enchantments, the activity cannot derive its DC from `save.dc.calculation`, only custom formulas work.
This adds a `save.dc.bonus` property during data prep that can be targeted by enchantments and accepts roll data. It works with both custom formula and ability-derived DCs.
=> Allow for arbitrary bonus to save DC on activities.

lang/en.json, module/applications/settings/combat-settings.mjs, module/settings.mjs, templates/settings/base-config.hbs
Adds a new "Configure Combat" application that contains combat related settings including dexterity tiebreaker, initiative score, critical multiply modifiers, and critical maximize dice.
=> [#5102] Add combat settings application with initiative & criticals

lang/en.json, module/applications/components/inventory.mjs, module/documents/chat-message.mjs
Closes #4802 
Adds an option to the context menu for inventory items to display in chat. In order not to show the effect application tray for a display-only use of `displayCard`, used a new `dnd5e.displayOnly` flag on the message which, if `true`, blocks the enriching of usage effects.
Not sure whether any conditions (like owning the item, for instance) should be necessary, or whether it's in the appropriate section of the context menu.
=> [#4802] Add "display chat card" button to inventory item context menu

module/applications/compendium-browser.mjs
Changing the compendium browser to inherit from the system's application class allows it to use the part container code for the sidebar rather than handling that itself.
=> [#5074] Adjust `CompendiumBrowser` to inherit from `Application5e`

module/applications/api/application-v2-mixin.mjs, module/applications/property-attribution.mjs
No change in design due to property attribution being styled like core's tooltips, but now uses `ApplicationV2` rather than the old API.
=> [#5074] Convert `PropertyAttribution` to `ApplicationV2`

lang/en.json, module/applications/settings/variant-rules-settings.mjs, module/settings.mjs
Adds a settings application for variant rules that contains the rest variant, proficiency variant, leveling mode, encumbrance settings, and additional ability scores.
Also includes the "Allow Feats" setting, but this only appears when the legacy rules version is selected.
Also removes the unused diagonal movement setting and some unused setting localization strings.
Closes #5102
=> [#5102] Add variant rules settings application

dnd5e.mjs, lang/en.json, module/documents/active-effect.mjs
When an effect granted to a target by some monster feature means that you also suffer from a given condition (eg "while slimed, you are also considered Poisoned"), that effect should simply have the given status. This use case is covered well enough and improved slightly by #4881.
The other case is being affected by a generic condition *in addition* - eg "you are slimed, and also knocked prone," where the two effects/conditions are independent; they are applied at the same time but can be removed at different times. This PR helps with that specific use case.
=> Extend rider conditions to generic effects

dnd5e.mjs, module/applications/actor/base-sheet.mjs, module/applications/actor/character-sheet-2.mjs, module/applications/components/effects.mjs, module/applications/components/inventory.mjs, module/applications/dice/roll-configuration-dialog.mjs, module/applications/item/item-sheet-2.mjs, module/applications/mixins/sheet-v2-mixin.mjs, module/documents/activity/mixin.mjs, module/documents/advancement/advancement.mjs
- Suppress namespace warnings
- Suppress ApplicationV1 warnings
- Suppress `Set#isSubset` warning
- Suppress `ChatMessage#getHTML` warning
- Suppress `renderchatMessage` warning
- Adjust creation of `ContextMenu` objects to pass in `HTMLElement` in V13 and pass the `jQuery` option
- Modified access to `Document#compendium` when running in V13 to use either `Document#collection` or `Document#inCompendium`
=> Suppress some V13 warnings and add alternate paths to others

module/data/item/templates/activities.mjs, package-lock.json
This fix a possible lot warnings in old campaigns.  The warning is:
`TypeError: Failed data migration for FeatData: source.uses?.max?.includes is not a function at #migrateUses (activities.mjs:170:28) at ActivitiesTemplate.migrateActivities (activities.mjs:159:36) at FeatData._migrateData (feat.mjs:174:24) at FeatData.migrateData (abstract.mjs:240:10) at FeatData.migrateDataSafe (foundry-esm.js:10695:14) at TypeDataField.migrateSource (foundry-esm.js:9837:22) at  (...)`
This warning is caused because a possible null pointer in some objects. What I did is check if the object is null before use.
=> Fix warnings migrations

module/dice/basic-roll.mjs, module/documents/activity/attack.mjs, module/documents/actor/actor.mjs
- Closes #4628 
Just a draft to run this potential solution by you. I think the root issue was we were running this line too early in `#rollSkillTool`.
```js
rollConfig.rolls.forEach((r, index) => buildConfig(rollConfig, r, null, index));
```
This is mutating our initial roll configs before they are stored by the roll dialog. That means that when we try to rebuild the rolls, we have to ignore the roll configs entirely, because they are contaminated with 'derived' data from the pre-dialog call to `buildConfig`.
It seems we are only performing this early `buildConfig` call in case the roll dialog is not instantiated at all, and never gets a chance to call `buildConfig` itself. So I think that by moving this logic into `BasicRoll.buildConfigure` and calling it only when `dialog.configure === …
=> [#4628] Preserve initial roll configuration for rebuilding.

dnd5e.mjs, module/applications/actor/base-sheet.mjs, module/applications/actor/npc-sheet-2.mjs, module/config.mjs, module/data/actor/npc.mjs, module/data/actor/templates/attributes.mjs, module/data/actor/templates/common.mjs, module/documents/activity/summon.mjs, module/documents/actor/actor.mjs, module/documents/item.mjs, module/utils.mjs, templates/actors/character-sheet.hbs, templates/actors/parts/actor-spellbook.hbs, templates/actors/tabs/creature-spells.hbs
Adds `attack` to each ability which is the default attack to hit using that ability (e.g. prof + mod).
Also adds the spell attack and ability label to actor attributes inside a new `attributes.spells` object. This moves the old `spelldc` and `spellmod` into that object with deprecation warnings.
Closes #5003
=> [#5003] Add ability attack, spell attack, & spell ability labels

lang/en.json, module/applications/components/inventory.mjs, module/applications/settings/combat-settings.mjs, module/data/chat-message/fields/deltas-field.mjs, module/data/chat-message/rest-message-data.mjs, module/data/chat-message/turn-message-data.mjs, module/data/item/templates/activities.mjs, module/data/shared/uses-field.mjs, module/documents/combatant.mjs, module/settings.mjs
Adds a setting that allows for automatically recharging NPC abilities at the start of their turn, either displaying the roll chat message or hiding it.
This includes some changes to the `rollRecharge` method so that it can return the updates to perform rather than performing them itself to allow the system to perform all combatant updates at the same time.
Also adds some data to the recharge roll options to allow the roll to be associated back with the delta data. This should support displaying a roll tooltip on the turn chat message next to the delta entry. This data will also need to be added to rolls performed during the normal recovery process.
Closes #4799
=> [#4799] Add setting for automatically recharging NPC abilities

less/v2/chat.less, module/data/activity/fields/consumption-targets-field.mjs, module/data/chat-message/fields/deltas-field.mjs, module/data/shared/uses-field.mjs, templates/chat/parts/card-deltas.hbs
Displays the rolls associated with recovery during rest or combat turn with the deltas in their chat cards. Uses core's inline roll display so that mousing over the roll icon displays the formula and clicking it will display the roll breakdown.
Also adds the necessary data to the rolls performed during consumption to display them correctly, but changes will need to be made to the usage chat message to fully display those.
=> [#5117] Display rest/turn rolls inline on chat cards with deltas

module/data/actor/npc.mjs, module/filter.mjs
Adds the ability to filter NPCs based on their habitat. Because of how habitat data is stored, this required adding support in the filtering system for applying sub-filters when searching a collection using the `has` comparison function.
Closes #5125
=> [#5125] Add habitat filter for Compendium Browser

lang/en.json, less/v1/advancement.less, less/v2/advancement.less, module/applications/advancement/ability-score-improvement-flow.mjs, module/applications/advancement/subclass-flow.mjs, templates/advancement/ability-score-improvement-flow.hbs, templates/advancement/subclass-flow.hbs
Adds a button to open the compendium browser to select a feat within the ASI advancement flow. This button takes the design of the species/background/class pills on the character sheet.
Also modifies the button on the subclass flow to match this new style.
Closes #4665
=> [#4665] Add compendium browser to select feat in ASI advancement

module/applications/actor/sheet-v2-mixin.mjs
Been using nested keys such as `dnd5e.crafting.rune` and `dnd5e.crafting.alchemy`. Current special traits tab never retrieved values properly.
=> Fix nested keys values retrieving

module/data/item/facility.mjs
This change removes a junk error from the log when attempting to drag-drop a facility to a low-level actor. Note that this makes no functional difference, as a level <5 actor will not trigger the "set built" conditional.
=> Avoid crash when drag-dropping facility to low-level actor

module/applications/actor/sheet-v2-mixin.mjs
`flag.field` is the expected value, leaving it unset (by accidentally setting `flag.fields`) and adding a `StringField` type character flag would prevent the sheet from opening in v12 and throw errors in v13.
=> Fix incorrect key use for StringField character flags

module/documents/active-effect.mjs
Using `:last-of-type` instead of `:last-child` means that if the details tab changes at some point (or a module extends/changes it) such that the final child on the tab no longer has the `form-group` class, the `querySelector` won't fail, but will simply append after what actually _is_ the final `form-group`-class-having element. 
Once in V13 only (if the system hasn't made a custom AE config application yet), could potentially be changed to
```js
html.querySelector("[data-tab=details] > .form-group.statuses").insertAdjacentHTML("afterend", element);
```
=> Make new rider status dropdown's insertion more resilient to potential AE Config modifications

less/v2/journal.less, module/data/actor/npc.mjs, templates/actors/embeds/npc-embed.hbs
- Links the actor name on embedded NPC stat blocks if the embed has `cite` set to `true`
- If a label is provided for the embed, the label will be displayed as the name instead of the document name
=> Add link to embedded actor if `cite` is set, use label as name

lang/en.json, module/dice/damage-roll.mjs
In #5015 I set `config.isCritical` to `false` or `true`, will only ever be `undefined` if there was no "last attack." Since `applyKeybindings` relied on `config.isCritical` being `undefined` in order to care about holding the critical key down, that functionality broke.
New functionality while clicking damage:
- Holding shift (by default) skips the dialog, doing whatever the default would be
- Holding ctrl (by default) skips the dialog, rolling _normal_ damage regardless of last attack
- Holding alt (by default) skips the dialog, rolling _critical_ damage regardless of last attack
=> Fix damage shortcut key bug introduced by #5015

module/documents/activity/mixin.mjs
Fixes all the activity consumption hooks not stopping the activity being activated.
=> Ensure explicit false return for activity consumption hooks

module/data/actor/templates/common.mjs, module/dice/basic-roll.mjs
To get around core limitation that prevents a `toString` shim on plain objects when used in roll formulas, this allows `toJSON` to be used as the shim. Since that results in the final value being surrounded by `$`, this looks for the pattern `$!!$` and replaces it with just the value between the marks (the bang has been added to ensure this is a deliberate shim from the system, not a unintentional usage that should show an error).
Closes #5196
=> [#5196] Adds handling to `replaceFormulaData` to parse shims

module/data/activity/cast-data.mjs, module/data/item/spell.mjs
Manually implement relative fetching of the activity using a relative UUID. Should be reverted once foundryvtt/foundryvtt#11214 is fixed.
Closes #5220
=> [#5220] Fix displaying cached spells on actors in compendiums

less/v2/dark/journal.less, less/v2/journal.less
Adjusts the colors the embedded stat blocks for dark mode.
Closes #5033
=> [#5033] Add dark mode styling for embedded stat blocks

module/applications/journal/table-of-contents.mjs, templates/journal/table-of-contents.hbs
Currently "special" table of contents that append to an existing chapter won't appear if `showPages` is `false` for that chapter. This change moves some of the page display logic into the app and allows for displaying those special pages while hiding all other pages in the chapter.
=> Allow special ToC sections to be seen in chapters that hide pages

module/data/activity/attack-data.mjs, module/data/activity/base-activity.mjs, module/data/activity/damage-data.mjs, module/data/activity/heal-data.mjs, module/data/activity/save-data.mjs
Switches to using `getDamageConfig` rather than using the raw damage parts when generating the damage labels. This allows the de-duplication in handling for `@mod` and other bonuses.
This also means the scaled cantrip damage is displayed, rather than just showing the base damage.
Closes #5275
Closes #5319
=> [#5275, #5319] Fix flat damage label, display scaled cantrips

lang/en.json, less/v1/advancement.less, less/v2/advancement.less, module/applications/advancement/advancement-migration-dialog.mjs, module/applications/api/dialog.mjs, module/applications/item/item-sheet.mjs, templates/advancement/advancement-migration-dialog.hbs, templates/shared/dialog-content.hbs
Convert `AdvancementMigrationDialog` to use `Dialog5e` and the V2 styles.
=> [#4708] Redesign `AdvancementMigrationDialog` for V2 app & styles

dnd5e.mjs, module/documents/actor/actor.mjs, module/migration.mjs, module/module-art.mjs, system.json
Adjusts the system's art mapping to use core's system rather than the system's. Add handling to the system to ensure credit is added to actor descriptions when using the core's system.
Deprecates the `ModuleArt` system while ensure it continues to work in tandem with core's system until the deprecation period ends. The removal version is set to `6.0` to give premium modules plenty of time to move over.
Closes #5332
=> [#5332] Migrate to core's `CompendiumArt` system

module/applications/actor/base-sheet.mjs, module/config.mjs, module/data/settings/transformation-setting.mjs, module/documents/actor/actor.mjs
Adjust the implementation of `transformInto` to accept the new `TransformationSetting` object rather than the old destructured options object. This adds a new `dnd5e.transformActorV2` hook and deprecateds the old hook.
Also stores the full transformation settings data in flags on the transformed actor to aid with the reversion process.
Closes #5261
=> [#3877, #5261] Rework `transformInto` using new settings object

dnd5e.mjs, lang/en.json, module/applications/actor/transform-dialog.mjs, module/config.mjs, module/data/actor/templates/creature.mjs, module/data/settings/transformation-setting.mjs, module/documents/actor/actor.mjs, templates/apps/transform-details.hbs
Adds a new formula field to define how much temp HP the transformed actor gets. The roll data in this field provides both the target actor's roll data as well as the source actor. This allows the polymorph preset formula to be `@source.attributes.hp.max`.
This PR also adds information on subclasses to the roll data, using a `Proxy` setup that allows for determining whether a specific subclass exists in roll data (so `@subclasses.moon` will resolve to `1` if the player has the Moon Druid subclass, or `0` if they do not). This allows setting the 2024 wild shape temp HP formula to be `max(@classes.druid.levels, @subclasses.moon.levels * 3)`.
Closes #5259
=> [#5259] Add temp HP formula to transformation, replacing `addTemp`

module/applications/activity/activity-sheet.mjs, module/applications/actor/base-sheet.mjs, module/applications/api/_module.mjs, module/applications/api/application-v2-mixin.mjs, module/applications/api/primary-sheet-mixin.mjs, module/applications/components/effects.mjs, module/applications/components/inventory.mjs, module/applications/components/item-list-controls.mjs, module/applications/context-menu.mjs, module/applications/item/item-sheet-2.mjs, module/applications/mixins/sheet-v2-mixin.mjs, module/documents/item.mjs
Introduces `PrimarySheetMixin` which is a V2-compatible version of `DocumentSheetV2Mixin` that handles tabs, edit/play toggle, and some other behavior that will be shared between the `ApplicationV2` versions of the actor and item sheets.
Also moves the section expansion code from `ActivitySheet` into `ApplicationV2Mixin` so it can be used to handle the description sections on the item sheets.
Adds the `triggerEvent` static method to `ContextMenu5e` to consolidate some duplicate code for the "Additional Options" dots buttons.
=> [#5340] Add `PrimarySheetMixin`, move section expansion

module/documents/activity/summon.mjs
`system.attack.bonus`, `system.attack.flat`, `system.save.dc`, and `system.save.scaling` all have equivalents in the `activities[type]` format (and indeed are shimmed via `_applyLegacy`), figured they should be updated to not require said shimming.
=> Swap from legacy to proper enchant keys for summon item changes

module/applications/actor/sheet-v2-mixin.mjs
Closes #5037 
Changes pill under Languages to display units alongside any ranged communication (currently only telepathy):
Senses also accept multiple units, but as they're more likely to almost always be whatever the "default" unit of measure is (feet, typically) it doesn't make much sense to give them this same functionality. Maybe specifically for non-feet, non-meter units. But that'd be a different PR.
=> [#5037] Add units display to ranged communication pill

module/data/item/weapon.mjs
Closes #5450 
Add `rule: true` to the existing first mastery, rather than creating it as a standalone object in the list.
=> [#5450] Fix for defaulting to no mastery under some circumstances

packs/_source/items/trinket/talisman-of-the-sphere.yml, packs/_source/monsterfeatures/legendary-resistance.yml, packs/_source/monsters/celestial/couatl.yml, packs/_source/monsters/fiend/succubus-incubus.yml, packs/_source/monsters/humanoid/assassin.yml, packs/_source/monsters/humanoid/berserker.yml, packs/_source/monsters/humanoid/druid.yml, packs/_source/monsters/humanoid/gladiator.yml, packs/_source/monsters/humanoid/mage.yml, packs/_source/monsters/humanoid/noble.yml, packs/_source/monsters/humanoid/priest.yml, packs/_source/monsters/humanoid/scout.yml, packs/_source/monsters/humanoid/weretiger.yml
Actors:
- Couatl, Succubus/Incubus, Assassin, Berserker, Gladiator, Weretiger  - attack/damage/save enrichers and additional activities
- Druid - enrichers and shillelagh improvements
- Mage, Priest, Scout - enrichers and replaced natural weapons with equipment equivalents
- Noble - enrichers
Items:
- Talisman of the Sphere - changed item type to equipment (wondrous item) and added control check activity
- Legendary Resistance - adds resource consumption, clarifies activity (expend use)
=> Miscellaneous SRD upgrades

less/elements.less, less/v1/actors.less, less/v1/advancement.less, less/v1/apps.less, less/v1/group.less, less/v1/inventory.less, less/v1/items.less, less/v2/activities.less, less/v2/actors.less, less/v2/advancement.less, less/v2/apps.less, less/v2/character.less, less/v2/chat.less, less/v2/compendium-browser.less, less/v2/forms.less, less/v2/inventory.less, less/v2/items.less, less/v2/npc.less, module/applications/components/checkbox.mjs, module/applications/components/proficiency-cycle.mjs
Swaps out everything except for uses of `cursor: help` and `cursor: not-allowed` which aren't supported as custom types.
=> Swap to using cursor variables

module/data/actor/_module.mjs
With makeSimpleTrait and makeDamageTrait being deprecated I couldn't find the SimpleTraitField and DamageTraitField classes available anywhere so I added them to the export for actor data.
=> Add DamageTraitField and SimpleTraitField exports to module

lang/en.json, module/data/shared/source-field.mjs, system.json
Adds the SRD 5.2 to the book provided by the module. Because the old SRD content didn't have a book listed, this also adjust the default book selection behavior to select the first book regardless of how many are present in the manifest so that existing SRD content will have the correct source listed.
=> [#5510] Add SRD 5.2 to source books, adjust book selection behavior

dnd5e.mjs, module/applications/actor/api/base-actor-sheet.mjs, module/applications/actor/deprecated/sheet-v2-mixin.mjs, module/config.mjs, module/documents/active-effect.mjs, templates/shared/active-effects2.hbs
- Migrate `icon` to `img`
- Migrate `label` to `name`
- Move `_configureStatusEffects` to just before prelocalization
Closes #5297.
=> [#5297] Adjust order of operations on status effect config, and migrate properties to use `name` and `img` everywhere

packs/_source/items/ring/ring-of-acid-resistance.yml, packs/_source/items/ring/ring-of-cold-resistance.yml, packs/_source/items/ring/ring-of-fire-resistance.yml, packs/_source/items/ring/ring-of-force-resistance.yml, packs/_source/items/ring/ring-of-lightning-resistance.yml, packs/_source/items/ring/ring-of-necrotic-resistance.yml, packs/_source/items/ring/ring-of-poison-resistance.yml, packs/_source/items/ring/ring-of-psychic-resistance.yml, packs/_source/items/ring/ring-of-radiant-resistance.yml, packs/_source/items/ring/ring-of-thunder-resistance.yml
Updated rings of resistance:
- Added missing dot.
- Fixed syntax (redundant `<em>` elements).
- Changed some images to fit the gem color described in the text.
- Removed redundant activities.
=> Update Rings of Resistance

packs/_source/items/equipment/amulet-of-health.yml, packs/_source/items/equipment/belt-of-cloud-giant-strength.yml, packs/_source/items/equipment/belt-of-dwarvenkind.yml, packs/_source/items/equipment/belt-of-fire-giant-strength.yml, packs/_source/items/equipment/belt-of-frost-giant-strength.yml, packs/_source/items/equipment/belt-of-hill-giant-strength.yml, packs/_source/items/equipment/belt-of-stone-giant-strength.yml, packs/_source/items/equipment/belt-of-storm-giant-strength.yml
- Added missing effect to Amulet of Health.
- Changes instances of `Wondrous item, (...)` to `Wondrous item (...)` (with no comma).
- Changed subtype of Belt of X Giant Strength to "Wondrous".
- Added missing effect to Belt of Dwarvenkind.
- Added missing effect to Belt of Stone Giant Strength.
=> More legacy SRD updates: Belts (and an amulet)

module/applications/actor/api/base-actor-sheet.mjs, module/applications/actor/character-sheet.mjs, module/applications/item/container-sheet.mjs
Small & simple hook; I double checked `Hooks.call` and it will default to returning `true`, so there's no good way to have a "return true if this filter is an always show" kind of deal. But this at least generalizes the implementation for stuff like Power Specializations or any other novel additions.
Closes #5522
=> [#5522] Added a hook to BaseActorSheet#_filterItem and ContainerSheet#_filterItem

packs/_source/items/wand/wand-of-the-war-mage-1.yml, packs/_source/items/wand/wand-of-the-war-mage-2.yml, packs/_source/items/wand/wand-of-the-war-mage-3.yml
- Add missing effects.
- Swap "trinket" subtype for "wand".
- Add missing word in description.
=> SRD 5.1: Wands of the War Mage +1, +2, +3

module/documents/actor/actor.mjs
Applies the unlinked actor changes as an updated directly to the synthetic actor rather than to the `ActorDelta` to avoid an issue with unlinked actors not immediately showing delta changes in V13.
See https://github.com/foundryvtt/foundryvtt/issues/12611
Closes #5508
=> [#5508] Fix transforming unlinked actors in V13

module/applications/settings/base-settings.mjs
---
The `requiresReload` option in the `game.settings.register` method was not being honored when modifying certain settings via the settings menu. Specifically:
1. When toggling a setting that has `requiresReload: true` (e.g., the "Sanity Ability Score" setting), no reload prompt was displayed after saving changes.
2. This issue was reported in [#5392](https://github.com/foundryvtt/dnd5e/issues/5392) of the Foundry VTT D&D 5e open-source project.
1. Open **Configure Settings** -> **Dungeons & Dragons Fifth Edition** -> **Configure Variant Rules**.
2. Toggle the "Sanity Ability Score" setting (or any other setting with `requiresReload: true`).
3. Save changes.
4. Observe that no reload prompt is displayed, even though the setting requires a reload.
The issue was caused by the …
=> [#5392] Fix `requiresReload` Option for Settings in D&D 5e System

.github/workflows/release.yml, package-lock.json, utils/integrate/action.yml
Modifies the release build script to integrate content into the final build artifact from a private repo. The build script now calls the `integrate` action, a composite action that does three things:
1) Generate private access token to the private repo
2) Checks out the private repo into the `_free` folder
3) Runs the repo's `integrate` action that copies compendium content and images into the system and modifies the system manifest slightly
Because the integration script modifies the manifest, the ordering in the build script has been adjusted so the full manifest isn't loaded until after this is completed. Instead only the module `id` is loaded earlier.
The free rules integration will fail if the build script is run on a fork outside the `foundryvtt` organization, so it is marked as …
=> Add Free Rules integration to build script

lang/en.json, less/v2/journal.less, module/applications/journal/journal-sheet.mjs
Adds support for a series of flags on journal sheets that allow displaying next, previous, and up links at the top of an entry for navigating through a book.
```json
"flags": {
"dnd5e": {
"navigation": {
"previous": "journalLinkPrevi",
"next": "journalLinkNext0",
"up": "journalLinkUp000"
}
}
}
```
=> Add journal navigation system from premium content to system sheets

module/applications/actor/api/base-actor-sheet.mjs
Uses the preparation mode to select where the pips should be added, not just the spell level.
Closes #5555
=> [#5555] Fix spell slots appearing in incorrect spellbook section

module/applications/dice/roll-configuration-dialog.mjs, module/dice/basic-roll.mjs
Makes three changes to the `dnd5e.buildRollConfig` hook to make it more useful:
- Moves it after `options.buildConfig` is called so it has the fully-built data to work on
- Calls multiple hooks using `hookNames` to dial down on specific roll types
- Calls it in `buildConfigure` if the dialog is skipped to give a chance to modify the config
This can be potentially a breaking change in two ways:
- Any callers relying on the hook being called before `buildConfig` is called
- Any callers expecting the full application to be passed to the hook might get issues with fast-forwarded rolls. A stub version of the application is passed that has all of the key public properties available, but if the caller is using the hook to modify the rendered application itself this may cause an issue.
Closes …
=> [#5503] Add `dnd5e.postBuildRollConfig` hook for skipped rolls

module/enrichers.mjs
Fixes #5562.
This is a simple repeat of the existing solution present in `enrichLookup` to every other mention of `options.rollData`.
A more top-down solution would probably be better, but currently this is a blocker for Loot Tavern, or we are back to shimming the system enrichers, which we were hoping not to do after #4476 was merged.
=> Add `getRollData()` fallbacks to every enricher

module/applications/journal/class-page-sheet.mjs, module/documents/actor/actor.mjs
Subclass progression tables now properly 'ignore' pre-subclass levels when the subclass grants a casting progression.
Subclass pact-style casters now render (previously errored out due to a pact slot computation checking for being an NPC when no actor is supplied).
I want to specifically call out the change to the `spellCell` retrieval change [here]( https://github.com/trioderegion/dnd5e/blob/1f757e3ca2108bc211ec0d35ce0e74325a54465b/module/applications/journal/class-page-sheet.mjs#L238) for review. Previously, when a subclass "skipped" this row (line 248), the next iteration would retrieve the same set of spellCells (now for the *previous* level) since the length was not modified.
Leveled subclass caster BEFORE
Leveled subclass caster AFTER
Pact subclass caster BEFORE (error at …
=> [#5072] Improvements to subclass summary table generation.

dnd5e.mjs, module/documents/chat-message.mjs
When right clicking a damage type dice roll message it now shows the proper context menu.
Fixes issue #5589
=> [#5589] Changed to getChatMessageContextOptions hook and changed addChatMessageContextOptions function accordingly

module/documents/actor/actor.mjs
Related foundryvtt/foundryvtt#12768
Related foundryvtt/foundryvtt#12769
Seems this initial solution was never working and I did something wrong when I was testing it. I don't see any way to avoid the extra server round-trips here given the above issues. This solution does work in v12 as well though, which is something.
Given I'm not sure what happened with the testing of the original solution, I'd appreciate an extra party to verify that the `==` solution does indeed not work currently in v13, and that this new proposal does work.
=> [#5530] Fix embedded Document marshalling in synthetic Actor transformations.

module/data/shared/duration-field.mjs, module/data/shared/range-field.mjs
These fields weren't allowing blank values in V12, but a change in how V13 generates fields was adding a blank option. This change to the data models will prevent blank values from being entered and fix the generated inputs.
Closes #5605
=> [#5605] Prevent blank values in duration & range units

less/v2/journal.less
* Renames 'dmg-tracker' class to 'srd-tracker' to avoid collisions with enabled DMG module.
* Simplifies tracker sheet styling to match with the SRD.
Below is an example of resulting styles in combination with free rules content updates.
Closes #5569
=> [#5569] Simplifies tracker sheet styling to match SRD.

module/data/shared/source-field.mjs, system.json
Adds support for the `dnd5e.sourceBook` flag in compendium packs in the manifest. If specified, this value will be used by default when inferring the source book before falling back to a single source book defined in the `dnd5e.sourceBooks` flag on the package manifest.
This reverts the change made earlier that changed the process to infer even if more than one source book is defined by the package at the root level.
Closes #5612
=> [#5612] Add ability to specify source books on a per-pack basis

module/applications/api/application-v2-mixin.mjs
Automatically configures the highlihgt matches plugin for all `ApplicationV2` applications. Anything that inherits from our V2 mixin can disable this by overwriting `_onConfigurePlugins`.
Closes #5649
=> [#5649] Enable highlight matches plugin for ProseMirror editors

module/canvas/detection-modes/blindsight.mjs
Error: You are accessing the global "Token" which is now namespaced under foundry.canvas.placeables.Token Deprecated since Version 13
Closes #5683
=> Deprecation Warning for `instanceof Token` in `blindsight.testVisibility()`

lang/en.json, module/applications/actor/rest/base-rest-dialog.mjs, module/config.mjs, module/documents/actor/actor.mjs, templates/actors/rest/long-rest.hbs, templates/actors/rest/short-rest.hbs
- Closes #3386
- Closes #5707 
The user sees a checkbox whether to reset the actor's temp max hp if the actor has any temp max hp, negative or positive. Group sheet long rest sees this checkbox if at least 1 actor has any temp max hp.
Also added that temp hp always resets on long rest. Not sure if this was a bug or intentional but as per the rules temp hp should reset on every long rest.
=> Added option to not reset temp max hp during long rest

module/documents/active-effect.mjs, module/documents/actor/actor.mjs
`ActiveEffect#isSuppressed` has existed in core as a getter for a little while now. With V13, systems which extend `ActiveEffect` should reference its `isSuppressed`, as now `ActiveEffect#isSuppressed` checks any effect subtypes' `system.isSuppressed` implementation. This PR gets rid of the now-unnecessary `ActiveEffect5e#determineSuppression` in favor of making `ActiveEffect5e#isSuppressed` a getter, and ensures the getter respects the super implementation.
=> Bring ActiveEffect5e#isSuppressed in line with core expectations

module/applications/components/damage-application.mjs, module/documents/actor/actor.mjs, module/documents/chat-message.mjs
Closes #5507 
For damage tray or chat card context menu applications, `isDelta` is always `true`. Otherwise, pass along the existing value.
=> [#5507] Include `isDelta` in passed `options `for `dnd5e.preApplyDamage` and `dnd5e.applyDamage` hooks

module/documents/item.mjs, templates/apps/document-create.hbs
Closes #5744 
Added a check in the hbs to appropriately check the radio input. Also remove a line which set a type by default, as that doesn't seem to be necessary/useful now. Otherwise would always default to having some radio checked, if that's desired.
=> [#5744] If `type` is provided to `Item5e.createDialog`, pre-select that type in the creation dialog

lang/en.json, less/v2/npc.less, module/applications/actor/character-sheet.mjs, module/applications/actor/npc-sheet.mjs, module/documents/actor/actor.mjs, module/settings.mjs, templates/actors/character-header.hbs, templates/actors/npc-header.hbs
Adds a new setting that controls whether the rest buttons appear on character sheets for players. When unchecked, players will only be able to rest their characters at the request of the GM. The setting is on by default so there is no behavior change.
=> [#5129] Add setting to disallow resting from individual sheets

module/applications/dice/damage-configuration-dialog.mjs, module/dice/damage-roll.mjs
Closes #5680 
Modify `config.isCritical` in two places:
1. `DamageRoll.applyKeybindings`: If advantage key held, `config.isCritical` is `true`, but if disadvantage key held, it's `false`
2. `DamageRollConfigurationDialog#_finalizeRolls`: If critical is clicked, `config.isCritical` is `true`, otherwise it's `false`
This ensures regardless of fast-forwarding, `config.isCritical` will always be accurate by the time it's passed in the `dnd5e.postRollConfiguration` hook
=> [#5680] Ensure `config.isCritical` matches `isCritical`s of roll options for damage rolls

module/dice/d20-roll.mjs
Adds two new combinations of modifier keys to support forcing a roll to be with advantage or disadvantage, leading to six final combinations:
- `shift`: Fast forward with current advantage mode
- `alt`: Fast forward with added source of advantage
- `control`: Fast forward with added source of disadvantage
- `shift` + `alt`: Fast forward with forced advantage **(new)**
- `shift` + `control`: Fast forward with forced disadvantage **(new)**
- `alt` + `control`: Fast forward with flat roll
Closes #5338
=> [#5338] Add modifier combinations for forcing advantage mode

module/documents/actor/actor.mjs
Keeps favorites on transformed actors but removes any that refer to items that were removed during transformation.
Closes #5415
=> [#5415] Maintain favorites on transformed actors

module/documents/actor/actor.mjs
Previously hidden was being applied correctly to the transformed tokens but lost when the token was reverted, and it wasn't applied to unlinked tokens during transformation.
Closes #5108
=> [#5108] Preserve hidden state of token across transformation

module/config.mjs, module/data/actor/templates/attributes.mjs, module/data/actor/templates/common.mjs
Adds disadvantage based on system conditions:
- Checks: Exhaustion 1 (legacy only) & poisoned
- Saves: Exhaustion 3 (legacy only)
- Attacks: Exhaustion 3 (legacy only) & poisoned (attack roll mode isn't currently functional pending #5176)
- Dex Saves: Restrained
Also applies disadvantage to stealth checks if the equipped armor has the "Stealth Disadvantage" flag.
Closes #5172
=> [#5172] Apply disadvantage based on certain conditions

lang/en.json, module/applications/actor/transform-dialog.mjs, module/config.mjs, module/data/settings/transformation-setting.mjs, module/documents/actor/actor.mjs
Adds a formula for the minimum armor class when transforming to support Circle of the Moon Druids. For Wild Shape this formula is set to `(13 + @abilities.wis.mod) * @subclasses.moon`, which means it only applies if the character has the right subclass.
Closes #5410
=> [#5410] Add minimum armor class formula during transformation

less/v1/apps.less, module/applications/actor/npc-sheet.mjs, module/data/actor/npc.mjs, module/data/item/race.mjs, module/data/shared/movement-field.mjs, module/documents/actor/actor.mjs
Adds a semi-colon separrated special movement field to actor movement data for one-off values.
Also adds a small change to the movement attribution tooltip to use proper unit localization.
Closes #933
=> [#933] Add special field to actor movement

dnd5e.mjs, lang/en.json, module/applications/advancement/item-choice-config.mjs, module/applications/advancement/item-choice-flow.mjs, module/data/advancement/item-choice.mjs, module/data/item/spell.mjs, module/documents/advancement/item-choice.mjs, module/registry.mjs, templates/advancement/item-choice-config-details.hbs
Adds a new restriction when the spell type is selected in the item choice advancement that only allows spells from a specific spell list.
Also adds a subclass registry to match the class one to improve the naming of subclass spell lists.
Closes #5137
=> [#5137] Add spell list restriction to Choose Items advancement

lang/en.json, module/applications/components/damage-application.mjs, module/applications/components/effect-application.mjs, module/documents/chat-message.mjs, module/settings.mjs
Closes #5304 
Changed name of previous "never" option from "Expand All" to "Collapse After Use", added new "Never Collapse."
=> [#5304] Add "Never Collapse" collapse tray option, which only collapses if explicitly told to collapse

lang/en.json, module/applications/region-behavior/rotate-area-config.mjs, module/data/region-behavior/rotate-area.mjs
Rotates the primary region's shapes when the rotate region behavior is activated, and adds support for rotating other linked regions at the same time. The region shape updates are performed at the middle of the animation time along with walls, lights, & sounds.
=> Add support for rotation region shapes with rotate region behavior

module/data/region-behavior/rotate-area.mjs
Adjust how the rotate area behavior handles animations. Instead of triggering separate animations for each token and tile based on their individual update hooks, this uses the update hook for the region behavior to trigger a single animation for all elements.
Also updated how tokens are refreshed to ensure token vision is updated throughout the animation on V13.
=> Adjust how rotating regions are animated to eliminate delays

module/config.mjs, module/data/actor/templates/attributes.mjs, module/data/actor/templates/creature.mjs
Increases or decreases passive ability scores by `5` depending on whether the skill has advantage or disadvantage. Adds an option to `CONFIG` to set this value.
Closes #5130
=> [#5130] Adjust passive skills based on roll mode

lang/en.json, module/applications/advancement/ability-score-improvement-flow.mjs, module/applications/advancement/item-choice-flow.mjs, module/data/abstract/item-data-model.mjs, module/data/item/feat.mjs, module/documents/actor/actor.mjs, templates/items/details/details-feat.hbs
Adds a list of identifiers to feature prerequisites and require at least one of those other items to be present on the actor to take that feature using an Choose Items or ASI advancement.
To support this functionality `identifiedItems` has been added to actors along side `sourcedItems`. This groups items by their identifiers and optionally allows getting only items with a matching identifier and of a certain type.
Moves the prerequisite validation code into a new method on the feature item itself to avoid code duplication between the two advancement types.
Closes #5300
=> [#5300] Add feature prerequisites on other items

lang/en.json, module/applications/advancement/ability-score-improvement-flow.mjs, module/data/advancement/ability-score-improvement.mjs, module/documents/advancement/ability-score-improvement.mjs, packs/_source/feats24/epic-boon-feats/boon-of-combat-prowess.yml, packs/_source/feats24/epic-boon-feats/boon-of-dimensional-travel.yml, packs/_source/feats24/epic-boon-feats/boon-of-fate.yml, packs/_source/feats24/epic-boon-feats/boon-of-irresistible-offense.yml, packs/_source/feats24/epic-boon-feats/boon-of-spell-recall.yml, packs/_source/feats24/epic-boon-feats/boon-of-the-night-spirit.yml, packs/_source/feats24/epic-boon-feats/boon-of-truesight.yml, templates/advancement/ability-score-improvement-config-details.hbs
Adds a maximum field to the ability score improvement advancement to allow for specifying a higher maximum then is allowed by the actor.
Closes #5736
=> [#5736] Add separate ability maximum to ability score advancement

lang/en.json, module/documents/actor/actor.mjs, module/enrichers.mjs
Adds support for passing a tool into `rollSkill` alongside the skill to support gaining proficiency if the tool has it and not the skill and gaining advantage if both have proficiency.
This then extends the check enricher when using the modern rules to support rolling a skill check with an associated tool:
```
// Produces Dexterity (Sleight of Hand) check using Thieves' Tools
[[/check slt thief]]
[[/check skill=slt tool=thief]]
```
When the 2014 rules are used, or when more than one tool is used, the enricher will use the older style of specifying multiple different checks.
This also adds support for explicitly setting the rules version in an enricher using `rule=2014` or `rule=2024`.
=> [#5824] Add option to use skills with tool in line with 2024 rules

module/canvas/token.mjs
`TokenDocument#getOccupiedGridSpaceOffsets` returns 2D offsets (`{i, j}`), need to account for elevation. 
~~Note: Core would do `Math.floor((waypoint.elevation / canvas.grid.distance) + 1e-8)` if we were using `SquareGrid#getOffset` (and would also add `1e-8` prior to `Math.floor`-ing in a hexagonal grid, inside `HexagonalGrid#cubeRound`) so it's entirely possible that we should add it here as well. I haven't, because it's not "pretty," but verifying in the dev-support discord channel whether I should.~~ Added.
=> Ensure elevation is considered for tokens blocking movement

module/documents/chat-message.mjs
`isMiss` should be calculated prior to wiping the AC for non-GMs.
=> Hit/Miss icon in "Targets" section of attack card properly reflects hit/miss if attack visibility is set to "hideAC"

module/applications/actor/api/base-actor-sheet.mjs
Closes #5848.
This sorts skills and tools during the actor sheet preparation to solve issues with localization where the order of names differs from the English localization.
=> Sort skills and tools during sheet preparation

module/config.mjs, module/documents/actor/actor.mjs
- ~~Migrates `attributes.exhaustion` to an object with `value` and `delta` (null).~~
- Adds `exhaustionDelta` to `DND5E.restTypes`.
- Reduces levels of exhaustion on a long rest by an amount equal to ~~`delta` or~~ `exhaustionDelta` ~~(in that order).~~
- ~~`delta` isn't in the schema or shown anywhere, can only be modified by AEs.~~
- ~~Migrates `ActiveEffect#changes` that have `system.attributes.exhaustion` to append `.value` (unsure why anyone would do this).~~
- The Malnutrition status causes the `malnourished` condition effect, which prevents exhaustion reduction on rests entirely (which should be in accordance with both '14 and '24 rules).
=> [#5382] Reduce exhaustion when resting

lang/en.json, module/data/item/background.mjs, module/data/item/class.mjs, module/data/item/feat.mjs, module/data/item/race.mjs, module/data/item/subclass.mjs, module/data/item/templates/advancement.mjs
In addition to the default advancement created on Species, this adds Trait & Grant Item advancement to backgrounds (and ASI with the modern rules) and Hit Points, ASI, and a single Grant Items advancement for classes.
Creates a new `AdvancementTemplate` for item data models that encapsulates the default creation code so that individual types just need to override `_advancementToCreate` to indicate what should be created and call `preCreateAdvancement` during the `_preCreate` method.
Closes #5787
=> [#5787] Automatically create advancement on classes & backgrounds

lang/en.json, less/v2/activities.less, module/applications/activity/transform-sheet.mjs, module/data/activity/summon-data.mjs, module/data/activity/transform-data.mjs, module/documents/activity/transform.mjs, templates/activity/parts/transform-profiles.hbs
Adds mode to the Transform activity to select between the default CR mode and a new Direct Link mode (similar to how the Summon activity is set up). When the direct link mode is selected a UUID field replaces the CR field allowing adding a specific actor which will be used when transforming.
Closes #5581
=> [#5581] Add direct link mode for selection in Transform activity

dnd5e.mjs, module/data/item/spell.mjs, module/data/journal/spells.mjs, module/registry.mjs, templates/journal/spell/unlinked-spell.hbs
Adds `identifier` on unlinked spells in the config and adds a new `identifiers` getter in the spell list registry that returns all the identifiers for linked & unlinked spells in the list.
Modifies the spell list filtering in the compendium browser to use identifiers rather than UUIDs to allow for finding spells from multiple sources. This would allow a module to create a single spell list referencing SRD spells, but still allow the PHB versions of those spells to appear if that module is present.
Closes #5847
=> [#5847] Add `identifier` to unlinked spells on spell list page

lang/en.json, module/applications/activity/activity-sheet.mjs, module/applications/activity/activity-usage-dialog.mjs, module/applications/activity/cast-sheet.mjs, module/applications/activity/enchant-sheet.mjs, module/applications/activity/enchant-usage-dialog.mjs, module/applications/activity/forward-sheet.mjs, module/applications/activity/summon-sheet.mjs, module/applications/activity/utility-sheet.mjs, module/applications/components/enchantment-application.mjs, module/data/activity/enchant-data.mjs, module/documents/active-effect.mjs, module/documents/activity/enchant.mjs, templates/activity/attack-identity.hbs, templates/activity/cast-identity.hbs, templates/activity/forward-identity.hbs, templates/activity/identity.hbs, templates/activity/summon-identity.hbs, templates/activity/utility-identity.hbs
Adds an option to the Behavior section of Enchant activities that allows them to automatically enchant their parent item when used. When activated with this option, the Enchant activity will check to see if an enchantment from this item is already on its item. If one is found, it will be removed. If one isn't found, or the profile of the found enchantment doesn't match the configured profile, then a new enchantment will be created. This allows for easy toggling of an enchantment on an item, or swapping between multiple enchantments on a single item.
When multiple profiles are available, the usage dialog will select the currently applied one by default and indicate that it is active in the list.
To avoid code duplication, some of the enchantment application code has been moved from …
=> [#4895] Add automatic self enchanting option for Enchant activity

lang/en.json, less/v2/typography.less, less/variables/dark.less, less/variables/light.less, module/data/actor/npc.mjs, module/data/actor/templates/attributes.mjs, templates/actors/embeds/npc-embed.hbs
Modifies the embed template to move the definition lists into the context rather than the template to support different lists on the two different styles of stat blocks. Then apply different styling depending on what rules version is selected.
The styling is near the 2014 versions, but the background and borders are missing some of the texture that is present in the official designs.
Also adds `attributes.ac.label` which is used when displaying the stat block.
Closes #5483
=> [#5483] Add stat blocks formatted for 2014 rules

less/v2/chat.less, module/applications/chat-log.mjs, module/applications/components/chat-tray-element.mjs, module/applications/components/damage-application.mjs, module/applications/components/effect-application.mjs, module/applications/components/targeted-application-mixin.mjs
This proposes a two-pronged approach to alleviate the performance issues with target selection while there are a lot of chat messages:
1. Applies [`content-visibility: auto`](https://developer.mozilla.org/en-US/docs/Web/CSS/content-visibility) to the chat message card/effect/target trays on all but the most recent 5 chat messages. 
2. `buildTargetsList` will only run when the chat tray is open. Also registers an event listener for the `toggled` event so any expanded sections are correctly updated.
Each change on its own made a noticable difference. The second is the bigger performance boost as long as you don't have too many expanded target selections in chat, and the first helps alleviate the rest.
I don't have a ton of experience with Mixins, but I suspect my changes to …
=> [#5806] Alleviate chat forced reflow/target selection performance issues

lang/en.json, module/applications/actor/api/base-actor-sheet.mjs, module/applications/actor/npc-sheet.mjs, module/data/activity/fields/consumption-targets-field.mjs, module/data/actor/npc.mjs, module/documents/activity/mixin.mjs, module/documents/token.mjs, module/utils.mjs, templates/actors/npc-header.hbs
Change legendary actions and resistances from storing a `value` to storing the number of `spent`. This leads to the correct number of available legendaries when an NPC enters or leaves their lair.
Some adjustments were made to `consumeAttribute` to allow for adjusting `spent` when the consumption target is `value`. This helps ensure the consumption limits are correct and that no migration is needed for consumption targets.
Closes #5025
=> [#5025] Switch legendaries to use `spent` rather than `value`

module/canvas/ruler.mjs, module/config.mjs
If total movement cost is <= selected move speed, green. If <= double, yellow. Otherwise red. The colors themselves are configurable under `CONFIG.DND5E.tokenRulerColors`.
Implementation notes:
- Only shows on the client attempting the movement
- Can be disabled using the "Disable Movement Automation" setting
- Currently treats all `walkFallback` actions as the maximum between that action's speed and walk speed, for coloring purposes
- Only shows coloring when previewing a movement (i.e. actively dragging)
- Currently colors the entire segment the same color, so a single move going from "within max speed" to ">3x max speed" will be entirely red. (If on a gridded map, the grid highlighting will _not_ be a single color).
=> Color ruler segment & grid highlights according to movement speed

dnd5e.mjs, module/applications/award.mjs, module/applications/currency-manager.mjs, module/data/abstract/actor-data-model.mjs, module/data/actor/group.mjs, module/data/collection/_module.mjs, module/data/collection/actors-collection.mjs, module/documents/actor/actor.mjs, module/tooltips.mjs
Adds `game.actors.party` which returns the primary party. Useful to not have to look up the setting manually and use optional chaining.
=> Add convenience getter for primary party

module/applications/item/item-sheet.mjs
Just a small change to restore the option to modify advancement choices. It looks like this was a side effect of [this change](https://github.com/foundryvtt/dnd5e/commit/054e58d02ea0e6ceb65dd44a396678b9a4e2f9f7#diff-97656250854f673ff52d31bfa12d06fe197a71e0e26772f6c33736490b2002dbR417).
I confirmed editing/creating items outside of actors still works as expected. 
Closes #5914.
=> [#5914] Update item-sheet maxLevel check from `!configMode` to `this.item.parent`

module/applications/actor/api/base-actor-sheet.mjs
Closes #5944 
Previously, if any `itemUses`-type consumption target, assumed the parent item of the cast activity. Now, will try to grab the specified item by ID (falling back to parent item, as it should for the self-targeting empty string).
=> [#5944] Cached spell `uses` reference actual consumption target when necessary

module/documents/actor/actor.mjs
Need to check the iterated actor, not the compendium one.
Closes #5999
=> [#5999] Linked actor summon fix

module/documents/token.mjs
Closes #6002 
By Foundry's own typedef, it shouldn't ever be undefined. However, in `Token._configureAnimationMovementSpeed` it's called without any parameters, so for the time being at least we must account for that possibility.
=> [#6002] Account for `token` being undefined in `getAnimationOptions`

templates/actors/character-header.hbs
An effect on an actor targeting `name` repeatedly applies.
=> [#6078] Use source name in edit mode on character sheets

module/canvas/token.mjs
If any part of a movement contains a token resize, don't consider whether tokens would block the path during said movement.
=> Don't consider token-blocking for resize "movements"

module/canvas/ruler.mjs
Any teleport action (blink or displace) will skip the ruler coloring and use the default logic instead.
Other movement types not found in `CONFIG.DND5E.movementTypes` will now use the walk fallback.
Closes #6123
=> [#6123] Fix token ruler always displaying red for certain actions

module/data/shared/duration-field.mjs
When I cast a spell with a duration, the concentration value gets applied to the active effect when using hour/day/year etc., but not when using months. This appears to be because the conversion function is missing months.
Since D&D uses a 30 day month (assuming we can ignore the in-between days), this is an easy tweak. See screenshot below for issue:
=> Fixed missing month conversion in duration field
